// UI chrome translations (labels, buttons, section headings).
// Keyed by string id then by language code.

export const UI = {
    appTitle: { en: "Microsoft Ecosystem", fr: "Écosystème Microsoft", de: "Microsoft Ökosystem", es: "Ecosistema Microsoft", it: "Ecosistema Microsoft", ar: "منظومة Microsoft", nl: "Microsoft Ecosysteem" },
    appSubtitle: { en: "Exhaustive Business Applications Map", fr: "Carte Exhaustive des Applications", de: "Umfassende Anwendungslandkarte", es: "Mapa Exhaustivo de Aplicaciones", it: "Mappa Esaustiva delle Applicazioni", ar: "خريطة شاملة لتطبيقات الأعمال", nl: "Uitgebreide Bedrijfsapplicatiekaart" },
    home: { en: "Home", fr: "Accueil", de: "Startseite", es: "Inicio", it: "Home", ar: "الرئيسية", nl: "Home" },
    mainCategories: { en: "Strategic Pillars", fr: "Piliers Stratégiques", de: "Strategische Säulen", es: "Pilares Estratégicos", it: "Pilastri Strategici", ar: "الركائز الاستراتيجية", nl: "Strategische Pijlers" },
    heroTitle: { en: "The Agentic AI Era Ecosystem", fr: "L'écosystème de l'Ère de l'IA Agentique", de: "Das Ökosystem im KI-Zeitalter", es: "El Ecosistema en la Era de la IA Agéntica", it: "L'ecosistema dell'era dell'IA Agente", ar: "منظومة عصر وكلاء الذكاء الاصطناعي", nl: "Het Ecosysteem van het Agentic AI-Tijdperk" },
    heroDesc: { en: "A comprehensive analysis of business applications, covering architectural foundations, core workflows, front-office, back-office operations, and sustainability.", fr: "Une analyse complète des applications métier, couvrant les fondations architecturales, les workflows essentiels, les opérations front-office, back-office et la durabilité.", de: "Eine umfassende Analyse von Geschäftsanwendungen mit Schwerpunkt auf architektonischen Grundlagen, Kernworkflows, Front-Office, Back-Office-Betrieb und Nachhaltigkeit.", es: "Un análisis exhaustivo de las aplicaciones empresariales, que abarca los fundamentos arquitectónicos, los flujos de trabajo principales, las operaciones front-office, back-office y la sostenibilidad.", it: "Un'analisi completa delle applicazioni aziendali, che copre fondamenti architetturali, flussi di lavoro principali, operazioni front-office, back-office e sostenibilità.", nl: "Een uitgebreide analyse van bedrijfsapplicaties, die architectonische fundamenten, kernworkflows, front-office, back-office en duurzaamheid behandelt.", ar: "تحليل شامل لتطبيقات الأعمال، يشمل الأسس المعمارية، ومسارات العمل الجوهرية، والواجهات الأمامية، والعمليات الخلفية، والاستدامة." },
    unifiedTitle: { en: "One Unified Platform. Infinite Adaptability.", fr: "Une Plateforme Unifiée. Adaptabilité Infinie.", de: "Eine Einheitliche Plattform. Unendliche Anpassbarkeit.", es: "Una Plataforma Unificada. Adaptabilidad Infinita.", it: "Una Piattaforma Unificata. Adattabilità Infinita.", ar: "منصة واحدة موحدة. قدرة لا نهائية على التكيف.", nl: "Eén Geünificeerd Platform. Oneindige Aanpasbaarheid." },
    unifiedDesc1: { en: "Built on a shared architectural foundation (Dataverse and the Common Data Model), eliminating data silos.", fr: "Construite sur une fondation architecturale partagée (Dataverse et Common Data Model), éliminant les silos de données.", de: "Aufgebaut auf einer gemeinsamen architektonischen Grundlage (Dataverse und Common Data Model), die Datensilos beseitigt.", es: "Construida sobre una base arquitectónica compartida (Dataverse y Common Data Model), eliminando los silos de datos.", it: "Costruita su una fondazione architetturale condivisa (Dataverse e Common Data Model), eliminando i silos di dati.", nl: "Gebouwd op een gedeeld architectonisch fundament (Dataverse en het Common Data Model), waarmee datasilo's worden geëlimineerd.", ar: "مبنية على أساس معماري مشترك (Dataverse ونموذج البيانات المشترك)، مما يقضي على عزل البيانات." },
    unifiedDesc2: { en: "Highly adaptable and seamlessly integrates with third-party tools, ERP systems, and external data sources.", fr: "Hautement adaptable et s'intègre de manière transparente aux outils tiers, aux systèmes ERP et aux sources de données externes.", de: "Hochgradig anpassbar und nahtlos integriert mit Drittanbieter-Tools, ERP-Systemen und externen Datenquellen.", es: "Altamente adaptable y se integra perfectamente con herramientas de terceros, sistemas ERP y fuentes de datos externas.", it: "Altamente adattabile e si integra perfettamente con strumenti di terze parti, sistemi ERP e fonti di dati esterne.", nl: "Zeer aanpasbaar en naadloos geïntegreerd met externe tools, ERP-systemen en externe databronnen.", ar: "قابلة للتكيف بدرجة عالية والدمج بسلاسة مع أدوات الجهات الخارجية، وأنظمة تخطيط موارد المؤسسات (ERP)، ومصادر البيانات الخارجية." },
    unifiedDesc3: { en: "Powered by the Model Context Protocol (MCP), enabling AI agents to securely access external systems.", fr: "Propulsée par le Model Context Protocol (MCP), permettant aux agents IA d'accéder en toute sécurité aux systèmes externes.", de: "Angetrieben durch das Model Context Protocol (MCP), das KI-Agenten den sicheren Zugriff auf externe Systeme ermöglicht.", es: "Impulsada por el Model Context Protocol (MCP), permitiendo a los agentes de IA acceder de forma segura a sistemas externos.", it: "Basata sul Model Context Protocol (MCP), che consente agli agenti IA di accedere in modo sicuro ai sistemi esterni.", nl: "Aangedreven door het Model Context Protocol (MCP), waarmee AI-agenten veilig toegang krijgen tot externe systemen.", ar: "مدعومة بـ Model Context Protocol (MCP)، مما يتيح لوكلاء الذكاء الاصطناعي الوصول الآمن إلى الأنظمة الخارجية." },
    exploreProducts: { en: "Explore Category", fr: "Explorer la Catégorie", de: "Kategorie erkunden", es: "Explorar Categoría", it: "Esplora Categoria", ar: "استكشاف الفئة", nl: "Categorie Verkennen" },
    partOf: { en: "Category:", fr: "Catégorie :", de: "Kategorie:", es: "Categoría:", it: "Categoria:", ar: "الفئة:", nl: "Categorie:" },
    capabilities: { en: "Core & Advanced Capabilities", fr: "Capacités Fondamentales et Avancées", de: "Kern- und erweiterte Funktionen", es: "Capacidades Fundamentales y Avanzadas", it: "Funzionalità Base e Avanzate", ar: "القدرات الأساسية والمتقدمة", nl: "Kern- en geavanceerde mogelijkheden" },    targetAudience: { en: "Target Audience", fr: "Public Cible", de: "Zielgruppe", es: "Público Objetivo", it: "Pubblico di Riferimento", ar: "الجمهور المستهدف", nl: "Doelgroep" },
    architecture: { en: "Architecture", fr: "Architecture", de: "Architektur", es: "Arquitectura", it: "Architettura", ar: "البنية المعمارية", nl: "Architectuur" },
    guidedTour: { en: "Try the guided tour", fr: "Essayer la visite guidée", de: "Geführte Tour starten", es: "Probar el tour guiado", it: "Prova il tour guidato", ar: "جرّب الجولة التفاعلية", nl: "Probeer de rondleiding" },
    integrations: { en: "Integrations", fr: "Intégrations", de: "Integrationen", es: "Integraciones", it: "Integrazioni", ar: "التكامل", nl: "Integraties" },
    searchPlaceholder: { en: "Search products, features...", fr: "Rechercher...", de: "Suchen...", es: "Buscar...", it: "Cerca...", ar: "ابحث عن المنتجات والميزات...", nl: "Zoeken..." },
    searchResults: { en: "Search results for:", fr: "Résultats pour :", de: "Suchergebnisse für:", es: "Resultados para:", it: "Risultati per:", ar: "نتائج البحث عن:", nl: "Resultaten voor:" },
    found: { en: "Found", fr: "Trouvé", de: "Gefunden", es: "Encontrado", it: "Trovato", ar: "تم العثور على", nl: "Gevonden" },
    itemsMatching: { en: "matching entities.", fr: "entités.", de: "Entitäten.", es: "entidades.", it: "elementi.", ar: "من الكيانات المطابقة.", nl: "items." },    noResults: { en: "No results found", fr: "Aucun résultat", de: "Keine Ergebnisse", es: "Sin resultados", it: "Nessun risultato", ar: "لم يتم العثور على نتائج", nl: "Geen resultaten" },
    checkSpelling: { en: "Please check your spelling.", fr: "Vérifiez l'orthographe.", de: "Bitte überprüfen Sie die Rechtschreibung.", es: "Compruebe la ortografía.", it: "Controlla l'ortografia.", ar: "يرجى التحقق من الكلمات المكتوبة.", nl: "Controleer de spelling." },
    pricing: { en: "Pricing", fr: "Tarification", de: "Preise", es: "Precios", it: "Prezzi", ar: "التسعير", nl: "Prijzen" },
    pricingBase: { en: "Base", fr: "Base", de: "Basis", es: "Base", it: "Base", ar: "أساسي", nl: "Basis" },
    pricingAttach: { en: "Attach", fr: "Complémentaire", de: "Add-on-Lizenz", es: "Complementaria", it: "Aggiuntiva", ar: "إرفاق", nl: "Aanvullend" },
    perUserMonth: { en: "/user/month", fr: "/utilisateur/mois", de: "/Benutzer/Monat", es: "/usuario/mes", it: "/utente/mese", ar: "/مستخدم/شهر", nl: "/gebruiker/maand" },
    perTenantMonth: { en: "/tenant/month", fr: "/locataire/mois", de: "/Mandant/Monat", es: "/inquilino/mes", it: "/tenant/mese", ar: "/مستأجر/شهر", nl: "/tenant/maand" },
    perMonth: { en: "/month", fr: "/mois", de: "/Monat", es: "/mes", it: "/mese", ar: "/شهر", nl: "/maand" },
    startingAt: { en: "Starting at", fr: "À partir de", de: "Ab", es: "Desde", it: "A partire da", ar: "يبدأ من", nl: "Vanaf" },
    endOfSale: { en: "End of Sale", fr: "Fin de vente", de: "Verkaufsende", es: "Fin de venta", it: "Fine vendita", ar: "انتهاء البيع", nl: "Einde verkoop" },
    pricingNote: { en: "Pricing Note", fr: "Note tarifaire", de: "Preishinweis", es: "Nota de precios", it: "Nota sui prezzi", ar: "ملاحظة التسعير", nl: "Prijsnotitie" },
    fromPrice: { en: "From", fr: "À partir de", de: "Ab", es: "Desde", it: "Da", ar: "من", nl: "Vanaf" },
    perPackMonth: { en: "/pack/month", fr: "/pack/mois", de: "/Paket/Monat", es: "/pack/mes", it: "/pack/mese", ar: "/حزمة/شهر", nl: "/pack/maand" },
    paidYearly: { en: "Billed annually", fr: "Facturé annuellement", de: "Jährliche Abrechnung", es: "Facturación anual", it: "Fatturato annualmente", ar: "يُدفع سنوياً", nl: "Jaarlijks gefactureerd" },
    soldInPacksOf: { en: "Sold in packs of", fr: "Vendu par packs de", de: "Verkauft in Paketen von", es: "Vendido en packs de", it: "Venduto in pack da", ar: "يُباع في حزم من", nl: "Verkocht in pakketten van" },
    tierRange: { en: "Total people", fr: "Total de personnes", de: "Personen gesamt", es: "Total de personas", it: "Persone totali", ar: "إجمالي الأشخاص", nl: "Totaal personen" },
    moreThan: { en: "More than", fr: "Plus de", de: "Mehr als", es: "Más de", it: "Più di", ar: "أكثر من", nl: "Meer dan" },
    attachQualifiers: { en: "Qualifying base licenses for Attach pricing", fr: "Licences de base éligibles au prix Attach", de: "Qualifizierende Basislizenzen für Attach-Preis", es: "Licencias base elegibles para el precio Attach", it: "Licenze base qualificanti per il prezzo Attach", ar: "التراخيص الأساسية المؤهلة لسعر الإرفاق", nl: "Kwalificerende basislicenties voor Attach-prijs" },
    cdmSchemaTitle: { en: "Common Data Model Schema", fr: "Schéma Common Data Model", de: "Common Data Model-Schema", es: "Esquema del Common Data Model", it: "Schema Common Data Model", ar: "مخطط Common Data Model", nl: "Common Data Model-schema" },
    cdmCoreNote: { en: "Core entities are shared across every Dynamics 365 app and extension area.", fr: "Les entités Core sont partagées entre toutes les applications et extensions Dynamics 365.", de: "Core-Entitäten werden von allen Dynamics 365-Apps und Erweiterungen geteilt.", es: "Las entidades Core se comparten entre todas las aplicaciones y extensiones de Dynamics 365.", it: "Le entità Core sono condivise tra tutte le app e le aree di estensione di Dynamics 365.", ar: "تتشارك كيانات Core بين جميع تطبيقات Dynamics 365 ومناطق الامتداد.", nl: "Core-entiteiten worden gedeeld tussen alle Dynamics 365-apps en uitbreidingsgebieden." },
    cdmAttributes: { en: "Attributes", fr: "Attributs", de: "Attribute", es: "Atributos", it: "Attributi", ar: "السمات", nl: "Attributen" },
    cdmCaption: { en: "Illustrative example — entity sets evolve as Common Data Model expands with industry partners and subject matter experts.", fr: "Exemple illustratif — les ensembles d'entités évoluent avec l'expansion de Common Data Model par les partenaires industriels et experts métier.", de: "Beispielhafte Darstellung – die Entitätssätze entwickeln sich, während Common Data Model mit Branchenpartnern und Fachexperten erweitert wird.", es: "Ejemplo ilustrativo: los conjuntos de entidades evolucionan a medida que Common Data Model se amplía con socios sectoriales y expertos.", it: "Esempio illustrativo — gli insiemi di entità evolvono con l'espansione del Common Data Model con partner di settore ed esperti.", ar: "مثال توضيحي — تتطور مجموعات الكيانات مع توسع Common Data Model بفضل شركاء الصناعة وخبراء المجال.", nl: "Illustratief voorbeeld — entiteitsets evolueren naarmate Common Data Model uitbreidt met branchepartners en domeinexperts." }
};

// Safe UI translation lookup with English fallback.
export function getUI(key, lang) {
    if (UI[key] && UI[key][lang]) return UI[key][lang];
    return UI[key]?.en ?? "";
}
