import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Unify your storefronts. Win the customer journey.',
        summary: 'Dynamics 365 Commerce unifies your digital and physical storefronts. Copilot automates product merchandising, AI drives hyper-personalized recommendations, and a single inventory model bridges online and in-store operations — so your AOV grows, your conversion rates rise, and your time-to-market collapses.',
        kpis: [
            { value: '180%+', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '+10–15%', label: 'Average Order Value (AOV)', kind: 'outcome' },
            { value: '+5–10%', label: 'Overall conversion rate', kind: 'outcome' },
            { value: '−50–70%', label: 'Time spent on product enrichment / copy', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Customer Lifetime Value', kind: 'outcome' },
        ],
        bqPre: 'Driving omnichannel revenue growth and maximizing Customer Lifetime Value is your core mandate, but currently, siloed systems between your online and physical stores lead to localized stockouts, while manual merchandising delays your time-to-market.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'If your channels remain disconnected and your teams are bogged down in manual data entry, ',
        bqHighlight: 'how will you increase your Average Order Value and prevent customers from abandoning their carts for more seamless competitors?',
        figcaption: 'Strategic question framing the business case for Dynamics 365 Commerce.',
        bridge: 'Here is how Dynamics 365 Commerce answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from the merchandiser publishing a new product all the way up to board-level retail strategy.',
        rungs: [
            { title: 'New products live in hours, not weeks', audience: 'Your merchandisers & store associates', what: 'Copilot instantly generates rich, SEO-optimized product descriptions for the website, while the unified POS gives store associates instant cross-channel inventory visibility.', outcome: 'You drastically cut the manual effort to launch new products online and empower store staff to confidently answer any customer question.', kpis: [{ label: '50–70% reduction in time spent on product enrichment / copywriting', kind: 'efficiency' }, { label: 'Shorter customer wait times in-store', kind: 'efficiency' }] },
            { title: 'Buy anywhere, fulfill from anywhere', audience: 'Your store ops & e-commerce managers', what: 'Unified inventory across digital, store, and warehouse enables seamless Buy Online, Pick Up In Store (BOPIS) and infinite-aisle capabilities — without complex manual workarounds.', outcome: 'You fulfill orders from the most efficient location and ensure customers never hit a dead end because of a localized stockout.', kpis: [{ label: 'Faster order fulfillment cycle times', kind: 'efficiency' }, { label: 'Significant reduction in out-of-stock (OOS) lost sales', kind: 'outcome' }] },
            { title: 'One customer, one profile, one experience', audience: 'Your VP of E-Commerce', what: 'The platform breaks down the walls between online browsing history, physical store purchases, and loyalty programs to create a single, unified customer profile.', outcome: 'You replace generic storefronts with an AI engine that surfaces hyper-personalized product recommendations at the exact moment of intent.', kpis: [{ label: '100% unified cross-channel visibility', kind: 'efficiency' }, { label: 'Higher click-through rates on automated recommendations', kind: 'outcome' }] },
            { title: 'Bigger baskets, more conversions', audience: 'Your Chief Retail / Digital Officer', what: 'Frictionless, personalized journeys — whether the customer is checking out online or talking to an associate in-store — directly influence purchasing behavior and recapture lost sales.', outcome: 'You up-sell and cross-sell every shopper, maximizing the revenue yield of every transaction.', kpis: [{ label: '10–15% increase in Average Order Value (AOV)', kind: 'outcome' }, { label: '5–10% increase in overall conversion rates', kind: 'outcome' }] },
            { title: 'A unified omnichannel engine', audience: 'Your Chief Retail Officer & Board', what: 'The business shifts from a fragmented collection of sales channels into a unified, high-margin omnichannel engine that breeds deep brand loyalty.', outcome: 'You deliver the resilient, modern retail experience consumers expect — and grow the lifetime value of every customer you win.', kpis: [{ label: '180%+ ROI over 3 years', kind: 'outcome' }, { label: 'Measurable expansion in Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Source for the 180%+ ROI, conversion-rate improvements, and the financial impact of unified inventory visibility reducing lost sales.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Source for the up-to-70% productivity gains for marketing and merchandising teams using Copilot to generate product copy and enrich catalogs.' },
        ],
    },
    fr: {
        headline: 'Unifiez vos points de vente. Gagnez le parcours client.',
        summary: 'Dynamics 365 Commerce unifie vos points de vente digitaux et physiques. Copilot automatise le merchandising produit, l\'IA génère des recommandations hyper-personnalisées et un modèle de stock unique relie les opérations online et en magasin — pour augmenter votre AOV, faire grimper vos taux de conversion et écraser votre time-to-market.',
        kpis: [
            { value: '180 %+', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '+10–15 %', label: 'Panier moyen (AOV)', kind: 'outcome' },
            { value: '+5–10 %', label: 'Taux de conversion global', kind: 'outcome' },
            { value: '−50–70 %', label: 'Temps passé à enrichir les fiches produit', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Valeur vie client', kind: 'outcome' },
        ],
        bqPre: 'Faire croître le chiffre d\'affaires omnicanal et maximiser la Customer Lifetime Value est votre mission centrale, mais aujourd\'hui des systèmes cloisonnés entre vos magasins en ligne et physiques créent des ruptures locales, pendant que le merchandising manuel ralentit votre time-to-market.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si vos canaux restent déconnectés et vos équipes englouties dans la saisie manuelle, ',
        bqHighlight: 'comment ferez-vous croître votre panier moyen et empêcherez-vous vos clients d\'abandonner leur panier pour des concurrents plus fluides ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Dynamics 365 Commerce.',
        bridge: 'Voici comment Dynamics 365 Commerce y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — du merchandiser qui publie un nouveau produit jusqu\'à la stratégie retail au niveau du conseil d\'administration.',
        rungs: [
            { title: 'De nouveaux produits en ligne en quelques heures, plus en semaines', audience: 'Vos merchandisers et vendeurs en magasin', what: 'Copilot génère instantanément des descriptions produits riches et optimisées pour le SEO, pendant que le POS unifié donne aux vendeurs en magasin une visibilité immédiate sur le stock cross-canal.', outcome: 'Vous réduisez radicalement l\'effort manuel pour lancer un produit en ligne et donnez aux équipes magasin les moyens de répondre avec assurance à toute question client.', kpis: [{ label: '50–70 % de temps en moins consacré à l\'enrichissement / la rédaction des fiches produit', kind: 'efficiency' }, { label: 'Temps d\'attente client en magasin réduit', kind: 'efficiency' }] },
            { title: 'Achetez n\'importe où, livrez depuis n\'importe où', audience: 'Vos responsables ops magasin et e-commerce', what: 'Un stock unifié entre digital, magasin et entrepôt permet le Click & Collect (BOPIS) et l\'infinite aisle de manière fluide — sans contournement manuel complexe.', outcome: 'Vous exécutez chaque commande depuis le point le plus efficace et garantissez qu\'aucun client ne reste bloqué à cause d\'une rupture localisée.', kpis: [{ label: 'Cycles d\'exécution de commande plus rapides', kind: 'efficiency' }, { label: 'Réduction significative des ventes perdues pour rupture (OOS)', kind: 'outcome' }] },
            { title: 'Un client, un profil, une expérience', audience: 'Votre VP E-Commerce', what: 'La plateforme abat les murs entre l\'historique de navigation en ligne, les achats en magasin physique et les programmes de fidélité pour créer un profil client unique et unifié.', outcome: 'Vous remplacez les vitrines génériques par un moteur d\'IA qui fait remonter des recommandations produits hyper-personnalisées au moment exact de l\'intention d\'achat.', kpis: [{ label: '100 % de visibilité unifiée cross-canal', kind: 'efficiency' }, { label: 'Taux de clic plus élevés sur les recommandations automatisées', kind: 'outcome' }] },
            { title: 'Des paniers plus gros, plus de conversions', audience: 'Votre Chief Retail / Digital Officer', what: 'Des parcours fluides et personnalisés — que le client passe en caisse en ligne ou échange avec un vendeur en magasin — influencent directement le comportement d\'achat et récupèrent les ventes perdues.', outcome: 'Vous up-sellez et cross-sellez chaque acheteur, en maximisant le rendement de chaque transaction.', kpis: [{ label: '+10–15 % sur le panier moyen (AOV)', kind: 'outcome' }, { label: '+5–10 % sur le taux de conversion global', kind: 'outcome' }] },
            { title: 'Un moteur omnicanal unifié', audience: 'Votre Chief Retail Officer et conseil d\'administration', what: 'L\'entreprise passe d\'une collection fragmentée de canaux de vente à un moteur omnicanal unifié, à forte marge, qui nourrit une fidélité de marque profonde.', outcome: 'Vous délivrez l\'expérience retail moderne et résiliente que les consommateurs attendent — et faites croître la valeur vie de chaque client conquis.', kpis: [{ label: 'Plus de 180 % de ROI sur 3 ans', kind: 'outcome' }, { label: 'Expansion mesurable de la Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Source du ROI de plus de 180 %, des gains de taux de conversion et de l\'impact financier de la visibilité de stock unifiée qui réduit les ventes perdues.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Source des gains de productivité jusqu\'à 70 % pour les équipes marketing et merchandising utilisant Copilot pour générer le contenu produit et enrichir les catalogues.' },
        ],
    },
    de: {
        headline: 'Vereinen Sie Ihre Storefronts. Gewinnen Sie die Customer Journey.',
        summary: 'Dynamics 365 Commerce vereint Ihre digitalen und physischen Storefronts. Copilot automatisiert das Produkt-Merchandising, KI liefert hyperpersonalisierte Empfehlungen und ein einheitliches Bestandsmodell verbindet Online- und Filialbetrieb — damit Ihr AOV wächst, Ihre Conversion-Rates steigen und Ihre Time-to-Market schrumpft.',
        kpis: [
            { value: '180 %+', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '+10–15 %', label: 'Durchschnittlicher Bestellwert (AOV)', kind: 'outcome' },
            { value: '+5–10 %', label: 'Gesamt-Conversion-Rate', kind: 'outcome' },
            { value: '−50–70 %', label: 'Zeit für Produktanreicherung / Texte', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Customer Lifetime Value', kind: 'outcome' },
        ],
        bqPre: 'Omnichannel-Umsatzwachstum zu treiben und den Customer Lifetime Value zu maximieren ist Ihr Kernauftrag — doch heute sorgen entkoppelte Systeme zwischen Online- und Filialgeschäft für lokale Bestandsausfälle, während manuelles Merchandising Ihre Time-to-Market bremst.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Wenn Ihre Kanäle weiterhin getrennt bleiben und Ihre Teams in manueller Dateneingabe versinken — ',
        bqHighlight: 'wie wollen Sie dann Ihren durchschnittlichen Bestellwert steigern und verhindern, dass Ihre Kund:innen den Warenkorb zugunsten reibungsloserer Wettbewerber verlassen?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Dynamics 365 Commerce.',
        bridge: 'So beantwortet Dynamics 365 Commerce diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — von der Merchandiser:in, die ein neues Produkt veröffentlicht, bis zur Retail-Strategie auf Vorstandsebene.',
        rungs: [
            { title: 'Neue Produkte live in Stunden statt Wochen', audience: 'Ihre Merchandiser:innen und Filialmitarbeitenden', what: 'Copilot erzeugt sofort reichhaltige, SEO-optimierte Produktbeschreibungen für die Website, während das vereinheitlichte POS den Filialmitarbeitenden eine sofortige kanalübergreifende Bestandsicht gibt.', outcome: 'Sie senken den manuellen Aufwand für den Online-Launch neuer Produkte drastisch und versetzen das Filialteam in die Lage, jede Kundenfrage souverän zu beantworten.', kpis: [{ label: '50–70 % weniger Zeit für Produktanreicherung / Copywriting', kind: 'efficiency' }, { label: 'Kürzere Wartezeiten der Kund:innen in der Filiale', kind: 'efficiency' }] },
            { title: 'Überall kaufen, von überall ausliefern', audience: 'Ihre Filial-Operations und E-Commerce-Manager:innen', what: 'Ein vereinheitlichter Bestand über Digital, Filiale und Lager hinweg ermöglicht nahtloses Click & Collect (BOPIS) und Infinite-Aisle-Funktionen — ohne komplexe manuelle Workarounds.', outcome: 'Sie erfüllen Bestellungen vom effizientesten Standort aus und stellen sicher, dass Kund:innen nie wegen einer lokalen Bestandslücke vor einer Sackgasse stehen.', kpis: [{ label: 'Schnellere Order-Fulfillment-Zykluszeiten', kind: 'efficiency' }, { label: 'Deutliche Reduktion verlorener Umsätze durch Out-of-Stock (OOS)', kind: 'outcome' }] },
            { title: 'Eine Kundin, ein Profil, ein Erlebnis', audience: 'Ihre VP E-Commerce', what: 'Die Plattform reißt die Mauern zwischen Online-Surfhistorie, Filialeinkäufen und Loyalty-Programmen ein und schafft ein einziges, vereinheitlichtes Kundenprofil.', outcome: 'Sie ersetzen generische Storefronts durch eine KI, die hyperpersonalisierte Produktempfehlungen genau im Moment der Kaufabsicht ausspielt.', kpis: [{ label: '100 % vereinheitlichte kanalübergreifende Sichtbarkeit', kind: 'efficiency' }, { label: 'Höhere Klickraten auf automatisierte Empfehlungen', kind: 'outcome' }] },
            { title: 'Größere Warenkörbe, mehr Conversions', audience: 'Ihre Chief Retail / Digital Officer', what: 'Reibungslose, personalisierte Journeys — egal ob die Kundin online auscheckt oder im Laden mit einer Mitarbeiter:in spricht — beeinflussen das Kaufverhalten direkt und holen verlorene Umsätze zurück.', outcome: 'Sie machen aus jedem Einkauf Up-Selling und Cross-Selling und maximieren den Umsatzbeitrag jeder Transaktion.', kpis: [{ label: '10–15 % höherer durchschnittlicher Bestellwert (AOV)', kind: 'outcome' }, { label: '5–10 % höhere Gesamt-Conversion-Rate', kind: 'outcome' }] },
            { title: 'Eine vereinheitlichte Omnichannel-Engine', audience: 'Ihre Chief Retail Officer und Vorstand', what: 'Das Geschäft verwandelt sich von einer fragmentierten Sammlung von Vertriebskanälen in eine vereinheitlichte, margenstarke Omnichannel-Engine, die tiefe Markenloyalität schafft.', outcome: 'Sie liefern das resiliente, moderne Retail-Erlebnis, das Konsument:innen erwarten — und steigern den Lifetime-Wert jeder gewonnenen Kund:in.', kpis: [{ label: 'Über 180 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Messbarer Anstieg des Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Quelle für den ROI von über 180 %, die Verbesserungen der Conversion-Rate und die finanzielle Wirkung einer vereinheitlichten Bestandssicht zur Reduktion verlorener Umsätze.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Quelle für die Produktivitätsgewinne von bis zu 70 % bei Marketing- und Merchandising-Teams, die Copilot zur Generierung von Produkttexten und Katalog-Anreicherung einsetzen.' },
        ],
    },
    es: {
        headline: 'Unifique sus tiendas. Gane el customer journey.',
        summary: 'Dynamics 365 Commerce unifica sus tiendas digitales y físicas. Copilot automatiza el merchandising de producto, la IA impulsa recomendaciones hiperpersonalizadas y un único modelo de inventario conecta las operaciones online y en tienda — para que su AOV crezca, sus tasas de conversión suban y su time-to-market se reduzca.',
        kpis: [
            { value: '180 %+', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '+10–15 %', label: 'Valor medio del pedido (AOV)', kind: 'outcome' },
            { value: '+5–10 %', label: 'Tasa de conversión global', kind: 'outcome' },
            { value: '−50–70 %', label: 'Tiempo dedicado al enriquecimiento de fichas', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Valor de vida del cliente', kind: 'outcome' },
        ],
        bqPre: 'Impulsar el crecimiento de los ingresos omnicanal y maximizar el Customer Lifetime Value es su mandato central, pero hoy los sistemas en silo entre sus tiendas online y físicas provocan roturas de stock localizadas, mientras que el merchandising manual ralentiza su time-to-market.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si sus canales siguen desconectados y sus equipos atascados en la entrada manual de datos, ',
        bqHighlight: '¿cómo va a aumentar el valor medio del pedido y evitar que los clientes abandonen su carrito a favor de competidores más fluidos?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Dynamics 365 Commerce.',
        bridge: 'Así responde Dynamics 365 Commerce',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde la merchandiser que publica un nuevo producto hasta la estrategia retail a nivel de consejo.',
        rungs: [
            { title: 'Productos nuevos en horas, no en semanas', audience: 'Sus merchandisers y personal de tienda', what: 'Copilot genera al instante descripciones de producto ricas y optimizadas para SEO en la web, mientras el POS unificado da al personal de tienda visibilidad inmediata del inventario en todos los canales.', outcome: 'Reduce drásticamente el esfuerzo manual para lanzar nuevos productos online y permite al personal de tienda responder con seguridad a cualquier pregunta del cliente.', kpis: [{ label: '50–70 % menos tiempo dedicado al enriquecimiento / redacción de fichas de producto', kind: 'efficiency' }, { label: 'Menores tiempos de espera del cliente en tienda', kind: 'efficiency' }] },
            { title: 'Compra en cualquier sitio, entrega desde cualquier sitio', audience: 'Sus responsables de operaciones de tienda y e-commerce', what: 'Un inventario unificado entre digital, tienda y almacén habilita Click & Collect (BOPIS) y la sala de ventas infinita sin parches manuales complejos.', outcome: 'Cumple cada pedido desde la ubicación más eficiente y garantiza que ningún cliente quede atascado por una rotura de stock localizada.', kpis: [{ label: 'Ciclos de fulfillment de pedidos más rápidos', kind: 'efficiency' }, { label: 'Reducción significativa de las ventas perdidas por out-of-stock (OOS)', kind: 'outcome' }] },
            { title: 'Un cliente, un perfil, una experiencia', audience: 'Su VP de E-Commerce', what: 'La plataforma derriba los muros entre el historial de navegación online, las compras en tienda física y los programas de fidelización para crear un perfil de cliente único y unificado.', outcome: 'Sustituye las vitrinas genéricas por un motor de IA que muestra recomendaciones de producto hiperpersonalizadas en el momento exacto de la intención de compra.', kpis: [{ label: '100 % de visibilidad unificada cross-canal', kind: 'efficiency' }, { label: 'Mayores tasas de clic en las recomendaciones automatizadas', kind: 'outcome' }] },
            { title: 'Carros más grandes, más conversiones', audience: 'Su Chief Retail / Digital Officer', what: 'Customer journeys sin fricción y personalizados — tanto si el cliente termina la compra online como si habla con un vendedor en tienda — influyen directamente en la decisión de compra y recuperan ventas perdidas.', outcome: 'Hace up-sell y cross-sell a cada comprador, maximizando el rendimiento de cada transacción.', kpis: [{ label: '+10–15 % en el valor medio del pedido (AOV)', kind: 'outcome' }, { label: '+5–10 % en la tasa de conversión global', kind: 'outcome' }] },
            { title: 'Un motor omnicanal unificado', audience: 'Su Chief Retail Officer y Consejo', what: 'El negocio pasa de una colección fragmentada de canales de venta a un motor omnicanal unificado, de alto margen, que cultiva una fidelidad de marca profunda.', outcome: 'Entrega la experiencia retail moderna y resiliente que los consumidores esperan — y aumenta el valor de vida de cada cliente conquistado.', kpis: [{ label: 'Más del 180 % de ROI en 3 años', kind: 'outcome' }, { label: 'Expansión medible del Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Fuente del ROI superior al 180 %, las mejoras en la tasa de conversión y el impacto financiero de la visibilidad unificada de inventario reduciendo ventas perdidas.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Fuente de las mejoras de productividad de hasta el 70 % para los equipos de marketing y merchandising que usan Copilot para generar contenido de producto y enriquecer catálogos.' },
        ],
    },
    it: {
        headline: 'Unifica le tue vetrine. Vinci il customer journey.',
        summary: 'Dynamics 365 Commerce unifica le tue vetrine digitali e fisiche. Copilot automatizza il merchandising di prodotto, l\'AI guida raccomandazioni iper-personalizzate e un unico modello di inventario collega operazioni online e in negozio — così il tuo AOV cresce, i tassi di conversione salgono e il time-to-market si riduce.',
        kpis: [
            { value: '180 %+', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '+10–15 %', label: 'Valore medio dell\'ordine (AOV)', kind: 'outcome' },
            { value: '+5–10 %', label: 'Tasso di conversione complessivo', kind: 'outcome' },
            { value: '−50–70 %', label: 'Tempo dedicato all\'arricchimento delle schede prodotto', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Customer Lifetime Value', kind: 'outcome' },
        ],
        bqPre: 'Far crescere il fatturato omnicanale e massimizzare la Customer Lifetime Value è il tuo mandato centrale, ma oggi sistemi in silo tra negozio online e fisico generano stockout localizzati, mentre il merchandising manuale rallenta il tuo time-to-market.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Se i tuoi canali rimangono disconnessi e i tuoi team impantanati nell\'inserimento manuale dei dati, ',
        bqHighlight: 'come farai a far crescere il valore medio dell\'ordine e a impedire ai clienti di abbandonare il carrello in favore di competitor più fluidi?',
        figcaption: 'Domanda strategica che inquadra il business case di Dynamics 365 Commerce.',
        bridge: 'Ecco come risponde Dynamics 365 Commerce',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dal merchandiser che pubblica un nuovo prodotto fino alla strategia retail a livello di consiglio di amministrazione.',
        rungs: [
            { title: 'Nuovi prodotti online in ore, non settimane', audience: 'I tuoi merchandiser e addetti vendita', what: 'Copilot genera istantaneamente descrizioni prodotto ricche e ottimizzate SEO per il sito, mentre il POS unificato dà agli addetti vendita visibilità immediata sull\'inventario cross-canale.', outcome: 'Riduci drasticamente lo sforzo manuale per lanciare nuovi prodotti online e metti gli addetti in negozio in condizione di rispondere con sicurezza a qualunque domanda del cliente.', kpis: [{ label: '50–70 % di tempo in meno dedicato all\'arricchimento / copywriting delle schede prodotto', kind: 'efficiency' }, { label: 'Tempi di attesa del cliente in negozio più brevi', kind: 'efficiency' }] },
            { title: 'Compra ovunque, evadi da ovunque', audience: 'I tuoi store ops e e-commerce manager', what: 'Un inventario unificato tra digitale, negozio e magazzino abilita Click & Collect (BOPIS) e infinite aisle senza workaround manuali complessi.', outcome: 'Evadi gli ordini dal punto più efficiente e garantisci che nessun cliente si trovi in un vicolo cieco a causa di uno stockout localizzato.', kpis: [{ label: 'Cicli di evasione ordine più rapidi', kind: 'efficiency' }, { label: 'Significativa riduzione delle vendite perse per out-of-stock (OOS)', kind: 'outcome' }] },
            { title: 'Un cliente, un profilo, un\'esperienza', audience: 'Il tuo VP E-Commerce', what: 'La piattaforma abbatte i muri tra cronologia di navigazione online, acquisti in negozio fisico e programmi loyalty per creare un unico profilo cliente unificato.', outcome: 'Sostituisci le vetrine generiche con un motore AI che propone raccomandazioni prodotto iper-personalizzate nel momento esatto dell\'intenzione d\'acquisto.', kpis: [{ label: '100 % di visibilità unificata cross-canale', kind: 'efficiency' }, { label: 'Click-through rate più alti sulle raccomandazioni automatiche', kind: 'outcome' }] },
            { title: 'Carrelli più grandi, più conversioni', audience: 'Il tuo Chief Retail / Digital Officer', what: 'Customer journey personalizzati e senza attriti — sia che il cliente concluda l\'acquisto online sia che parli con un addetto in negozio — influenzano direttamente il comportamento d\'acquisto e recuperano le vendite perse.', outcome: 'Fai up-selling e cross-selling su ogni acquirente, massimizzando il ricavo di ogni transazione.', kpis: [{ label: '+10–15 % sul valore medio dell\'ordine (AOV)', kind: 'outcome' }, { label: '+5–10 % sul tasso di conversione complessivo', kind: 'outcome' }] },
            { title: 'Un motore omnicanale unificato', audience: 'Il tuo Chief Retail Officer e Consiglio di Amministrazione', what: 'Il business passa da una collezione frammentata di canali di vendita a un motore omnicanale unificato e ad alto margine che alimenta una profonda fedeltà al marchio.', outcome: 'Offri l\'esperienza retail moderna e resiliente che i consumatori si aspettano — e fai crescere il lifetime value di ogni cliente conquistato.', kpis: [{ label: 'Oltre 180 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Espansione misurabile del Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Fonte del ROI superiore al 180 %, dei miglioramenti del tasso di conversione e dell\'impatto finanziario della visibilità di inventario unificata sulla riduzione delle vendite perse.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Fonte dei guadagni di produttività fino al 70 % per i team di marketing e merchandising che usano Copilot per generare contenuti prodotto e arricchire i cataloghi.' },
        ],
    },
    ar: {
        headline: 'وحِّد متاجرك. اربح رحلة العميل.',
        summary: 'يُوحّد Dynamics 365 Commerce متاجرك الرقمية والمادية. يُؤتمت Copilot عرض المنتجات، ويقود الذكاء الاصطناعي توصيات شديدة التخصيص، فيما يربط نموذج مخزون موحَّد بين العمليات على الإنترنت وفي المتجر — لينمو متوسط قيمة الطلب لديك، ترتفع معدلات التحويل، ويتقلّص زمن الوصول إلى السوق.',
        kpis: [
            { value: '180٪+', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: '+10–15٪', label: 'متوسط قيمة الطلب (AOV)', kind: 'outcome' },
            { value: '+5–10٪', label: 'معدل التحويل الإجمالي', kind: 'outcome' },
            { value: '−50–70٪', label: 'الزمن المُنفَق على إثراء المنتج / كتابة المحتوى', kind: 'efficiency' },
            { value: '↑ CLV', label: 'القيمة الدائمة للعميل', kind: 'outcome' },
        ],
        bqPre: 'دفع نمو الإيرادات متعددة القنوات وتعظيم القيمة الدائمة للعميل هو مهمتك الجوهرية، لكن أنظمة منعزلة بين متاجرك الإلكترونية والمادية تُسبّب اليوم نقصاً موضعياً في المخزون، فيما يُبطئ العمل اليدوي على عرض المنتجات زمن وصولك إلى السوق.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'إذا ظلّت قنواتك منفصلة وفِرَقُك غارقة في الإدخال اليدوي للبيانات، ',
        bqHighlight: 'فكيف ستزيد متوسط قيمة الطلب وتمنع العملاء من التخلّي عن سلّاتهم لصالح منافسين أكثر سلاسة؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Dynamics 365 Commerce.',
        bridge: 'إليك كيف يجيب Dynamics 365 Commerce عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من المسؤول عن العرض الذي يُطلق منتجاً جديداً وصولاً إلى استراتيجية التجزئة على مستوى مجلس الإدارة.',
        rungs: [
            { title: 'منتجات جديدة على الإنترنت في ساعات لا أسابيع', audience: 'المسؤولون عن العرض وموظفو المتجر لديك', what: 'يُولّد Copilot فوراً أوصافاً غنية ومُحسَّنة لمحركات البحث للموقع، فيما يمنح نظام نقاط البيع الموحَّد موظفي المتجر رؤية فورية للمخزون عبر كل القنوات.', outcome: 'تُقلّص بشكل جذري الجهد اليدوي لإطلاق منتجات جديدة على الإنترنت، وتُمكّن طاقم المتجر من الإجابة بثقة عن أي سؤال للعميل.', kpis: [{ label: 'انخفاض 50–70٪ في الزمن المُنفَق على إثراء المنتج / كتابة المحتوى', kind: 'efficiency' }, { label: 'تقصير زمن انتظار العميل داخل المتجر', kind: 'efficiency' }] },
            { title: 'اشترِ من أي مكان، نفّذ من أي مكان', audience: 'مسؤولو عمليات المتجر والتجارة الإلكترونية لديك', what: 'مخزون موحَّد بين الإنترنت والمتجر والمستودع يُتيح "اشتر إلكترونياً واستلم من المتجر" (BOPIS) ومفهوم الرفّ اللامتناهي بسلاسة — دون حلول التفافية يدوية معقّدة.', outcome: 'تُنفّذ الطلبات من الموقع الأكثر كفاءة وتضمن ألّا يصطدم العميل بطريق مسدود بسبب نقص موضعي في المخزون.', kpis: [{ label: 'دورات تنفيذ طلبات أسرع', kind: 'efficiency' }, { label: 'انخفاض ملموس في المبيعات المفقودة بسبب نفاد المخزون (OOS)', kind: 'outcome' }] },
            { title: 'عميل واحد، ملف واحد، تجربة واحدة', audience: 'نائب رئيس التجارة الإلكترونية لديك', what: 'تُسقط المنصة الجدران بين سجل التصفح على الإنترنت والمشتريات في المتجر المادي وبرامج الولاء، لتُنشئ ملف عميل وحيداً وموحَّداً.', outcome: 'تُستبدل واجهات المتاجر النمطية بمحرّك ذكاء اصطناعي يُقدّم توصيات منتجات شديدة التخصيص في لحظة نية الشراء بالضبط.', kpis: [{ label: 'رؤية موحَّدة بنسبة 100٪ عبر القنوات', kind: 'efficiency' }, { label: 'معدلات نقر أعلى على التوصيات المُؤتمَتة', kind: 'outcome' }] },
            { title: 'سلال أكبر، تحويلات أكثر', audience: 'الرئيس التنفيذي للتجزئة / الرقمي لديك', what: 'رحلات شخصية وخالية من الاحتكاك — سواء أتمّ العميل عملية الشراء على الإنترنت أم تحدّث إلى موظف داخل المتجر — تُؤثّر مباشرة في سلوك الشراء وتستعيد المبيعات المفقودة.', outcome: 'تقوم بالبيع الإضافي والتقاطعي لكل مشترٍ، فتُعظّم العائد من كل صفقة.', kpis: [{ label: 'زيادة 10–15٪ في متوسط قيمة الطلب (AOV)', kind: 'outcome' }, { label: 'زيادة 5–10٪ في معدل التحويل الإجمالي', kind: 'outcome' }] },
            { title: 'محرّك متعدد القنوات موحَّد', audience: 'الرئيس التنفيذي للتجزئة ومجلس الإدارة لديك', what: 'يتحوّل العمل من مجموعة مجزّأة من قنوات البيع إلى محرّك متعدد القنوات موحَّد وذي هامش مرتفع يُنمّي ولاءً عميقاً للعلامة.', outcome: 'تُقدّم تجربة التجزئة الحديثة والمرنة التي يتوقّعها المستهلكون — وتُنمّي القيمة الدائمة لكل عميل تكسبه.', kpis: [{ label: 'عائد على الاستثمار يفوق 180٪ خلال 3 سنوات', kind: 'outcome' }, { label: 'توسّع قابل للقياس في القيمة الدائمة للعميل (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'مصدر العائد على الاستثمار البالغ أكثر من 180٪، وتحسينات معدل التحويل، والأثر المالي للرؤية الموحَّدة للمخزون في تقليص المبيعات المفقودة.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'مصدر مكاسب الإنتاجية التي تصل إلى 70٪ لفِرَق التسويق وعرض المنتجات التي تستخدم Copilot لتوليد محتوى المنتج وإثراء الكتالوجات.' },
        ],
    },
    nl: {
        headline: 'Verenig uw storefronts. Win de customer journey.',
        summary: 'Dynamics 365 Commerce verenigt uw digitale en fysieke storefronts. Copilot automatiseert productmerchandising, AI levert hyper-gepersonaliseerde aanbevelingen en één voorraadmodel verbindt online en winkeloperaties — zodat uw AOV groeit, uw conversieratio\'s stijgen en uw time-to-market krimpt.',
        kpis: [
            { value: '180%+', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '+10–15%', label: 'Gemiddelde orderwaarde (AOV)', kind: 'outcome' },
            { value: '+5–10%', label: 'Algehele conversieratio', kind: 'outcome' },
            { value: '−50–70%', label: 'Tijd besteed aan productverrijking / copy', kind: 'efficiency' },
            { value: '↑ CLV', label: 'Customer Lifetime Value', kind: 'outcome' },
        ],
        bqPre: 'Het stuwen van omnichannel-omzetgroei en het maximaliseren van Customer Lifetime Value is uw kernopdracht, maar vandaag zorgen losse systemen tussen uw online- en fysieke winkels voor lokale stockouts, terwijl handmatige merchandising uw time-to-market vertraagt.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Als uw kanalen losgekoppeld blijven en uw teams blijven vastzitten in handmatige data-entry, ',
        bqHighlight: 'hoe gaat u dan uw gemiddelde orderwaarde verhogen en voorkomen dat klanten hun winkelmandje verlaten voor soepelere concurrenten?',
        figcaption: 'Strategische vraag die de businesscase voor Dynamics 365 Commerce kadert.',
        bridge: 'Zo beantwoordt Dynamics 365 Commerce die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de merchandiser die een nieuw product publiceert tot aan de retailstrategie op bestuursniveau.',
        rungs: [
            { title: 'Nieuwe producten in uren live, niet weken', audience: 'Uw merchandisers en winkelmedewerkers', what: 'Copilot genereert direct rijke, SEO-geoptimaliseerde productbeschrijvingen voor de website, terwijl de geünificeerde POS winkelmedewerkers directe cross-channel-voorraadinzicht geeft.', outcome: 'U verlaagt drastisch de handmatige inspanning om nieuwe producten online te lanceren en stelt winkelpersoneel in staat om elke klantvraag met vertrouwen te beantwoorden.', kpis: [{ label: '50–70% minder tijd besteed aan productverrijking / copywriting', kind: 'efficiency' }, { label: 'Kortere wachttijden voor klanten in de winkel', kind: 'efficiency' }] },
            { title: 'Koop overal, lever vanaf overal', audience: 'Uw store ops- en e-commercemanagers', what: 'Een geünificeerde voorraad over digitaal, winkel en magazijn maakt naadloze Click & Collect (BOPIS) en infinite-aisle-mogelijkheden mogelijk — zonder complexe handmatige workarounds.', outcome: 'U levert orders vanaf de meest efficiënte locatie en zorgt dat klanten nooit muurvast komen te zitten door een lokale stockout.', kpis: [{ label: 'Snellere order-fulfillment-doorlooptijden', kind: 'efficiency' }, { label: 'Significante reductie van verloren omzet door out-of-stock (OOS)', kind: 'outcome' }] },
            { title: 'Eén klant, één profiel, één ervaring', audience: 'Uw VP E-Commerce', what: 'Het platform breekt de muren af tussen online browsegedrag, aankopen in de fysieke winkel en loyaltyprogramma\'s om één geünificeerd klantprofiel te creëren.', outcome: 'U vervangt generieke storefronts door een AI-engine die hyper-gepersonaliseerde productaanbevelingen toont op het exacte moment van koopintentie.', kpis: [{ label: '100% geünificeerd cross-channel-inzicht', kind: 'efficiency' }, { label: 'Hogere click-through rates op geautomatiseerde aanbevelingen', kind: 'outcome' }] },
            { title: 'Grotere mandjes, meer conversies', audience: 'Uw Chief Retail / Digital Officer', what: 'Frictieloze, gepersonaliseerde journeys — of de klant nu online afrekent of in de winkel met een medewerker praat — beïnvloeden direct het koopgedrag en heroveren verloren omzet.', outcome: 'U up-selt en cross-selt elke shopper en maximaliseert de omzetopbrengst van elke transactie.', kpis: [{ label: '+10–15% op de gemiddelde orderwaarde (AOV)', kind: 'outcome' }, { label: '+5–10% op de algehele conversieratio', kind: 'outcome' }] },
            { title: 'Een geünificeerde omnichannel-engine', audience: 'Uw Chief Retail Officer en Raad van Bestuur', what: 'De business verschuift van een gefragmenteerde verzameling verkoopkanalen naar een geünificeerde, hoge-marge omnichannel-engine die diepe merkloyaliteit kweekt.', outcome: 'U levert de veerkrachtige, moderne retailervaring die consumenten verwachten — en laat de lifetime value van elke gewonnen klant groeien.', kpis: [{ label: 'Meer dan 180% ROI over 3 jaar', kind: 'outcome' }, { label: 'Meetbare uitbreiding van de Customer Lifetime Value (CLV)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Commerce', note: 'Bron voor de meer dan 180% ROI, conversieverbeteringen en de financiële impact van geünificeerd voorraadinzicht dat verloren omzet vermindert.' },
            { title: 'Microsoft Retail Benchmarks — Copilot for Merchandising & Catalog Enrichment', note: 'Bron voor de productiviteitsverbeteringen tot 70% voor marketing- en merchandisingteams die Copilot inzetten om productcontent te genereren en catalogi te verrijken.' },
        ],
    },
};

export default function BusinessValueCommerce({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
