import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Get out of the rear-view mirror — and run finance in real time.',
        summary: 'Dynamics 365 Finance with Copilot automates the reconciliations, consolidations, and collections work that traps your finance team in spreadsheets. The result is a faster close, sharper forecasts, accelerated cash flow, and a finance organization that can actually steer the business — backed by independently validated industry benchmarks.',
        kpis: [
            { value: '122%', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '<12 mo', label: 'Payback period', kind: 'outcome' },
            { value: '−40–50%', label: 'Month-end close time', kind: 'efficiency' },
            { value: '−10–15%', label: 'Days Sales Outstanding (DSO)', kind: 'outcome' },
            { value: '+15–20%', label: 'Finance team productivity', kind: 'efficiency' },
        ],
        bqPre: 'Providing real-time financial agility to protect margins is your core mandate, but currently, your team spends up to ',
        bqPct: '70%',
        bqPost: ' of their time manually aggregating data — leading to a delayed month-end close and backward-looking reporting.',
        bqLeadIn: 'If your highly-paid finance professionals continue acting as manual data consolidators, ',
        bqHighlight: 'how will you deliver the real-time financial agility the board needs to navigate market volatility?',
        figcaption: 'Strategic question framing the business case for Dynamics 365 Finance.',
        bridge: 'Here is how Dynamics 365 Finance answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from individual analyst productivity all the way up to board-level financial impact.',
        rungs: [
            { title: 'Analysts who analyze, not aggregate', audience: 'Your financial analysts & accountants', what: 'Copilot automates routine variance analysis, drafts collections communications, and auto-matches invoices and receipts — eliminating hundreds of hours of manual spreadsheet reconciliation.', outcome: 'Your finance team moves away from tedious data entry and refocuses on high-value analysis.', kpis: [{ label: '15–20% reduction in manual data processing time', kind: 'efficiency' }, { label: 'Hundreds of hours saved annually per FTE', kind: 'efficiency' }] },
            { title: 'A month-end close in days, not weeks', audience: 'Your corporate controller', what: 'Automating the global ledger, consolidating entities in real time, and resolving variances instantly with AI eliminates the traditional reporting bottleneck.', outcome: 'You accelerate your reporting cycles and pull your financial data out of the rear-view mirror.', kpis: [{ label: '40–50% reduction in time to complete the month-end close', kind: 'efficiency' }] },
            { title: 'One real-time version of the truth', audience: 'Your VP of Finance / FP&A', what: 'A unified ERP breaks down regional and departmental silos and gives you AI-driven forecasting models in place of fragile, error-prone spreadsheets.', outcome: 'You forecast cash flow with confidence, spot risks early, and decide proactively on predictive intelligence — not historical guesses.', kpis: [{ label: '100% real-time global visibility', kind: 'efficiency' }, { label: 'Significant improvement in forecast variance accuracy', kind: 'outcome' }] },
            { title: 'Cash unlocked, margins protected', audience: 'Your CFO', what: 'AI-driven collections prioritize high-risk accounts and automate routine outreach, while real-time expense and budget controls prevent overspending before it happens.', outcome: 'You accelerate cash conversion, free up trapped working capital, and actively defend your operating margins.', kpis: [{ label: '10–15% reduction in Days Sales Outstanding (DSO)', kind: 'outcome' }, { label: 'Measurable reduction in bad-debt write-offs', kind: 'outcome' }] },
            { title: 'Finance as a strategic growth partner', audience: 'Your CFO, CEO & Board', what: 'Finance shifts from a backward-looking compliance cost center into a forward-looking partner that actively drives corporate profitability.', outcome: 'You retire the high cost of disjointed legacy ERP and give the board the real-time agility it needs.', kpis: [{ label: '122%+ ROI over 3 years', kind: 'outcome' }, { label: 'Reduction in legacy ERP Total Cost of Ownership (TCO)', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Source for the 122%+ ROI, the significant reduction in the month-end close process, and the reduction in legacy ERP costs.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot in Dynamics 365 Finance', note: 'Source for the 15–20% productivity improvements for finance professionals using Copilot for variance analysis, collections automation, and reconciliation.' },
        ],
    },
    fr: {
        headline: 'Sortez du rétroviseur — et pilotez la finance en temps réel.',
        summary: 'Dynamics 365 Finance avec Copilot automatise les rapprochements, les consolidations et les relances qui enferment votre équipe finance dans des tableurs. Résultat : une clôture plus rapide, des prévisions plus fines, un cash flow accéléré et une fonction finance qui peut réellement piloter l\'entreprise — le tout appuyé par des indicateurs sectoriels validés de manière indépendante.',
        kpis: [
            { value: '122 %', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '< 12 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '−40–50 %', label: 'Durée de clôture mensuelle', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Délai moyen de recouvrement (DSO)', kind: 'outcome' },
            { value: '+15–20 %', label: 'Productivité de l\'équipe finance', kind: 'efficiency' },
        ],
        bqPre: 'Garantir une agilité financière en temps réel pour protéger les marges est votre mission centrale, mais aujourd\'hui votre équipe passe jusqu\'à ',
        bqPct: '70 %',
        bqPost: ' de son temps à agréger manuellement des données — ce qui retarde la clôture mensuelle et produit un reporting tourné vers le passé.',
        bqLeadIn: 'Si vos professionnels de la finance, dont la rémunération est élevée, continuent d\'agir comme de simples consolidateurs manuels de données, ',
        bqHighlight: 'comment allez-vous fournir au conseil d\'administration l\'agilité financière temps réel dont il a besoin pour naviguer dans la volatilité du marché ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Dynamics 365 Finance.',
        bridge: 'Voici comment Dynamics 365 Finance y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — de la productivité individuelle de l\'analyste jusqu\'à l\'impact financier au niveau du conseil d\'administration.',
        rungs: [
            { title: 'Des analystes qui analysent, et n\'agrègent plus', audience: 'Vos analystes financiers et comptables', what: 'Copilot automatise les analyses d\'écarts de routine, rédige les relances clients et rapproche automatiquement factures et règlements — éliminant des centaines d\'heures de réconciliation manuelle dans des tableurs.', outcome: 'Votre équipe finance s\'éloigne de la saisie fastidieuse pour se recentrer sur l\'analyse à forte valeur.', kpis: [{ label: '15–20 % de temps en moins consacré au traitement manuel des données', kind: 'efficiency' }, { label: 'Des centaines d\'heures économisées par an et par ETP', kind: 'efficiency' }] },
            { title: 'Une clôture mensuelle en jours, pas en semaines', audience: 'Votre contrôleur financier', what: 'Automatiser le grand livre global, consolider les entités en temps réel et résoudre les écarts instantanément avec l\'IA élimine le goulet d\'étranglement traditionnel du reporting.', outcome: 'Vous accélérez vos cycles de reporting et sortez vos données financières du rétroviseur.', kpis: [{ label: '40–50 % de temps en moins pour réaliser la clôture mensuelle', kind: 'efficiency' }] },
            { title: 'Une seule version de la vérité, en temps réel', audience: 'Votre VP Finance / FP&A', what: 'Un ERP unifié fait tomber les silos régionaux et fonctionnels et vous fournit des modèles de prévision pilotés par l\'IA en lieu et place de tableurs fragiles et sources d\'erreurs.', outcome: 'Vous prévoyez la trésorerie avec confiance, détectez les risques tôt et décidez de manière proactive sur la base d\'une intelligence prédictive — pas de suppositions historiques.', kpis: [{ label: '100 % de visibilité globale en temps réel', kind: 'efficiency' }, { label: 'Amélioration significative de la précision des écarts de prévision', kind: 'outcome' }] },
            { title: 'De la trésorerie débloquée, des marges protégées', audience: 'Votre directeur financier (CFO)', what: 'Le recouvrement piloté par l\'IA priorise les comptes à risque et automatise les relances de routine, tandis que les contrôles de dépenses et de budgets en temps réel empêchent les dépassements avant qu\'ils ne surviennent.', outcome: 'Vous accélérez la conversion de trésorerie, libérez le besoin en fonds de roulement piégé et défendez activement vos marges opérationnelles.', kpis: [{ label: '10–15 % de réduction du délai moyen de recouvrement (DSO)', kind: 'outcome' }, { label: 'Réduction mesurable des passages en pertes sur créances douteuses', kind: 'outcome' }] },
            { title: 'La finance comme partenaire stratégique de la croissance', audience: 'Votre CFO, PDG et conseil d\'administration', what: 'La finance cesse d\'être un centre de coût de conformité tourné vers le passé pour devenir un partenaire prospectif qui contribue activement à la rentabilité de l\'entreprise.', outcome: 'Vous mettez fin au coût élevé d\'un ERP existant éclaté et donnez au conseil d\'administration l\'agilité temps réel dont il a besoin.', kpis: [{ label: 'ROI de plus de 122 % sur 3 ans', kind: 'outcome' }, { label: 'Réduction du coût total de possession (TCO) de l\'ERP existant', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Source pour le ROI de plus de 122 %, la réduction significative du processus de clôture mensuelle et la baisse des coûts de l\'ERP existant.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot dans Dynamics 365 Finance', note: 'Source pour les gains de productivité de 15 à 20 % des professionnels de la finance utilisant Copilot pour l\'analyse d\'écarts, l\'automatisation des relances et la réconciliation.' },
        ],
    },
    de: {
        headline: 'Raus aus dem Rückspiegel — steuern Sie Finance in Echtzeit.',
        summary: 'Dynamics 365 Finance mit Copilot automatisiert die Abstimmungen, Konsolidierungen und Mahnaktivitäten, die Ihr Finance-Team in Tabellen festhalten. Das Ergebnis: ein schnellerer Abschluss, präzisere Forecasts, beschleunigter Cashflow und eine Finanzorganisation, die das Geschäft tatsächlich steuern kann — gestützt auf unabhängig validierte Branchen-Benchmarks.',
        kpis: [
            { value: '122 %', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '< 12 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '−40–50 %', label: 'Dauer des Monatsabschlusses', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Days Sales Outstanding (DSO)', kind: 'outcome' },
            { value: '+15–20 %', label: 'Produktivität des Finance-Teams', kind: 'efficiency' },
        ],
        bqPre: 'Echtzeit-Finanzagilität zum Schutz der Margen bereitzustellen ist Ihr Kernauftrag — doch heute verbringt Ihr Team bis zu ',
        bqPct: '70 %',
        bqPost: ' seiner Zeit damit, Daten manuell zu aggregieren, was zu einem verzögerten Monatsabschluss und einem rückwärtsgewandten Reporting führt.',
        bqLeadIn: 'Wenn Ihre hochbezahlten Finance-Profis weiterhin als manuelle Datenkonsolidatoren agieren — ',
        bqHighlight: 'wie wollen Sie dem Vorstand dann die Echtzeit-Finanzagilität liefern, die er braucht, um Marktvolatilität zu navigieren?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Dynamics 365 Finance.',
        bridge: 'So beantwortet Dynamics 365 Finance diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — von der Produktivität einzelner Analyst:innen bis hin zur finanziellen Wirkung auf Vorstandsebene.',
        rungs: [
            { title: 'Analyst:innen, die analysieren statt aggregieren', audience: 'Ihre Financial Analysts und Buchhalter:innen', what: 'Copilot automatisiert Routine-Abweichungsanalysen, entwirft Mahnschreiben und gleicht Rechnungen und Zahlungseingänge automatisch ab — Hunderte Stunden manueller Tabellenkalkulationsabstimmung entfallen.', outcome: 'Ihr Finance-Team bewegt sich weg von mühsamer Dateneingabe und konzentriert sich wieder auf hochwertige Analyse.', kpis: [{ label: '15–20 % weniger Zeit für die manuelle Datenverarbeitung', kind: 'efficiency' }, { label: 'Hunderte Stunden pro Jahr und FTE eingespart', kind: 'efficiency' }] },
            { title: 'Monatsabschluss in Tagen, nicht Wochen', audience: 'Ihr Corporate Controller', what: 'Die Automatisierung des globalen Hauptbuchs, die Konsolidierung von Einheiten in Echtzeit und die sofortige Auflösung von Abweichungen mit KI eliminieren den klassischen Reporting-Engpass.', outcome: 'Sie beschleunigen Ihre Reporting-Zyklen und holen Ihre Finanzdaten aus dem Rückspiegel heraus.', kpis: [{ label: '40–50 % weniger Zeit für den Monatsabschluss', kind: 'efficiency' }] },
            { title: 'Eine Echtzeit-Version der Wahrheit', audience: 'Ihr VP Finance / FP&A', what: 'Ein vereinheitlichtes ERP räumt regionale und funktionale Silos aus dem Weg und stellt Ihnen KI-gestützte Forecast-Modelle anstelle fragiler, fehleranfälliger Tabellen zur Verfügung.', outcome: 'Sie prognostizieren Cashflow mit Vertrauen, erkennen Risiken früh und entscheiden proaktiv auf Basis prädiktiver Intelligenz — nicht historischer Schätzungen.', kpis: [{ label: '100 % globale Echtzeit-Sichtbarkeit', kind: 'efficiency' }, { label: 'Deutlich verbesserte Genauigkeit der Forecast-Abweichungen', kind: 'outcome' }] },
            { title: 'Liquidität freigesetzt, Margen geschützt', audience: 'Ihr CFO', what: 'KI-gestützte Forderungsverfolgung priorisiert risikoreiche Konten und automatisiert Routine-Kontaktaufnahmen, während Echtzeit-Ausgaben- und Budgetkontrollen Mehrausgaben verhindern, bevor sie entstehen.', outcome: 'Sie beschleunigen die Cash Conversion, setzen gebundenes Working Capital frei und verteidigen Ihre operativen Margen aktiv.', kpis: [{ label: '10–15 % Reduktion der Days Sales Outstanding (DSO)', kind: 'outcome' }, { label: 'Messbare Reduktion von Forderungsausfällen', kind: 'outcome' }] },
            { title: 'Finance als strategischer Wachstumspartner', audience: 'Ihr CFO, CEO und Vorstand', what: 'Finance wandelt sich vom rückwärtsgewandten Compliance-Cost-Center zum vorausschauenden Partner, der die Profitabilität des Unternehmens aktiv vorantreibt.', outcome: 'Sie reduzieren die hohen Kosten zersplitterter Legacy-ERP-Systeme und geben dem Vorstand die Echtzeit-Agilität, die er braucht.', kpis: [{ label: 'Über 122 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Senkung der Total Cost of Ownership (TCO) von Legacy-ERP', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Quelle für die mehr als 122 % ROI, die deutliche Reduktion des Monatsabschluss-Prozesses und die Senkung der Legacy-ERP-Kosten.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot in Dynamics 365 Finance', note: 'Quelle für die Produktivitätsgewinne von 15–20 % bei Finance-Profis, die Copilot für Abweichungsanalyse, Mahnautomation und Abstimmung nutzen.' },
        ],
    },
    es: {
        headline: 'Salga del retrovisor — y dirija las finanzas en tiempo real.',
        summary: 'Dynamics 365 Finance con Copilot automatiza las conciliaciones, consolidaciones y gestión de cobros que mantienen a su equipo financiero atrapado en hojas de cálculo. El resultado: un cierre más rápido, previsiones más precisas, un flujo de caja acelerado y una organización financiera que realmente puede dirigir el negocio — respaldado por indicadores sectoriales validados de forma independiente.',
        kpis: [
            { value: '122 %', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '< 12 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '−40–50 %', label: 'Tiempo de cierre mensual', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Período medio de cobro (DSO)', kind: 'outcome' },
            { value: '+15–20 %', label: 'Productividad del equipo financiero', kind: 'efficiency' },
        ],
        bqPre: 'Proporcionar agilidad financiera en tiempo real para proteger los márgenes es su mandato central, pero hoy su equipo dedica hasta el ',
        bqPct: '70 %',
        bqPost: ' de su tiempo a agregar datos manualmente — lo que retrasa el cierre mensual y produce un reporting orientado al pasado.',
        bqLeadIn: 'Si sus profesionales financieros, altamente remunerados, siguen actuando como simples consolidadores manuales de datos, ',
        bqHighlight: '¿cómo va a entregar al consejo la agilidad financiera en tiempo real que necesita para navegar la volatilidad del mercado?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Dynamics 365 Finance.',
        bridge: 'Así responde Dynamics 365 Finance',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde la productividad individual del analista hasta el impacto financiero a nivel de consejo.',
        rungs: [
            { title: 'Analistas que analizan, no agregan', audience: 'Sus analistas financieros y contables', what: 'Copilot automatiza los análisis de desviación rutinarios, redacta las comunicaciones de cobro y concilia automáticamente facturas y pagos — eliminando cientos de horas de conciliación manual en hojas de cálculo.', outcome: 'Su equipo financiero deja la entrada manual de datos y se reorienta hacia el análisis de alto valor.', kpis: [{ label: '15–20 % menos tiempo dedicado al procesamiento manual de datos', kind: 'efficiency' }, { label: 'Cientos de horas ahorradas al año por ETC', kind: 'efficiency' }] },
            { title: 'Un cierre mensual en días, no en semanas', audience: 'Su controller financiero', what: 'Automatizar el libro mayor global, consolidar entidades en tiempo real y resolver desviaciones al instante con IA elimina el cuello de botella tradicional del reporting.', outcome: 'Acelera sus ciclos de reporting y saca sus datos financieros del retrovisor.', kpis: [{ label: '40–50 % menos tiempo para completar el cierre mensual', kind: 'efficiency' }] },
            { title: 'Una única versión de la verdad en tiempo real', audience: 'Su VP de Finanzas / FP&A', what: 'Un ERP unificado derriba los silos regionales y departamentales y le ofrece modelos de previsión impulsados por IA en lugar de hojas de cálculo frágiles y propensas a errores.', outcome: 'Prevé el flujo de caja con confianza, detecta riesgos a tiempo y decide de forma proactiva sobre inteligencia predictiva — no sobre suposiciones históricas.', kpis: [{ label: '100 % de visibilidad global en tiempo real', kind: 'efficiency' }, { label: 'Mejora significativa en la precisión de la desviación de previsiones', kind: 'outcome' }] },
            { title: 'Caja liberada, márgenes protegidos', audience: 'Su director financiero (CFO)', what: 'La gestión de cobros impulsada por IA prioriza las cuentas de mayor riesgo y automatiza el contacto rutinario, mientras que los controles de gasto y presupuesto en tiempo real impiden los excesos antes de que se produzcan.', outcome: 'Acelera la conversión de caja, libera el capital circulante atrapado y defiende activamente sus márgenes operativos.', kpis: [{ label: '10–15 % de reducción del período medio de cobro (DSO)', kind: 'outcome' }, { label: 'Reducción medible de las pérdidas por insolvencias', kind: 'outcome' }] },
            { title: 'Finanzas como socio estratégico del crecimiento', audience: 'Su CFO, CEO y Consejo de Administración', what: 'Finanzas pasa de ser un centro de coste de cumplimiento orientado al pasado a un socio prospectivo que impulsa activamente la rentabilidad corporativa.', outcome: 'Retira el alto coste de un ERP heredado y fragmentado, y aporta al consejo la agilidad en tiempo real que necesita.', kpis: [{ label: 'Más de 122 % de ROI en 3 años', kind: 'outcome' }, { label: 'Reducción del coste total de propiedad (TCO) del ERP heredado', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Fuente del ROI superior al 122 %, la reducción significativa del proceso de cierre mensual y la disminución del coste del ERP heredado.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot en Dynamics 365 Finance', note: 'Fuente de las mejoras de productividad del 15–20 % para profesionales financieros que usan Copilot para análisis de desviaciones, automatización de cobros y conciliación.' },
        ],
    },
    it: {
        headline: 'Esci dallo specchietto retrovisore — e gestisci la finanza in tempo reale.',
        summary: 'Dynamics 365 Finance con Copilot automatizza le riconciliazioni, le consolidazioni e il credit collection che intrappolano il tuo team finance nei fogli di calcolo. Il risultato: una chiusura più rapida, forecast più precisi, cash flow accelerato e una funzione finance che può davvero guidare il business — il tutto supportato da benchmark di settore convalidati in modo indipendente.',
        kpis: [
            { value: '122 %', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '< 12 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '−40–50 %', label: 'Durata della chiusura mensile', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Days Sales Outstanding (DSO)', kind: 'outcome' },
            { value: '+15–20 %', label: 'Produttività del team finance', kind: 'efficiency' },
        ],
        bqPre: 'Garantire un\'agilità finanziaria in tempo reale per proteggere i margini è il tuo mandato centrale, ma oggi il tuo team passa fino al ',
        bqPct: '70 %',
        bqPost: ' del tempo ad aggregare dati manualmente — il che ritarda la chiusura mensile e produce un reporting rivolto al passato.',
        bqLeadIn: 'Se i tuoi professionisti finance, ben pagati, continuano ad agire come consolidatori manuali di dati, ',
        bqHighlight: 'come fornirai al consiglio di amministrazione l\'agilità finanziaria in tempo reale che gli serve per navigare la volatilità di mercato?',
        figcaption: 'Domanda strategica che inquadra il business case di Dynamics 365 Finance.',
        bridge: 'Ecco come risponde Dynamics 365 Finance',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dalla produttività del singolo analista fino all\'impatto finanziario a livello di consiglio di amministrazione.',
        rungs: [
            { title: 'Analisti che analizzano, non aggregano', audience: 'I tuoi analisti finanziari e contabili', what: 'Copilot automatizza le analisi di scostamento di routine, redige le comunicazioni di sollecito e abbina automaticamente fatture e incassi — eliminando centinaia di ore di riconciliazione manuale su fogli di calcolo.', outcome: 'Il tuo team finance si allontana dalla data entry tediosa e si rifocalizza sull\'analisi a valore aggiunto.', kpis: [{ label: '15–20 % di tempo in meno dedicato al data processing manuale', kind: 'efficiency' }, { label: 'Centinaia di ore risparmiate ogni anno per FTE', kind: 'efficiency' }] },
            { title: 'Una chiusura mensile in giorni, non in settimane', audience: 'Il tuo corporate controller', what: 'Automatizzare il libro mastro globale, consolidare le entità in tempo reale e risolvere gli scostamenti istantaneamente con l\'IA elimina il classico collo di bottiglia del reporting.', outcome: 'Acceleri i tuoi cicli di reporting e tiri fuori i dati finanziari dallo specchietto retrovisore.', kpis: [{ label: '40–50 % di tempo in meno per completare la chiusura mensile', kind: 'efficiency' }] },
            { title: 'Un\'unica versione della verità, in tempo reale', audience: 'Il tuo VP Finance / FP&A', what: 'Un ERP unificato abbatte i silos regionali e dipartimentali e ti fornisce modelli di forecasting guidati dall\'IA al posto di fogli di calcolo fragili e soggetti a errori.', outcome: 'Prevedi il cash flow con sicurezza, individui i rischi in anticipo e decidi in modo proattivo sulla base di intelligenza predittiva — non di supposizioni storiche.', kpis: [{ label: '100 % di visibilità globale in tempo reale', kind: 'efficiency' }, { label: 'Significativo miglioramento dell\'accuratezza degli scostamenti di forecast', kind: 'outcome' }] },
            { title: 'Cassa liberata, margini protetti', audience: 'Il tuo CFO', what: 'Il credit collection guidato dall\'IA dà priorità ai conti a rischio e automatizza i contatti di routine, mentre i controlli di spesa e budget in tempo reale impediscono gli sforamenti prima che si verifichino.', outcome: 'Acceleri la cash conversion, liberi capitale circolante intrappolato e difendi attivamente i tuoi margini operativi.', kpis: [{ label: '10–15 % di riduzione dei Days Sales Outstanding (DSO)', kind: 'outcome' }, { label: 'Riduzione misurabile delle perdite su crediti', kind: 'outcome' }] },
            { title: 'La finanza come partner strategico della crescita', audience: 'Il tuo CFO, CEO e Consiglio di Amministrazione', what: 'La finanza passa da centro di costo di compliance rivolto al passato a partner prospettico che guida attivamente la redditività aziendale.', outcome: 'Elimini i costi elevati di un ERP legacy frammentato e dai al consiglio di amministrazione l\'agilità in tempo reale di cui ha bisogno.', kpis: [{ label: 'Oltre il 122 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Riduzione del Total Cost of Ownership (TCO) dell\'ERP legacy', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Fonte del ROI superiore al 122 %, della significativa riduzione del processo di chiusura mensile e della riduzione dei costi dell\'ERP legacy.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot in Dynamics 365 Finance', note: 'Fonte dei guadagni di produttività del 15–20 % per i professionisti finance che usano Copilot per analisi di scostamento, automazione del collection e riconciliazione.' },
        ],
    },
    ar: {
        headline: 'اخرج من المرآة الخلفية — وأَدِر التمويل في الزمن الفعلي.',
        summary: 'يُؤتمت Dynamics 365 Finance مع Copilot أعمال المطابقات والتوحيد والتحصيل التي تُكبّل فريقك المالي داخل جداول البيانات. والنتيجة: إقفال أسرع، تنبؤات أدق، تدفق نقدي مُسرّع، ومنظمة مالية قادرة فعلاً على توجيه الأعمال — وكل ذلك مدعوم بمؤشرات قطاعية موثَّقة من جهات مستقلة.',
        kpis: [
            { value: '122٪', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: 'أقل من 12 شهراً', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '−40–50٪', label: 'زمن الإقفال الشهري', kind: 'efficiency' },
            { value: '−10–15٪', label: 'متوسط فترة التحصيل (DSO)', kind: 'outcome' },
            { value: '+15–20٪', label: 'إنتاجية الفريق المالي', kind: 'efficiency' },
        ],
        bqPre: 'توفير مرونة مالية آنية لحماية الهوامش هو مهمتك الجوهرية، لكن فريقك اليوم يُمضي حتى ',
        bqPct: '70٪',
        bqPost: ' من وقته في تجميع البيانات يدوياً — مما يُؤخّر الإقفال الشهري ويُنتج تقارير ناظرة إلى الماضي.',
        bqLeadIn: 'إذا واصل اختصاصيوك الماليون، ذوو الأجور المرتفعة، العمل كمُجمّعي بيانات يدويين، ',
        bqHighlight: 'فكيف ستُقدّم لمجلس الإدارة المرونة المالية الآنية التي يحتاجها للإبحار في تقلّبات السوق؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Dynamics 365 Finance.',
        bridge: 'إليك كيف يجيب Dynamics 365 Finance عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من إنتاجية المحلل الفردي وصولاً إلى الأثر المالي على مستوى مجلس الإدارة.',
        rungs: [
            { title: 'محلّلون يُحلّلون، لا يُجمّعون', audience: 'محلّلوك الماليون والمحاسبون لديك', what: 'يُؤتمت Copilot تحليلات الانحراف الروتينية، ويصوغ مراسلات التحصيل، ويُطابق تلقائياً الفواتير والمقبوضات — مُلغياً مئات الساعات من المطابقة اليدوية على جداول البيانات.', outcome: 'ينتقل فريقك المالي من إدخال البيانات المُجهِد إلى التركيز على التحليل عالي القيمة.', kpis: [{ label: 'انخفاض 15–20٪ في وقت معالجة البيانات اليدوية', kind: 'efficiency' }, { label: 'توفير مئات الساعات سنوياً لكل موظف بدوام كامل', kind: 'efficiency' }] },
            { title: 'إقفال شهري في أيام، لا أسابيع', audience: 'المراقب المالي للشركة لديك', what: 'أتمتة دفتر الأستاذ العالمي، وتوحيد الكيانات آنياً، وحلّ الانحرافات فورياً عبر الذكاء الاصطناعي يُلغي عنق الزجاجة التقليدي للتقارير.', outcome: 'تُسرِّع دورات التقارير لديك وتُخرج بياناتك المالية من المرآة الخلفية.', kpis: [{ label: 'انخفاض 40–50٪ في الوقت اللازم لإكمال الإقفال الشهري', kind: 'efficiency' }] },
            { title: 'نسخة واحدة من الحقيقة، آنية', audience: 'نائب رئيس المالية / FP&A لديك', what: 'يُحطّم نظام ERP الموحَّد الصوامع الإقليمية والإدارية، ويُوفّر لك نماذج تنبؤ مدعومة بالذكاء الاصطناعي بديلاً لجداول البيانات الهشّة المعرّضة للأخطاء.', outcome: 'تتنبأ بالتدفقات النقدية بثقة، وترصد المخاطر مبكراً، وتُقرّر بشكل استباقي بالاعتماد على ذكاء تنبؤي — لا على تخمينات تاريخية.', kpis: [{ label: 'رؤية عالمية آنية بنسبة 100٪', kind: 'efficiency' }, { label: 'تحسّن ملموس في دقة انحرافات التنبؤ', kind: 'outcome' }] },
            { title: 'سيولة مُحرَّرة، وهوامش محمية', audience: 'المدير المالي (CFO) لديك', what: 'يُولي التحصيل المدعوم بالذكاء الاصطناعي الأولوية للحسابات عالية المخاطر ويُؤتمت التواصل الروتيني، فيما تمنع ضوابط النفقات والميزانيات الآنية تجاوز الإنفاق قبل وقوعه.', outcome: 'تُسرّع تحويل النقد، وتُحرّر رأس المال العامل المُجمَّد، وتُدافع بنشاط عن هوامشك التشغيلية.', kpis: [{ label: 'انخفاض 10–15٪ في متوسط فترة التحصيل (DSO)', kind: 'outcome' }, { label: 'انخفاض قابل للقياس في شطب الديون المعدومة', kind: 'outcome' }] },
            { title: 'المالية شريك استراتيجي للنمو', audience: 'CFO ورئيس تنفيذي ومجلس إدارتك', what: 'تتحوّل المالية من مركز تكلفة امتثال يتطلّع إلى الماضي إلى شريك استشرافي يُسهم بفاعلية في ربحية الشركة.', outcome: 'تتخلّص من التكلفة العالية لأنظمة ERP القديمة المُجزّأة وتُمنح مجلس الإدارة المرونة الآنية التي يحتاجها.', kpis: [{ label: 'عائد على الاستثمار يفوق 122٪ خلال 3 سنوات', kind: 'outcome' }, { label: 'خفض إجمالي تكلفة الملكية (TCO) لأنظمة ERP القديمة', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'مصدر العائد على الاستثمار البالغ أكثر من 122٪، والانخفاض الكبير في عملية الإقفال الشهري، وتقليص تكاليف أنظمة ERP القديمة.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot in Dynamics 365 Finance', note: 'مصدر ارتفاع الإنتاجية بنسبة 15–20٪ للاختصاصيين الماليين الذين يستخدمون Copilot لتحليل الانحرافات وأتمتة التحصيل والمطابقة.' },
        ],
    },
    nl: {
        headline: 'Stap uit de achteruitkijkspiegel — en stuur finance in realtime aan.',
        summary: 'Dynamics 365 Finance met Copilot automatiseert de reconciliaties, consolidaties en collections die uw finance-team gevangen houden in spreadsheets. Het resultaat: een snellere afsluiting, scherpere forecasts, een versnelde cashflow en een finance-organisatie die de business daadwerkelijk kan aansturen — onderbouwd met onafhankelijk gevalideerde sectorbenchmarks.',
        kpis: [
            { value: '122%', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '< 12 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '−40–50%', label: 'Doorlooptijd maandafsluiting', kind: 'efficiency' },
            { value: '−10–15%', label: 'Days Sales Outstanding (DSO)', kind: 'outcome' },
            { value: '+15–20%', label: 'Productiviteit finance-team', kind: 'efficiency' },
        ],
        bqPre: 'Realtime financiële wendbaarheid leveren om marges te beschermen is uw kernopdracht, maar vandaag besteedt uw team tot ',
        bqPct: '70%',
        bqPost: ' van zijn tijd aan het handmatig samenvoegen van data — wat leidt tot een vertraagde maandafsluiting en achteruitkijkende rapportage.',
        bqLeadIn: 'Als uw goedbetaalde finance-professionals zich blijven gedragen als handmatige dataconsolidators, ',
        bqHighlight: 'hoe gaat u dan de Raad van Bestuur de realtime financiële wendbaarheid leveren die nodig is om door marktvolatiliteit te navigeren?',
        figcaption: 'Strategische vraag die de businesscase voor Dynamics 365 Finance kadert.',
        bridge: 'Zo beantwoordt Dynamics 365 Finance die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de productiviteit van de individuele analist tot aan de financiële impact op bestuursniveau.',
        rungs: [
            { title: 'Analisten die analyseren, niet aggregeren', audience: 'Uw financieel analisten en accountants', what: 'Copilot automatiseert routinematige variantie-analyses, stelt collections-communicatie op en matcht facturen en betalingen automatisch — honderden uren handmatige spreadsheet-reconciliatie verdwijnen.', outcome: 'Uw finance-team stapt af van moeizame data-invoer en focust opnieuw op hoogwaardige analyse.', kpis: [{ label: '15–20% minder tijd aan handmatige dataverwerking', kind: 'efficiency' }, { label: 'Honderden uren per jaar bespaard per FTE', kind: 'efficiency' }] },
            { title: 'Een maandafsluiting in dagen, niet weken', audience: 'Uw corporate controller', what: 'Het automatiseren van het globale grootboek, het in realtime consolideren van entiteiten en het direct oplossen van varianties met AI heft de traditionele rapportage-bottleneck op.', outcome: 'U versnelt uw rapportagecycli en haalt uw financiële data uit de achteruitkijkspiegel.', kpis: [{ label: '40–50% minder tijd om de maandafsluiting te voltooien', kind: 'efficiency' }] },
            { title: 'Eén realtime versie van de waarheid', audience: 'Uw VP Finance / FP&A', what: 'Een unified ERP slecht regionale en functionele silo\'s en biedt u AI-gestuurde forecast-modellen in plaats van fragiele, foutgevoelige spreadsheets.', outcome: 'U voorspelt cashflow met vertrouwen, signaleert risico\'s vroeg en beslist proactief op basis van predictieve intelligentie — niet op historische gissingen.', kpis: [{ label: '100% realtime wereldwijde zichtbaarheid', kind: 'efficiency' }, { label: 'Significante verbetering in nauwkeurigheid van forecast-varianties', kind: 'outcome' }] },
            { title: 'Cash vrijgemaakt, marges beschermd', audience: 'Uw CFO', what: 'AI-gestuurde collections geven prioriteit aan risicovolle accounts en automatiseren routinematige outreach, terwijl realtime uitgaven- en budgetcontroles overschrijdingen voorkomen voordat ze ontstaan.', outcome: 'U versnelt cashconversie, maakt vastzittend werkkapitaal vrij en verdedigt actief uw operationele marges.', kpis: [{ label: '10–15% reductie van Days Sales Outstanding (DSO)', kind: 'outcome' }, { label: 'Meetbare reductie van afschrijvingen op oninbare vorderingen', kind: 'outcome' }] },
            { title: 'Finance als strategische groeipartner', audience: 'Uw CFO, CEO en Raad van Bestuur', what: 'Finance verandert van een terugkijkend compliance-kostencentrum in een vooruitkijkende partner die de winstgevendheid van het bedrijf actief aanjaagt.', outcome: 'U schaft de hoge kosten van versnipperde legacy-ERP af en geeft de Raad van Bestuur de realtime wendbaarheid die nodig is.', kpis: [{ label: 'Meer dan 122% ROI over 3 jaar', kind: 'outcome' }, { label: 'Verlaging van de Total Cost of Ownership (TCO) van legacy-ERP', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Finance', note: 'Bron voor de meer dan 122% ROI, de significante reductie van het maandafsluitingsproces en de verlaging van de legacy-ERP-kosten.' },
            { title: 'Microsoft AI in Finance Benchmarks — Copilot in Dynamics 365 Finance', note: 'Bron voor de productiviteitsverbeteringen van 15–20% voor finance-professionals die Copilot gebruiken voor variantie-analyse, automatisering van collections en reconciliatie.' },
        ],
    },
};

export default function BusinessValueFinance({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
