import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Sell more, with the team you already have.',
        summary: 'Dynamics 365 Sales with Copilot helps your sellers spend more of their week with customers and less of it inside the CRM. The result is a measurably faster pipeline, more reliable forecasts, and a stronger win rate — backed by independently validated industry benchmarks.',
        kpis: [
            { value: '215%', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '<6 mo', label: 'Payback period', kind: 'outcome' },
            { value: '+15%', label: 'Higher win rates', kind: 'outcome' },
            { value: '−12%', label: 'Shorter sales cycle', kind: 'efficiency' },
            { value: '6 hrs', label: 'Reclaimed per rep / week', kind: 'efficiency' },
        ],
        bqPre: 'Scaling top-line revenue requires maximizing the yield of your existing team, but currently, sellers spend up to ',
        bqPct: '66%',
        bqPost: ' of their day on manual CRM updates and non-selling tasks, degrading pipeline velocity.',
        bqLeadIn: 'If your most expensive assets keep losing more than half their week to administrative work, ',
        bqHighlight: 'how will you achieve your growth targets without proportionally inflating your headcount and Customer Acquisition Cost?',
        figcaption: 'Strategic question framing the business case for Dynamics 365 Sales.',
        bridge: 'Here is how Dynamics 365 Sales answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from individual seller productivity all the way up to board-level financial impact.',
        rungs: [
            { title: 'More time selling, less time on admin', audience: 'Your Account Executives', what: "Copilot drafts your reps' emails, summarizes meetings, and auto-captures CRM activity.", outcome: 'Your sellers get hours back every week to focus on customers instead of paperwork.', kpis: [{ label: '15% less time spent on admin tasks', kind: 'efficiency' }, { label: '~6 hours saved per rep, per week', kind: 'efficiency' }] },
            { title: 'Faster, better-prioritized pipeline', audience: 'Your Sales Managers', what: 'AI-driven lead and opportunity scoring surfaces the deals most likely to close, while automated workflows keep momentum moving.', outcome: 'You move opportunities through the pipeline noticeably faster.', kpis: [{ label: '12% shorter average sales cycle', kind: 'efficiency' }, { label: '30% faster lead qualification', kind: 'efficiency' }] },
            { title: 'Trustworthy data, confident forecasts', audience: 'Your Sales Operations', what: 'Because activity is captured automatically, CRM hygiene approaches 100% — without nagging your reps.', outcome: 'You spot stalled deals early and forecast the quarter with confidence instead of guesswork.', kpis: [{ label: '50% less time preparing pipeline & forecast reviews', kind: 'efficiency' }] },
            { title: 'More revenue from the team you already have', audience: 'Your VP Sales / CRO', what: 'Recovered selling time, faster cycles, and AI-guided targeting compound into higher conversion.', outcome: 'You increase the revenue yield of every seller without growing headcount.', kpis: [{ label: '15% relative increase in win rates', kind: 'outcome' }, { label: '10% increase in average deal size', kind: 'outcome' }] },
            { title: 'Predictable, profitable growth', audience: 'Your CEO & Board', what: 'Revenue scales faster than operational expense, turning your sales engine into a durable growth lever.', outcome: 'You hit your top-line targets while keeping your cost-to-serve in check.', kpis: [{ label: '215% ROI over 3 years', kind: 'outcome' }, { label: 'Payback in less than 6 months', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Source for the 215% ROI, <6-month payback, 15% admin-time reduction, 12% faster sales cycles, and 15% higher win rates. The TEI summary is hosted on the official Dynamics 365 Sales product page.' },
            { title: 'Microsoft Work Trend Index — Research on AI and the way we work', note: 'Source for the industry baseline that sellers spend up to 66% of their time on administrative/non-selling activities, with AI recovering ~90 minutes per week on CRM updates alone.' },
        ],
    },
    fr: {
        headline: 'Vendez plus, avec l\'équipe que vous avez déjà.',
        summary: 'Dynamics 365 Sales avec Copilot aide vos commerciaux à passer plus de temps avec les clients et moins de temps dans le CRM. Résultat : un pipeline mesurablement plus rapide, des prévisions plus fiables et un taux de réussite supérieur — appuyés par des indicateurs sectoriels validés de manière indépendante.',
        kpis: [
            { value: '215 %', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '< 6 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '+15 %', label: 'Taux de réussite supérieur', kind: 'outcome' },
            { value: '−12 %', label: 'Cycle de vente raccourci', kind: 'efficiency' },
            { value: '6 h', label: 'Récupérées par commercial et par semaine', kind: 'efficiency' },
        ],
        bqPre: 'Faire croître le chiffre d\'affaires suppose de maximiser le rendement de votre équipe existante, or les commerciaux consacrent aujourd\'hui jusqu\'à ',
        bqPct: '66 %',
        bqPost: ' de leur journée à des mises à jour manuelles du CRM et à des tâches non commerciales, ce qui ralentit le pipeline.',
        bqLeadIn: 'Si vos ressources les plus coûteuses continuent de perdre plus de la moitié de leur semaine en tâches administratives, ',
        bqHighlight: 'comment atteindrez-vous vos objectifs de croissance sans gonfler proportionnellement vos effectifs et votre coût d\'acquisition client ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Dynamics 365 Sales.',
        bridge: 'Voici comment Dynamics 365 Sales y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — de la productivité individuelle du commercial jusqu\'à l\'impact financier au niveau du conseil d\'administration.',
        rungs: [
            { title: 'Plus de temps pour vendre, moins de temps administratif', audience: 'Vos commerciaux (Account Executives)', what: 'Copilot rédige les e-mails de vos commerciaux, résume les réunions et capture automatiquement l\'activité dans le CRM.', outcome: 'Vos vendeurs récupèrent des heures chaque semaine pour se concentrer sur les clients plutôt que sur la paperasse.', kpis: [{ label: '15 % de temps en moins sur les tâches administratives', kind: 'efficiency' }, { label: '≈ 6 heures économisées par commercial et par semaine', kind: 'efficiency' }] },
            { title: 'Un pipeline plus rapide et mieux priorisé', audience: 'Vos sales managers', what: 'Le scoring de leads et d\'opportunités piloté par IA fait remonter les affaires les plus susceptibles de se conclure, pendant que des workflows automatisés maintiennent la dynamique.', outcome: 'Vous faites avancer les opportunités dans le pipeline nettement plus vite.', kpis: [{ label: '12 % de cycle de vente moyen en moins', kind: 'efficiency' }, { label: 'Qualification des leads 30 % plus rapide', kind: 'efficiency' }] },
            { title: 'Des données fiables, des prévisions confiantes', audience: 'Votre équipe Sales Operations', what: 'L\'activité étant capturée automatiquement, l\'hygiène du CRM atteint près de 100 % — sans avoir à relancer vos commerciaux.', outcome: 'Vous repérez tôt les affaires bloquées et prévoyez le trimestre avec confiance plutôt qu\'au jugé.', kpis: [{ label: '50 % de temps en moins pour préparer les revues de pipeline et de prévisions', kind: 'efficiency' }] },
            { title: 'Plus de revenus avec l\'équipe que vous avez déjà', audience: 'Votre VP Ventes / CRO', what: 'Le temps de vente récupéré, les cycles plus courts et le ciblage assisté par IA se cumulent en une meilleure conversion.', outcome: 'Vous augmentez le rendement commercial de chaque vendeur sans accroître les effectifs.', kpis: [{ label: '15 % d\'augmentation relative du taux de réussite', kind: 'outcome' }, { label: '10 % d\'augmentation du panier moyen', kind: 'outcome' }] },
            { title: 'Une croissance prévisible et rentable', audience: 'Votre PDG et votre conseil d\'administration', what: 'Le chiffre d\'affaires croît plus vite que les charges opérationnelles, transformant votre moteur commercial en levier de croissance durable.', outcome: 'Vous atteignez vos objectifs de chiffre d\'affaires tout en maîtrisant le coût de service.', kpis: [{ label: '215 % de ROI sur 3 ans', kind: 'outcome' }, { label: 'Rentabilité en moins de 6 mois', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Source pour le ROI de 215 %, le retour sur investissement en moins de 6 mois, la réduction de 15 % du temps administratif, l\'accélération de 12 % des cycles de vente et la hausse de 15 % du taux de réussite. Le résumé TEI est hébergé sur la page produit officielle de Dynamics 365 Sales.' },
            { title: 'Microsoft Work Trend Index — Recherche sur l\'IA et notre façon de travailler', note: 'Source pour la référence sectorielle indiquant que les commerciaux passent jusqu\'à 66 % de leur temps sur des tâches administratives ou non commerciales, l\'IA permettant de récupérer environ 90 minutes par semaine rien que sur les mises à jour du CRM.' },
        ],
    },
    de: {
        headline: 'Verkaufen Sie mehr — mit dem Team, das Sie bereits haben.',
        summary: 'Dynamics 365 Sales mit Copilot hilft Ihren Vertriebsmitarbeitenden, mehr Zeit pro Woche bei Kund:innen statt im CRM zu verbringen. Das Ergebnis: ein messbar schnellerer Pipeline-Durchlauf, verlässlichere Forecasts und höhere Gewinnraten — gestützt auf unabhängig validierte Branchen-Benchmarks.',
        kpis: [
            { value: '215 %', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '< 6 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '+15 %', label: 'Höhere Gewinnraten', kind: 'outcome' },
            { value: '−12 %', label: 'Kürzerer Vertriebszyklus', kind: 'efficiency' },
            { value: '6 Std.', label: 'Pro Vertriebler:in & Woche zurückgewonnen', kind: 'efficiency' },
        ],
        bqPre: 'Um den Umsatz auszubauen, muss die Leistung Ihres bestehenden Teams maximiert werden — doch Vertriebsmitarbeitende verbringen heute bis zu ',
        bqPct: '66 %',
        bqPost: ' ihres Tages mit manuellen CRM-Aktualisierungen und vertriebsfremden Aufgaben, was die Pipeline-Geschwindigkeit ausbremst.',
        bqLeadIn: 'Wenn Ihre teuersten Ressourcen weiterhin mehr als die Hälfte ihrer Woche an administrative Arbeit verlieren — ',
        bqHighlight: 'wie wollen Sie Ihre Wachstumsziele erreichen, ohne Ihre Personalstärke und Kundenakquisitionskosten proportional zu erhöhen?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Dynamics 365 Sales.',
        bridge: 'So beantwortet Dynamics 365 Sales diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — von der Produktivität einzelner Vertriebler:innen bis hin zur finanziellen Wirkung auf Vorstandsebene.',
        rungs: [
            { title: 'Mehr Zeit für den Verkauf, weniger Verwaltungsaufwand', audience: 'Ihre Account Executives', what: 'Copilot entwirft die E-Mails Ihrer Vertriebler:innen, fasst Meetings zusammen und erfasst CRM-Aktivitäten automatisch.', outcome: 'Ihre Vertriebler:innen gewinnen jede Woche Stunden zurück, um sich auf Kund:innen statt auf Papierkram zu konzentrieren.', kpis: [{ label: '15 % weniger Zeit für Verwaltungsaufgaben', kind: 'efficiency' }, { label: 'ca. 6 Stunden pro Vertriebler:in und Woche eingespart', kind: 'efficiency' }] },
            { title: 'Schnellere und besser priorisierte Pipeline', audience: 'Ihre Vertriebsleitung', what: 'KI-gestütztes Lead- und Opportunity-Scoring bringt die Deals mit der höchsten Abschlusswahrscheinlichkeit nach vorn, während automatisierte Workflows den Schwung aufrechterhalten.', outcome: 'Sie bewegen Opportunities spürbar schneller durch die Pipeline.', kpis: [{ label: '12 % kürzerer durchschnittlicher Vertriebszyklus', kind: 'efficiency' }, { label: '30 % schnellere Lead-Qualifizierung', kind: 'efficiency' }] },
            { title: 'Verlässliche Daten, fundierte Forecasts', audience: 'Ihr Sales-Operations-Team', what: 'Da Aktivitäten automatisch erfasst werden, erreicht die CRM-Datenqualität nahezu 100 % — ganz ohne Nachhaken bei Ihren Vertriebler:innen.', outcome: 'Sie erkennen ins Stocken geratene Deals früh und prognostizieren das Quartal mit Sicherheit statt mit Bauchgefühl.', kpis: [{ label: '50 % weniger Zeit für die Vorbereitung von Pipeline- und Forecast-Reviews', kind: 'efficiency' }] },
            { title: 'Mehr Umsatz mit dem Team, das Sie bereits haben', audience: 'Ihr Vertriebsvorstand / CRO', what: 'Zurückgewonnene Verkaufszeit, kürzere Zyklen und KI-gestütztes Targeting verstärken sich gegenseitig zu einer höheren Conversion.', outcome: 'Sie steigern den Umsatzbeitrag jedes Vertriebskopfes, ohne den Personalstand auszuweiten.', kpis: [{ label: '15 % relative Steigerung der Gewinnrate', kind: 'outcome' }, { label: '10 % höherer durchschnittlicher Auftragswert', kind: 'outcome' }] },
            { title: 'Planbares, profitables Wachstum', audience: 'Ihr CEO und Ihr Vorstand', what: 'Der Umsatz wächst schneller als die operativen Kosten und macht Ihren Vertrieb zum dauerhaften Wachstumstreiber.', outcome: 'Sie erreichen Ihre Umsatzziele und halten gleichzeitig Ihre Vertriebskosten im Griff.', kpis: [{ label: '215 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Amortisation in weniger als 6 Monaten', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Quelle für 215 % ROI, Amortisation in unter 6 Monaten, 15 % weniger Verwaltungszeit, 12 % schnellere Vertriebszyklen und 15 % höhere Gewinnraten. Die TEI-Zusammenfassung ist auf der offiziellen Produktseite zu Dynamics 365 Sales verfügbar.' },
            { title: 'Microsoft Work Trend Index — Forschung zu KI und unserer Arbeitsweise', note: 'Quelle für den Branchen-Benchmark, dass Vertriebler:innen bis zu 66 % ihrer Zeit für administrative bzw. vertriebsfremde Tätigkeiten aufwenden und KI allein bei CRM-Aktualisierungen rund 90 Minuten pro Woche zurückgibt.' },
        ],
    },
    es: {
        headline: 'Venda más con el equipo que ya tiene.',
        summary: 'Dynamics 365 Sales con Copilot ayuda a sus vendedores a dedicar más tiempo a los clientes y menos al CRM. El resultado es un pipeline notablemente más rápido, previsiones más fiables y una mayor tasa de éxito — respaldado por indicadores sectoriales validados de forma independiente.',
        kpis: [
            { value: '215 %', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '< 6 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '+15 %', label: 'Mayor tasa de éxito', kind: 'outcome' },
            { value: '−12 %', label: 'Ciclo de ventas más corto', kind: 'efficiency' },
            { value: '6 h', label: 'Recuperadas por vendedor / semana', kind: 'efficiency' },
        ],
        bqPre: 'Hacer crecer los ingresos exige maximizar el rendimiento de su equipo actual, pero hoy los vendedores dedican hasta el ',
        bqPct: '66 %',
        bqPost: ' de su jornada a actualizaciones manuales del CRM y tareas que no son de venta, ralentizando el pipeline.',
        bqLeadIn: 'Si sus recursos más caros siguen perdiendo más de la mitad de la semana en trabajo administrativo, ',
        bqHighlight: '¿cómo va a alcanzar sus objetivos de crecimiento sin inflar proporcionalmente su plantilla y su coste de adquisición de clientes?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Dynamics 365 Sales.',
        bridge: 'Así responde Dynamics 365 Sales',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde la productividad individual del vendedor hasta el impacto financiero a nivel de consejo.',
        rungs: [
            { title: 'Más tiempo vendiendo, menos en tareas administrativas', audience: 'Sus ejecutivos de cuenta', what: 'Copilot redacta los correos de sus comerciales, resume las reuniones y captura automáticamente la actividad en el CRM.', outcome: 'Sus vendedores recuperan horas cada semana para centrarse en los clientes en lugar del papeleo.', kpis: [{ label: '15 % menos tiempo en tareas administrativas', kind: 'efficiency' }, { label: '≈ 6 horas ahorradas por vendedor y semana', kind: 'efficiency' }] },
            { title: 'Pipeline más rápido y mejor priorizado', audience: 'Sus directores de ventas', what: 'La puntuación de leads y oportunidades con IA destaca los acuerdos con mayor probabilidad de cierre, mientras los flujos automatizados mantienen el impulso.', outcome: 'Hace avanzar las oportunidades por el pipeline notablemente más rápido.', kpis: [{ label: '12 % de reducción del ciclo medio de ventas', kind: 'efficiency' }, { label: '30 % más rapidez en la cualificación de leads', kind: 'efficiency' }] },
            { title: 'Datos fiables, previsiones con confianza', audience: 'Su equipo de Sales Operations', what: 'Como la actividad se captura automáticamente, la calidad del CRM se acerca al 100 % — sin tener que insistir a sus comerciales.', outcome: 'Detecta pronto los acuerdos estancados y prevé el trimestre con confianza, no a ojo.', kpis: [{ label: '50 % menos tiempo preparando revisiones de pipeline y previsión', kind: 'efficiency' }] },
            { title: 'Más ingresos con el equipo que ya tiene', audience: 'Su VP de Ventas / CRO', what: 'El tiempo de venta recuperado, los ciclos más cortos y la segmentación asistida por IA se combinan en una mayor conversión.', outcome: 'Aumenta el rendimiento de ingresos por vendedor sin ampliar la plantilla.', kpis: [{ label: '15 % de aumento relativo de la tasa de éxito', kind: 'outcome' }, { label: '10 % de aumento del importe medio por operación', kind: 'outcome' }] },
            { title: 'Crecimiento previsible y rentable', audience: 'Su CEO y Consejo de Administración', what: 'Los ingresos crecen más rápido que los gastos operativos, convirtiendo su motor comercial en una palanca de crecimiento sostenible.', outcome: 'Cumple sus objetivos de ingresos manteniendo el coste de servicio bajo control.', kpis: [{ label: '215 % de ROI en 3 años', kind: 'outcome' }, { label: 'Amortización en menos de 6 meses', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Fuente del 215 % de ROI, la amortización en menos de 6 meses, la reducción del 15 % del tiempo administrativo, el 12 % de aceleración del ciclo de ventas y el 15 % de aumento de la tasa de éxito. El resumen TEI está alojado en la página oficial del producto Dynamics 365 Sales.' },
            { title: 'Microsoft Work Trend Index — Investigación sobre la IA y nuestra forma de trabajar', note: 'Fuente del dato sectorial de que los vendedores dedican hasta el 66 % de su tiempo a actividades administrativas/no comerciales, recuperando con IA unos 90 minutos por semana solo en actualizaciones del CRM.' },
        ],
    },
    it: {
        headline: 'Vendi di più, con il team che hai già.',
        summary: 'Dynamics 365 Sales con Copilot aiuta i tuoi venditori a passare più tempo con i clienti e meno tempo dentro il CRM. Il risultato è una pipeline misurabilmente più rapida, previsioni più affidabili e un win rate più alto — supportati da benchmark di settore convalidati in modo indipendente.',
        kpis: [
            { value: '215 %', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '< 6 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '+15 %', label: 'Win rate più alto', kind: 'outcome' },
            { value: '−12 %', label: 'Ciclo di vendita più breve', kind: 'efficiency' },
            { value: '6 ore', label: 'Recuperate per venditore / settimana', kind: 'efficiency' },
        ],
        bqPre: 'Far crescere i ricavi richiede di massimizzare la resa del team che hai già, ma oggi i venditori spendono fino al ',
        bqPct: '66 %',
        bqPost: ' della loro giornata in aggiornamenti manuali del CRM e attività non commerciali, rallentando la pipeline.',
        bqLeadIn: 'Se le tue risorse più costose continuano a perdere più di metà settimana in lavoro amministrativo, ',
        bqHighlight: 'come raggiungerai i tuoi obiettivi di crescita senza gonfiare in proporzione organico e Customer Acquisition Cost?',
        figcaption: 'Domanda strategica che inquadra il business case di Dynamics 365 Sales.',
        bridge: 'Ecco come risponde Dynamics 365 Sales',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dalla produttività del singolo venditore fino all\'impatto finanziario a livello di consiglio di amministrazione.',
        rungs: [
            { title: 'Più tempo per vendere, meno per il lavoro amministrativo', audience: 'I tuoi Account Executive', what: 'Copilot redige le email dei tuoi venditori, riassume le riunioni e cattura automaticamente l\'attività nel CRM.', outcome: 'I tuoi venditori recuperano ore ogni settimana per concentrarsi sui clienti invece che sulla burocrazia.', kpis: [{ label: '15 % di tempo in meno sulle attività amministrative', kind: 'efficiency' }, { label: '≈ 6 ore risparmiate per venditore a settimana', kind: 'efficiency' }] },
            { title: 'Pipeline più veloce e meglio prioritizzata', audience: 'I tuoi responsabili vendite', what: 'Lo scoring AI di lead e opportunità mette in evidenza le trattative con maggiori probabilità di chiusura, mentre i workflow automatizzati ne mantengono lo slancio.', outcome: 'Fai avanzare le opportunità nella pipeline in modo nettamente più rapido.', kpis: [{ label: '12 % di ciclo di vendita medio in meno', kind: 'efficiency' }, { label: '30 % di qualificazione lead più rapida', kind: 'efficiency' }] },
            { title: 'Dati affidabili, previsioni con sicurezza', audience: 'Il tuo team Sales Operations', what: 'Poiché le attività vengono catturate automaticamente, la qualità dei dati CRM si avvicina al 100 % — senza dover sollecitare i tuoi venditori.', outcome: 'Individui per tempo le trattative ferme e prevedi il trimestre con sicurezza invece che a sensazione.', kpis: [{ label: '50 % di tempo in meno per preparare le review di pipeline e forecast', kind: 'efficiency' }] },
            { title: 'Più ricavi con il team che hai già', audience: 'Il tuo VP Sales / CRO', what: 'Il tempo di vendita recuperato, i cicli più brevi e il targeting guidato dall\'AI si combinano in una conversione più alta.', outcome: 'Aumenti il rendimento di ricavo per venditore senza ampliare l\'organico.', kpis: [{ label: '15 % di aumento relativo del win rate', kind: 'outcome' }, { label: '10 % di aumento del valore medio dell\'opportunità', kind: 'outcome' }] },
            { title: 'Crescita prevedibile e profittevole', audience: 'Il tuo CEO e Consiglio di Amministrazione', what: 'I ricavi crescono più velocemente delle spese operative, trasformando il tuo motore commerciale in una leva di crescita duratura.', outcome: 'Raggiungi i tuoi obiettivi di fatturato mantenendo sotto controllo il cost-to-serve.', kpis: [{ label: '215 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Rientro in meno di 6 mesi', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Fonte del 215 % di ROI, del rientro in meno di 6 mesi, del 15 % di tempo amministrativo in meno, del 12 % di accelerazione del ciclo di vendita e del 15 % di aumento del win rate. La sintesi TEI è ospitata sulla pagina ufficiale del prodotto Dynamics 365 Sales.' },
            { title: 'Microsoft Work Trend Index — Ricerca su IA e modo di lavorare', note: 'Fonte del dato di settore secondo cui i venditori spendono fino al 66 % del loro tempo in attività amministrative/non commerciali, con l\'AI che recupera circa 90 minuti a settimana solo sugli aggiornamenti CRM.' },
        ],
    },
    ar: {
        headline: 'حقّق مبيعات أكبر، بالفريق نفسه الذي لديك بالفعل.',
        summary: 'يساعد Dynamics 365 Sales مع Copilot فريق المبيعات لديك على قضاء وقت أطول مع العملاء ووقت أقل داخل نظام إدارة علاقات العملاء (CRM). والنتيجة: خط مبيعات أسرع بشكل قابل للقياس، وتنبؤات أكثر موثوقية، ومعدل نجاح أعلى — مدعومة بمؤشرات قطاعية موثّقة من جهات مستقلة.',
        kpis: [
            { value: '215٪', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: 'أقل من 6 أشهر', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '+15٪', label: 'معدل نجاح أعلى', kind: 'outcome' },
            { value: '−12٪', label: 'دورة مبيعات أقصر', kind: 'efficiency' },
            { value: '6 ساعات', label: 'مستردّة لكل مندوب / أسبوع', kind: 'efficiency' },
        ],
        bqPre: 'يتطلّب نمو الإيرادات تعظيم إنتاجية فريقك الحالي، غير أن مندوبي المبيعات يقضون اليوم ما يصل إلى ',
        bqPct: '66٪',
        bqPost: ' من يومهم في تحديثات يدوية لنظام CRM ومهام غير بيعية، مما يُبطئ سرعة خط المبيعات.',
        bqLeadIn: 'إذا ظلّت أغلى مواردك تُهدر أكثر من نصف أسبوعها في أعمال إدارية، ',
        bqHighlight: 'فكيف ستحقّق أهداف نموّك دون أن ترفع عدد موظفيك وتكلفة اكتساب العميل بالنسبة نفسها؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Dynamics 365 Sales.',
        bridge: 'إليك كيف يجيب Dynamics 365 Sales عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من إنتاجية المندوب الفردي وصولاً إلى الأثر المالي على مستوى مجلس الإدارة.',
        rungs: [
            { title: 'وقت أكبر للبيع، ووقت أقل للأعمال الإدارية', audience: 'مديرو الحسابات لديك', what: 'يصوغ Copilot رسائل البريد الإلكتروني لمندوبيك، ويُلخّص الاجتماعات، ويلتقط نشاط CRM تلقائياً.', outcome: 'يستعيد مندوبو المبيعات لديك ساعات كل أسبوع للتركيز على العملاء بدلاً من الأعمال الورقية.', kpis: [{ label: 'انخفاض 15٪ في الوقت المستغرق في المهام الإدارية', kind: 'efficiency' }, { label: 'توفير ≈ 6 ساعات لكل مندوب أسبوعياً', kind: 'efficiency' }] },
            { title: 'خط مبيعات أسرع وأفضل ترتيباً للأولويات', audience: 'مديرو المبيعات لديك', what: 'يُبرز التقييم المدفوع بالذكاء الاصطناعي للعملاء المحتملين والفرص الصفقاتِ الأرجح إغلاقاً، فيما تحافظ مسارات العمل المؤتمتة على الزخم.', outcome: 'تُحرّك الفرص عبر خط المبيعات بسرعة ملحوظة.', kpis: [{ label: 'انخفاض 12٪ في متوسط دورة المبيعات', kind: 'efficiency' }, { label: 'تأهيل العملاء المحتملين أسرع بنسبة 30٪', kind: 'efficiency' }] },
            { title: 'بيانات موثوقة وتنبؤات بثقة', audience: 'فريق عمليات المبيعات لديك', what: 'بفضل الالتقاط التلقائي للنشاط، تقترب جودة بيانات CRM من 100٪ — دون مطاردة مندوبيك.', outcome: 'تكتشف الصفقات المتوقفة مبكّراً وتتنبأ بنتائج الربع بثقة بدلاً من التخمين.', kpis: [{ label: 'انخفاض 50٪ في وقت إعداد مراجعات خط المبيعات والتنبؤات', kind: 'efficiency' }] },
            { title: 'إيرادات أعلى من الفريق نفسه الذي لديك', audience: 'نائب رئيس المبيعات / المدير الإيرادي (CRO)', what: 'يتراكم الوقت البيعي المستردّ والدورات الأقصر والاستهداف الموجَّه بالذكاء الاصطناعي ليتحوّل إلى تحويلات أعلى.', outcome: 'ترفع عائد الإيرادات لكل مندوب دون توسيع عدد الموظفين.', kpis: [{ label: 'زيادة نسبية 15٪ في معدل النجاح', kind: 'outcome' }, { label: 'زيادة 10٪ في متوسط حجم الصفقة', kind: 'outcome' }] },
            { title: 'نمو متوقَّع ومُربِح', audience: 'الرئيس التنفيذي ومجلس الإدارة لديك', what: 'تنمو الإيرادات أسرع من المصاريف التشغيلية، فيتحوّل محرّك مبيعاتك إلى رافعة نمو مستدامة.', outcome: 'تحقّق أهدافك في أعلى الميزانية مع إبقاء تكلفة الخدمة تحت السيطرة.', kpis: [{ label: '215٪ عائد على الاستثمار خلال 3 سنوات', kind: 'outcome' }, { label: 'استرداد رأس المال في أقل من 6 أشهر', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'مصدر نسبة العائد على الاستثمار 215٪، واسترداد رأس المال في أقل من 6 أشهر، وتقليل الوقت الإداري بنسبة 15٪، وتسريع دورات المبيعات بنسبة 12٪، وارتفاع معدل النجاح بنسبة 15٪. ملخّص TEI مُستضاف على صفحة منتج Dynamics 365 Sales الرسمية.' },
            { title: 'Microsoft Work Trend Index — أبحاث حول الذكاء الاصطناعي وأسلوب عملنا', note: 'مصدر المؤشر القطاعي الذي يفيد بأن مندوبي المبيعات يقضون ما يصل إلى 66٪ من وقتهم في أنشطة إدارية أو غير بيعية، مع استرداد الذكاء الاصطناعي حوالي 90 دقيقة أسبوعياً من تحديثات CRM وحدها.' },
        ],
    },
    nl: {
        headline: 'Verkoop meer met het team dat u al heeft.',
        summary: 'Dynamics 365 Sales met Copilot helpt uw verkopers meer tijd door te brengen bij klanten en minder in het CRM. Het resultaat: een meetbaar snellere pipeline, betrouwbaardere forecasts en een hogere winratio — onderbouwd met onafhankelijk gevalideerde sectorbenchmarks.',
        kpis: [
            { value: '215%', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '< 6 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '+15%', label: 'Hogere winratio', kind: 'outcome' },
            { value: '−12%', label: 'Kortere salescyclus', kind: 'efficiency' },
            { value: '6 uur', label: 'Per vertegenwoordiger / week teruggewonnen', kind: 'efficiency' },
        ],
        bqPre: 'Omzetgroei vereist het maximale halen uit uw bestaande team, maar verkopers besteden vandaag tot ',
        bqPct: '66%',
        bqPost: ' van hun dag aan handmatige CRM-updates en niet-verkooptaken, wat de pipeline-snelheid afremt.',
        bqLeadIn: 'Als uw duurste resources meer dan de helft van hun week blijven verliezen aan administratief werk, ',
        bqHighlight: 'hoe gaat u dan uw groeidoelen halen zonder uw personeelsbestand en klantacquisitiekosten evenredig op te blazen?',
        figcaption: 'Strategische vraag die de businesscase voor Dynamics 365 Sales kadert.',
        bridge: 'Zo beantwoordt Dynamics 365 Sales die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de productiviteit van de individuele verkoper tot aan de financiële impact op bestuursniveau.',
        rungs: [
            { title: 'Meer tijd om te verkopen, minder administratie', audience: 'Uw accountmanagers', what: 'Copilot stelt e-mails op voor uw verkopers, vat vergaderingen samen en legt CRM-activiteit automatisch vast.', outcome: 'Uw verkopers krijgen elke week uren terug om zich op klanten te richten in plaats van op papierwerk.', kpis: [{ label: '15% minder tijd aan administratieve taken', kind: 'efficiency' }, { label: '≈ 6 uur bespaard per verkoper per week', kind: 'efficiency' }] },
            { title: 'Snellere, beter geprioriteerde pipeline', audience: 'Uw salesmanagers', what: 'AI-gestuurde lead- en opportunity-scoring zet de deals met de hoogste sluitingskans bovenaan, terwijl geautomatiseerde workflows de vaart erin houden.', outcome: 'U beweegt opportunities merkbaar sneller door de pipeline.', kpis: [{ label: '12% kortere gemiddelde salescyclus', kind: 'efficiency' }, { label: '30% snellere leadkwalificatie', kind: 'efficiency' }] },
            { title: 'Betrouwbare data, vertrouwde forecasts', audience: 'Uw Sales Operations-team', what: 'Doordat activiteit automatisch wordt vastgelegd, nadert de CRM-datakwaliteit 100% — zonder uw verkopers achter de broek te zitten.', outcome: 'U signaleert vastgelopen deals vroeg en voorspelt het kwartaal met vertrouwen in plaats van op gevoel.', kpis: [{ label: '50% minder tijd voor het voorbereiden van pipeline- en forecastreviews', kind: 'efficiency' }] },
            { title: 'Meer omzet uit het team dat u al heeft', audience: 'Uw VP Sales / CRO', what: 'Teruggewonnen verkooptijd, kortere cycli en AI-gestuurde targeting versterken elkaar tot een hogere conversie.', outcome: 'U verhoogt de omzetbijdrage per verkoper zonder het personeelsbestand uit te breiden.', kpis: [{ label: '15% relatieve stijging van de winratio', kind: 'outcome' }, { label: '10% hogere gemiddelde dealwaarde', kind: 'outcome' }] },
            { title: 'Voorspelbare, winstgevende groei', audience: 'Uw CEO en Raad van Bestuur', what: 'Omzet groeit sneller dan operationele kosten, waardoor uw verkoopmotor een duurzame groeihefboom wordt.', outcome: 'U haalt uw omzetdoelen en houdt tegelijk uw cost-to-serve onder controle.', kpis: [{ label: '215% ROI over 3 jaar', kind: 'outcome' }, { label: 'Terugverdiend in minder dan 6 maanden', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Sales', note: 'Bron voor de 215% ROI, terugverdientijd van minder dan 6 maanden, 15% minder administratieve tijd, 12% snellere salescycli en 15% hogere winratio. De TEI-samenvatting staat op de officiële productpagina van Dynamics 365 Sales.' },
            { title: 'Microsoft Work Trend Index — Onderzoek naar AI en hoe we werken', note: 'Bron voor het sectorgemiddelde dat verkopers tot 66% van hun tijd aan administratieve/niet-verkoopactiviteiten besteden, waarbij AI alleen al ≈ 90 minuten per week aan CRM-updates terugwint.' },
        ],
    },
};

export default function BusinessValueSales({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
