import React from 'react';
import { Building2, EyeOff, KeyRound, Lock, Server, ShieldCheck, Trophy, Users as UsersIcon, UserRound } from 'lucide-react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'One identity, threat, and data-protection plane for every Power Platform and Dynamics 365 workload.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel, and Microsoft Purview bring identity, threat protection, and data governance under one roof — so the apps your makers ship and the Dynamics 365 environments your business runs on are secured by the same controls, the same policies, and the same auditable evidence as the rest of your Microsoft estate.',
        kpis: [
            { value: '240%', label: 'ROI over 3 years (Entra ID)', kind: 'outcome' },
            { value: '<6 mo', label: 'Payback period', kind: 'outcome' },
            { value: '−50%', label: 'Identity-related breach risk', kind: 'outcome' },
            { value: '−75%', label: 'Help-desk identity tickets', kind: 'efficiency' },
            { value: '1', label: 'Unified control plane', kind: 'outcome' },
        ],
        bqPre: 'Citizen development, AI agents, and SaaS sprawl are multiplying the number of places your corporate data lives — and every new identity, app, and integration widens the surface an attacker can reach.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'If every new app, agent, and connector quietly expands your attack surface, ',
        bqHighlight: 'how will you let the business move fast on Power Platform and Dynamics 365 — without giving up control of identity, data, and audit evidence?',
        figcaption: 'Strategic question framing the business case for the Enterprise Security layer.',
        bridge: 'Here is how the Microsoft security stack answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from frictionless sign-in for end users all the way up to a board-defensible cyber-risk posture.',
        rungs: [
            { title: 'One sign-in, everywhere your people work', audience: 'Your Employees & Partners', what: 'Microsoft Entra ID delivers single sign-on and self-service password reset across Power Platform, Dynamics 365, Microsoft 365, and thousands of SaaS apps — with phishing-resistant MFA on top.', outcome: 'Your users stop juggling passwords and recover from lockouts on their own, while your help desk stops absorbing the cost.', kpis: [{ label: '~75% fewer identity-related help-desk tickets', kind: 'efficiency' }, { label: 'Single sign-on across Microsoft and 1,000+ SaaS apps', kind: 'efficiency' }] },
            { title: 'Right access, right person, right context', audience: 'Your IT & Identity Admins', what: 'Conditional Access, role-based access control, and Privileged Identity Management let you grant least-privilege access based on user, device, location, and risk signal — and revoke it just as quickly.', outcome: 'You enforce Zero Trust without slowing your business down, and you stop over-provisioning standing admin rights.', kpis: [{ label: 'Conditional Access policies enforced on every sign-in', kind: 'outcome' }, { label: 'Just-in-time, time-bound elevation for privileged roles', kind: 'efficiency' }] },
            { title: 'See threats early, contain them fast', audience: 'Your SecOps Team', what: 'Microsoft Defender XDR and Sentinel correlate signals from identities, endpoints, email, cloud apps, and your Power Platform / Dynamics 365 estate into a single, AI-assisted investigation experience.', outcome: 'Your analysts catch lateral movement and data exfiltration earlier — and resolve incidents in a fraction of the time.', kpis: [{ label: '88% less likely to experience a material breach (Forrester TEI)', kind: 'outcome' }, { label: 'Faster mean time to detect and respond across the kill chain', kind: 'efficiency' }] },
            { title: 'Data stays where it should — and only there', audience: 'Your CISO & Compliance Officers', what: 'DLP policies across environments, customer-managed keys, Customer Lockbox, tenant isolation, geo-residency, audit logging, and Microsoft Purview labels apply uniformly to every Power App, flow, and Dynamics 365 environment.', outcome: 'You give the business the freedom to build, while keeping regulated and sensitive data inside the boundaries your auditors expect.', kpis: [{ label: 'Centralized DLP and labelling for the entire Power Platform / D365 estate', kind: 'outcome' }, { label: 'Reduced audit and compliance burden via a single control plane', kind: 'efficiency' }] },
            { title: 'A defensible security posture for the board', audience: 'Your CEO & Board', what: 'Identity, endpoint, data, and app security converge on one Microsoft platform — replacing a long tail of point products and the integration burden that comes with them.', outcome: 'You lower your cyber-risk exposure and your security TCO at the same time, with numbers you can defend at the board.', kpis: [{ label: '240% ROI over 3 years on Microsoft Entra ID', kind: 'outcome' }, { label: 'Payback in less than 6 months', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Source for the 240% ROI, <6-month payback, ~75% reduction in identity-related help-desk tickets, and reduced identity-related breach risk.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Source for the finding that customers were 88% less likely to experience a material breach, with faster mean time to detect and respond.' },
            { title: 'Microsoft Security, Compliance & Identity — product documentation (Microsoft Learn)', note: 'Source for Conditional Access, Privileged Identity Management, DLP policies across environments, Customer Lockbox, customer-managed keys, and Microsoft Purview integration.' },
        ],
    },
    fr: {
        headline: 'Un seul plan d\'identité, de protection contre les menaces et de protection des données pour chaque charge de travail Power Platform et Dynamics 365.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel et Microsoft Purview rassemblent identité, protection contre les menaces et gouvernance des données sous un même toit — pour que les applications livrées par vos makers et les environnements Dynamics 365 sur lesquels tourne votre business soient sécurisés par les mêmes contrôles, les mêmes politiques et les mêmes preuves auditables que le reste de votre patrimoine Microsoft.',
        kpis: [
            { value: '240 %', label: 'ROI sur 3 ans (Entra ID)', kind: 'outcome' },
            { value: '< 6 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '−50 %', label: 'Risque de brèche liée à l\'identité', kind: 'outcome' },
            { value: '−75 %', label: 'Tickets help-desk liés à l\'identité', kind: 'efficiency' },
            { value: '1', label: 'Plan de contrôle unifié', kind: 'outcome' },
        ],
        bqPre: 'Citizen development, agents IA et prolifération SaaS multiplient les endroits où vit la donnée de l\'entreprise — et chaque nouvelle identité, application et intégration élargit la surface qu\'un attaquant peut atteindre.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si chaque nouvelle application, agent et connecteur élargit silencieusement votre surface d\'attaque, ',
        bqHighlight: 'comment laisserez-vous le métier avancer vite sur Power Platform et Dynamics 365 — sans renoncer au contrôle de l\'identité, des données et des preuves d\'audit ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de la couche Sécurité d\'entreprise.',
        bridge: 'Voici comment la stack de sécurité Microsoft y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — d\'une connexion sans friction pour l\'utilisateur final jusqu\'à une posture de cyber-risque défendable devant le conseil d\'administration.',
        rungs: [
            { title: 'Une seule connexion, partout où vos collaborateurs travaillent', audience: 'Vos collaborateurs et partenaires', what: 'Microsoft Entra ID offre le single sign-on et la réinitialisation de mot de passe en libre-service sur Power Platform, Dynamics 365, Microsoft 365 et des milliers d\'applications SaaS — avec une MFA résistante au phishing par-dessus.', outcome: 'Vos utilisateurs cessent de jongler avec les mots de passe et débloquent eux-mêmes leurs comptes, pendant que votre help-desk cesse d\'en absorber le coût.', kpis: [{ label: '~75 % de tickets help-desk liés à l\'identité en moins', kind: 'efficiency' }, { label: 'SSO sur Microsoft et plus de 1 000 applications SaaS', kind: 'efficiency' }] },
            { title: 'Le bon accès, à la bonne personne, dans le bon contexte', audience: 'Vos administrateurs IT et identité', what: 'Conditional Access, RBAC et Privileged Identity Management permettent d\'accorder le moindre privilège selon l\'utilisateur, l\'appareil, la localisation et le signal de risque — et de le révoquer tout aussi vite.', outcome: 'Vous appliquez le Zero Trust sans ralentir le métier et cessez de sur-provisionner des droits d\'admin permanents.', kpis: [{ label: 'Politiques Conditional Access appliquées à chaque connexion', kind: 'outcome' }, { label: 'Élévation just-in-time et limitée dans le temps pour les rôles privilégiés', kind: 'efficiency' }] },
            { title: 'Détectez les menaces tôt, contenez-les vite', audience: 'Votre équipe SecOps', what: 'Microsoft Defender XDR et Sentinel corrèlent les signaux issus des identités, des endpoints, du courrier, des applications cloud et de votre patrimoine Power Platform / Dynamics 365 en une expérience d\'investigation unique, assistée par l\'IA.', outcome: 'Vos analystes repèrent plus tôt les mouvements latéraux et les exfiltrations de données — et résolvent les incidents en une fraction du temps.', kpis: [{ label: '88 % moins susceptibles de subir une brèche matérielle (Forrester TEI)', kind: 'outcome' }, { label: 'MTTD et MTTR réduits sur toute la kill chain', kind: 'efficiency' }] },
            { title: 'La donnée reste là où elle doit être — et nulle part ailleurs', audience: 'Votre CISO et vos responsables conformité', what: 'Les politiques DLP entre environnements, les customer-managed keys, Customer Lockbox, l\'isolation du tenant, la résidence géographique, les journaux d\'audit et les étiquettes Microsoft Purview s\'appliquent uniformément à chaque Power App, flow et environnement Dynamics 365.', outcome: 'Vous laissez au métier la liberté de construire, tout en gardant les données réglementées et sensibles à l\'intérieur des frontières que vos auditeurs attendent.', kpis: [{ label: 'DLP et étiquetage centralisés pour tout le patrimoine Power Platform / D365', kind: 'outcome' }, { label: 'Charge d\'audit et de conformité réduite grâce à un plan de contrôle unique', kind: 'efficiency' }] },
            { title: 'Une posture de sécurité défendable devant le conseil', audience: 'Votre CEO et conseil d\'administration', what: 'Identité, endpoint, données et sécurité applicative convergent sur une seule plateforme Microsoft — en remplacement d\'une longue traîne de produits ponctuels et de la charge d\'intégration qui va avec.', outcome: 'Vous abaissez votre exposition au cyber-risque et votre TCO sécurité en même temps, avec des chiffres défendables devant le conseil.', kpis: [{ label: '240 % de ROI sur 3 ans sur Microsoft Entra ID', kind: 'outcome' }, { label: 'Rentabilisation en moins de 6 mois', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Source du ROI de 240 %, du retour sur investissement en moins de 6 mois, de la réduction d\'environ 75 % des tickets help-desk liés à l\'identité et de la réduction du risque de brèche liée à l\'identité.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Source du constat selon lequel les clients étaient 88 % moins susceptibles de subir une brèche matérielle, avec un MTTD et un MTTR plus rapides.' },
            { title: 'Microsoft Security, Compliance & Identity — documentation produit (Microsoft Learn)', note: 'Source pour Conditional Access, Privileged Identity Management, politiques DLP entre environnements, Customer Lockbox, customer-managed keys et intégration Microsoft Purview.' },
        ],
    },
    de: {
        headline: 'Eine einzige Identitäts-, Bedrohungs- und Datenschutzschicht für jede Power-Platform- und Dynamics-365-Workload.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel und Microsoft Purview bringen Identität, Bedrohungsschutz und Daten-Governance unter ein Dach — damit die Apps, die Ihre Maker:innen ausliefern, und die Dynamics-365-Umgebungen, auf denen Ihr Geschäft läuft, durch dieselben Kontrollen, dieselben Richtlinien und dieselben auditierbaren Nachweise abgesichert werden wie der Rest Ihres Microsoft-Bestands.',
        kpis: [
            { value: '240 %', label: 'ROI über 3 Jahre (Entra ID)', kind: 'outcome' },
            { value: '< 6 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '−50 %', label: 'Risiko identitätsbezogener Sicherheitsvorfälle', kind: 'outcome' },
            { value: '−75 %', label: 'Help-Desk-Tickets rund um Identität', kind: 'efficiency' },
            { value: '1', label: 'Vereinheitlichte Steuerungsebene', kind: 'outcome' },
        ],
        bqPre: 'Citizen Development, KI-Agenten und SaaS-Wildwuchs vervielfachen die Orte, an denen Unternehmensdaten leben — und jede neue Identität, App und Integration vergrößert die Angriffsfläche, die ein Angreifer erreichen kann.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Wenn jede neue App, jeder Agent und jeder Connector Ihre Angriffsfläche stillschweigend vergrößert — ',
        bqHighlight: 'wie wollen Sie dann das Geschäft auf Power Platform und Dynamics 365 schnell vorankommen lassen, ohne die Kontrolle über Identität, Daten und Audit-Nachweise abzugeben?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case der Schicht Enterprise Security.',
        bridge: 'So beantwortet der Microsoft-Security-Stack diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — vom reibungslosen Sign-in für Endnutzer:innen bis hin zu einer vor dem Vorstand verteidigbaren Cyber-Risiko-Position.',
        rungs: [
            { title: 'Eine Anmeldung, überall wo Ihre Leute arbeiten', audience: 'Ihre Mitarbeiter:innen und Partner', what: 'Microsoft Entra ID liefert Single Sign-On und Self-Service-Passwort-Reset über Power Platform, Dynamics 365, Microsoft 365 und Tausende SaaS-Apps — mit phishing-resistenter MFA obendrauf.', outcome: 'Ihre Nutzer:innen jonglieren keine Passwörter mehr und lösen Sperren selbst auf, während Ihr Help-Desk die Kosten dafür nicht mehr trägt.', kpis: [{ label: '~75 % weniger identitätsbezogene Help-Desk-Tickets', kind: 'efficiency' }, { label: 'Single Sign-On über Microsoft und mehr als 1.000 SaaS-Apps', kind: 'efficiency' }] },
            { title: 'Der richtige Zugriff, der richtigen Person, im richtigen Kontext', audience: 'Ihre IT- und Identity-Admins', what: 'Conditional Access, rollenbasierte Zugriffskontrolle und Privileged Identity Management gewähren Least-Privilege-Zugriff anhand von Nutzer, Gerät, Standort und Risikosignal — und entziehen ihn ebenso schnell wieder.', outcome: 'Sie setzen Zero Trust durch, ohne das Geschäft zu bremsen, und beenden die Über-Provisionierung dauerhafter Admin-Rechte.', kpis: [{ label: 'Conditional-Access-Richtlinien bei jeder Anmeldung erzwungen', kind: 'outcome' }, { label: 'Just-in-Time-, zeitlich begrenzte Erhöhung für privilegierte Rollen', kind: 'efficiency' }] },
            { title: 'Bedrohungen früh erkennen, schnell eindämmen', audience: 'Ihr SecOps-Team', what: 'Microsoft Defender XDR und Sentinel korrelieren Signale aus Identitäten, Endpunkten, E-Mail, Cloud-Apps und Ihrem Power-Platform-/Dynamics-365-Bestand in einer einzigen, KI-gestützten Untersuchungserfahrung.', outcome: 'Ihre Analyst:innen erkennen Lateral Movement und Datenabfluss früher — und schließen Vorfälle in einem Bruchteil der Zeit.', kpis: [{ label: '88 % geringere Wahrscheinlichkeit eines materiellen Sicherheitsvorfalls (Forrester TEI)', kind: 'outcome' }, { label: 'Schnellere mittlere Zeit bis zur Erkennung und Reaktion über die gesamte Kill Chain', kind: 'efficiency' }] },
            { title: 'Daten bleiben, wo sie sollen — und nur dort', audience: 'Ihre CISO und Compliance Officer', what: 'DLP-Richtlinien über Umgebungen hinweg, Customer-Managed Keys, Customer Lockbox, Tenant-Isolation, Geo-Residency, Audit-Logging und Microsoft-Purview-Labels gelten einheitlich für jede Power App, jeden Flow und jede Dynamics-365-Umgebung.', outcome: 'Sie geben dem Geschäft die Freiheit zu bauen — und halten gleichzeitig regulierte und sensible Daten innerhalb der Grenzen, die Ihre Prüfer erwarten.', kpis: [{ label: 'Zentrales DLP und Labelling für den gesamten Power-Platform-/D365-Bestand', kind: 'outcome' }, { label: 'Geringere Audit- und Compliance-Last durch eine einzige Steuerungsebene', kind: 'efficiency' }] },
            { title: 'Eine vor dem Vorstand verteidigbare Sicherheitsposition', audience: 'Ihre CEO und der Vorstand', what: 'Identität, Endpoint, Daten und App-Security konvergieren auf einer Microsoft-Plattform — anstelle einer langen Reihe von Punktprodukten und der damit verbundenen Integrationslast.', outcome: 'Sie senken Ihr Cyber-Risiko und Ihren Security-TCO gleichzeitig — mit Zahlen, die Sie vor dem Vorstand verteidigen können.', kpis: [{ label: '240 % ROI über 3 Jahre auf Microsoft Entra ID', kind: 'outcome' }, { label: 'Amortisation in unter 6 Monaten', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Quelle für den ROI von 240 %, die Amortisation in unter 6 Monaten, die rund 75 % geringeren identitätsbezogenen Help-Desk-Tickets und das verringerte identitätsbezogene Vorfallsrisiko.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Quelle für den Befund, dass Kunden zu 88 % weniger wahrscheinlich einen materiellen Sicherheitsvorfall erlebten, bei schnelleren Erkennungs- und Reaktionszeiten.' },
            { title: 'Microsoft Security, Compliance & Identity — Produktdokumentation (Microsoft Learn)', note: 'Quelle für Conditional Access, Privileged Identity Management, DLP-Richtlinien über Umgebungen hinweg, Customer Lockbox, Customer-Managed Keys und die Microsoft-Purview-Integration.' },
        ],
    },
    es: {
        headline: 'Un solo plano de identidad, protección frente a amenazas y protección de datos para cada carga de trabajo de Power Platform y Dynamics 365.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel y Microsoft Purview reúnen identidad, protección frente a amenazas y gobernanza del dato bajo un mismo techo — para que las aplicaciones que entregan sus makers y los entornos de Dynamics 365 sobre los que opera su negocio queden protegidos por los mismos controles, las mismas políticas y las mismas evidencias auditables que el resto de su patrimonio Microsoft.',
        kpis: [
            { value: '240 %', label: 'ROI en 3 años (Entra ID)', kind: 'outcome' },
            { value: '< 6 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '−50 %', label: 'Riesgo de brecha relacionada con la identidad', kind: 'outcome' },
            { value: '−75 %', label: 'Tickets de help-desk relacionados con la identidad', kind: 'efficiency' },
            { value: '1', label: 'Plano de control unificado', kind: 'outcome' },
        ],
        bqPre: 'El citizen development, los agentes de IA y la proliferación de SaaS multiplican los lugares donde vive el dato corporativo — y cada nueva identidad, aplicación e integración amplía la superficie a la que un atacante puede llegar.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si cada nueva app, agente y conector amplía silenciosamente su superficie de ataque, ',
        bqHighlight: '¿cómo va a dejar al negocio avanzar rápido sobre Power Platform y Dynamics 365 — sin renunciar al control de la identidad, los datos y las evidencias de auditoría?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de la capa de Seguridad empresarial.',
        bridge: 'Así responde la stack de seguridad de Microsoft',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde un inicio de sesión sin fricciones para el usuario final hasta una postura de ciber-riesgo defendible ante el Consejo.',
        rungs: [
            { title: 'Un inicio de sesión, en cualquier lugar donde trabajen sus equipos', audience: 'Sus empleados y partners', what: 'Microsoft Entra ID ofrece single sign-on y restablecimiento de contraseña en autoservicio sobre Power Platform, Dynamics 365, Microsoft 365 y miles de apps SaaS — con MFA resistente al phishing por encima.', outcome: 'Sus usuarios dejan de hacer malabares con contraseñas y se desbloquean por sí mismos, mientras su help-desk deja de absorber el coste.', kpis: [{ label: '~75 % menos tickets de help-desk relacionados con la identidad', kind: 'efficiency' }, { label: 'SSO sobre Microsoft y más de 1.000 apps SaaS', kind: 'efficiency' }] },
            { title: 'El acceso correcto, a la persona correcta, en el contexto correcto', audience: 'Sus administradores de TI e identidad', what: 'Conditional Access, RBAC y Privileged Identity Management permiten conceder el mínimo privilegio en función del usuario, el dispositivo, la ubicación y la señal de riesgo — y revocarlo igual de rápido.', outcome: 'Aplica Zero Trust sin frenar al negocio y deja de sobre-aprovisionar derechos de administrador permanentes.', kpis: [{ label: 'Políticas de Conditional Access aplicadas en cada inicio de sesión', kind: 'outcome' }, { label: 'Elevación just-in-time y acotada en el tiempo para roles privilegiados', kind: 'efficiency' }] },
            { title: 'Detecte amenazas pronto, conténgalas rápido', audience: 'Su equipo SecOps', what: 'Microsoft Defender XDR y Sentinel correlacionan señales de identidades, endpoints, correo, apps cloud y de su patrimonio Power Platform / Dynamics 365 en una única experiencia de investigación asistida por IA.', outcome: 'Sus analistas detectan antes el movimiento lateral y la exfiltración de datos — y resuelven incidentes en una fracción del tiempo.', kpis: [{ label: '88 % menos probabilidades de sufrir una brecha material (Forrester TEI)', kind: 'outcome' }, { label: 'Menor MTTD y MTTR a lo largo de toda la kill chain', kind: 'efficiency' }] },
            { title: 'El dato se queda donde debe — y solo ahí', audience: 'Su CISO y responsables de cumplimiento', what: 'Las políticas de DLP entre entornos, las customer-managed keys, Customer Lockbox, el aislamiento del tenant, la residencia geográfica, el registro de auditoría y las etiquetas de Microsoft Purview se aplican de forma uniforme a cada Power App, flow y entorno de Dynamics 365.', outcome: 'Da al negocio libertad para construir, manteniendo los datos regulados y sensibles dentro de las fronteras que esperan sus auditores.', kpis: [{ label: 'DLP y etiquetado centralizados para todo el patrimonio Power Platform / D365', kind: 'outcome' }, { label: 'Menor carga de auditoría y cumplimiento gracias a un único plano de control', kind: 'efficiency' }] },
            { title: 'Una postura de seguridad defendible ante el Consejo', audience: 'Su CEO y Consejo', what: 'Identidad, endpoint, dato y seguridad de apps convergen en una sola plataforma Microsoft — sustituyendo una larga cola de productos puntuales y la carga de integración asociada.', outcome: 'Reduce su exposición al ciber-riesgo y su TCO de seguridad al mismo tiempo, con cifras defendibles ante el Consejo.', kpis: [{ label: '240 % de ROI en 3 años sobre Microsoft Entra ID', kind: 'outcome' }, { label: 'Amortización en menos de 6 meses', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Fuente del ROI del 240 %, la amortización en menos de 6 meses, la reducción de aproximadamente el 75 % de tickets de help-desk relacionados con la identidad y la reducción del riesgo de brecha relacionada con la identidad.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Fuente del hallazgo de que los clientes tenían un 88 % menos de probabilidades de sufrir una brecha material, con MTTD y MTTR más rápidos.' },
            { title: 'Microsoft Security, Compliance & Identity — documentación de producto (Microsoft Learn)', note: 'Fuente para Conditional Access, Privileged Identity Management, políticas de DLP entre entornos, Customer Lockbox, customer-managed keys e integración con Microsoft Purview.' },
        ],
    },
    it: {
        headline: 'Un unico piano di identità, protezione dalle minacce e protezione dei dati per ogni workload di Power Platform e Dynamics 365.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel e Microsoft Purview riuniscono identità, protezione dalle minacce e governance del dato sotto un solo tetto — così le app che i tuoi maker rilasciano e gli ambienti Dynamics 365 su cui gira il business sono protetti dagli stessi controlli, dalle stesse policy e dalle stesse evidenze auditabili del resto del tuo patrimonio Microsoft.',
        kpis: [
            { value: '240 %', label: 'ROI in 3 anni (Entra ID)', kind: 'outcome' },
            { value: '< 6 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '−50 %', label: 'Rischio di breach legato all\'identità', kind: 'outcome' },
            { value: '−75 %', label: 'Ticket help-desk legati all\'identità', kind: 'efficiency' },
            { value: '1', label: 'Piano di controllo unificato', kind: 'outcome' },
        ],
        bqPre: 'Citizen development, agenti AI e SaaS sprawl moltiplicano i posti in cui vivono i dati aziendali — e ogni nuova identità, app e integrazione amplia la superficie che un attaccante può raggiungere.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Se ogni nuova app, agente e connettore allarga silenziosamente la tua superficie d\'attacco, ',
        bqHighlight: 'come farai a lasciare correre il business su Power Platform e Dynamics 365 — senza rinunciare al controllo su identità, dati ed evidenze d\'audit?',
        figcaption: 'Domanda strategica che inquadra il business case del layer Enterprise Security.',
        bridge: 'Ecco come risponde lo stack di sicurezza Microsoft',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — da un sign-in senza attriti per l\'utente finale fino a una postura di cyber-rischio difendibile davanti al Consiglio.',
        rungs: [
            { title: 'Un unico sign-in, ovunque le tue persone lavorino', audience: 'I tuoi dipendenti e partner', what: 'Microsoft Entra ID offre single sign-on e reset password self-service su Power Platform, Dynamics 365, Microsoft 365 e migliaia di app SaaS — con MFA resistente al phishing in cima.', outcome: 'I tuoi utenti smettono di fare i giocolieri con le password e si sbloccano da soli, mentre l\'help-desk smette di assorbirne il costo.', kpis: [{ label: '~75 % in meno di ticket help-desk legati all\'identità', kind: 'efficiency' }, { label: 'SSO su Microsoft e oltre 1.000 app SaaS', kind: 'efficiency' }] },
            { title: 'Il giusto accesso, alla giusta persona, nel giusto contesto', audience: 'I tuoi amministratori IT e identità', what: 'Conditional Access, RBAC e Privileged Identity Management consentono di concedere il minimo privilegio in base a utente, dispositivo, posizione e segnale di rischio — e di revocarlo altrettanto in fretta.', outcome: 'Applichi Zero Trust senza rallentare il business e smetti di sovraprovvisionare diritti di admin permanenti.', kpis: [{ label: 'Policy Conditional Access applicate a ogni sign-in', kind: 'outcome' }, { label: 'Elevazione just-in-time e a tempo limitato per i ruoli privilegiati', kind: 'efficiency' }] },
            { title: 'Vedi le minacce prima, contienile in fretta', audience: 'Il tuo team SecOps', what: 'Microsoft Defender XDR e Sentinel correlano segnali da identità, endpoint, posta, app cloud e dal tuo patrimonio Power Platform / Dynamics 365 in un\'unica esperienza di indagine assistita dall\'AI.', outcome: 'I tuoi analisti intercettano prima i movimenti laterali e l\'esfiltrazione di dati — e risolvono gli incidenti in una frazione del tempo.', kpis: [{ label: '88 % di probabilità in meno di subire un breach materiale (Forrester TEI)', kind: 'outcome' }, { label: 'MTTD e MTTR più rapidi lungo tutta la kill chain', kind: 'efficiency' }] },
            { title: 'I dati restano dove devono — e solo lì', audience: 'Il tuo CISO e i responsabili compliance', what: 'Policy DLP tra ambienti, customer-managed key, Customer Lockbox, isolamento del tenant, geo-residency, audit logging ed etichette Microsoft Purview si applicano in modo uniforme a ogni Power App, flow e ambiente Dynamics 365.', outcome: 'Dai al business la libertà di costruire, tenendo i dati regolamentati e sensibili dentro i confini che i tuoi auditor si aspettano.', kpis: [{ label: 'DLP ed etichettatura centralizzati per tutto il patrimonio Power Platform / D365', kind: 'outcome' }, { label: 'Carico di audit e compliance ridotto grazie a un unico piano di controllo', kind: 'efficiency' }] },
            { title: 'Una postura di sicurezza difendibile davanti al Consiglio', audience: 'Il tuo CEO e Consiglio di Amministrazione', what: 'Identità, endpoint, dati e sicurezza delle app convergono su un\'unica piattaforma Microsoft — sostituendo una lunga coda di prodotti punto e il relativo carico di integrazione.', outcome: 'Abbassi insieme l\'esposizione al cyber-rischio e il TCO di sicurezza, con numeri difendibili davanti al Consiglio.', kpis: [{ label: '240 % di ROI in 3 anni su Microsoft Entra ID', kind: 'outcome' }, { label: 'Rientro in meno di 6 mesi', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Fonte del ROI del 240 %, del rientro in meno di 6 mesi, della riduzione di circa il 75 % dei ticket help-desk legati all\'identità e della riduzione del rischio di breach legato all\'identità.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Fonte del riscontro che i clienti avevano l\'88 % in meno di probabilità di subire un breach materiale, con MTTD e MTTR più rapidi.' },
            { title: 'Microsoft Security, Compliance & Identity — documentazione di prodotto (Microsoft Learn)', note: 'Fonte per Conditional Access, Privileged Identity Management, policy DLP tra ambienti, Customer Lockbox, customer-managed key e integrazione con Microsoft Purview.' },
        ],
    },
    ar: {
        headline: 'مستوى واحد للهوية وحماية التهديدات وحماية البيانات لكل أعباء عمل Power Platform وDynamics 365.',
        summary: 'تجمع Microsoft Entra ID وMicrosoft Defender وMicrosoft Sentinel وMicrosoft Purview الهوية وحماية التهديدات وحوكمة البيانات تحت سقف واحد — حتى تكون التطبيقات التي يُسلّمها صنّاعك وبيئات Dynamics 365 التي تدير أعمالك مُؤمَّنة بالضوابط نفسها والسياسات نفسها والأدلّة القابلة للتدقيق ذاتها التي يخضع لها بقية إرثك في Microsoft.',
        kpis: [
            { value: '240٪', label: 'العائد على الاستثمار خلال 3 سنوات (Entra ID)', kind: 'outcome' },
            { value: 'أقل من 6 أشهر', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '−50٪', label: 'مخاطر الاختراق المرتبطة بالهوية', kind: 'outcome' },
            { value: '−75٪', label: 'تذاكر الدعم الفنّي المرتبطة بالهوية', kind: 'efficiency' },
            { value: '1', label: 'مستوى تحكّم موحَّد', kind: 'outcome' },
        ],
        bqPre: 'الـ citizen development ووكلاء الذكاء الاصطناعي وانتشار الـ SaaS كلّها تُضاعف أماكن وجود بيانات شركتك — وكل هوية وتطبيق وتكامل جديد يُوسّع الرقعة التي يستطيع المهاجم بلوغها.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'إذا كان كل تطبيق ووكيل وموصِل جديد يُوسّع بصمت سطح هجومك، ',
        bqHighlight: 'فكيف ستترك الأعمال تتقدّم بسرعة على Power Platform وDynamics 365 — دون أن تتنازل عن السيطرة على الهوية والبيانات وأدلّة التدقيق؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لطبقة الأمن المؤسسي.',
        bridge: 'إليك كيف تُجيب منظومة أمن Microsoft عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من تسجيل دخول بلا احتكاك للمستخدم النهائي، وصولاً إلى وضع سيبراني قابل للدفاع عنه أمام مجلس الإدارة.',
        rungs: [
            { title: 'تسجيل دخول واحد، أينما يعمل أفرادك', audience: 'موظفوك وشركاؤك', what: 'تُقدّم Microsoft Entra ID تسجيل دخول موحّد وإعادة تعيين كلمة المرور بالخدمة الذاتية على Power Platform وDynamics 365 وMicrosoft 365 وآلاف تطبيقات الـ SaaS — مع MFA مقاوم للتصيّد في القمّة.', outcome: 'يكُفّ مستخدموك عن التلاعب بكلمات المرور ويستردّون حساباتهم بأنفسهم، فيما يكُفّ الدعم الفنّي عن استيعاب الكلفة.', kpis: [{ label: 'انخفاض ~75٪ في تذاكر الدعم الفنّي المرتبطة بالهوية', kind: 'efficiency' }, { label: 'تسجيل دخول موحّد على Microsoft وأكثر من 1000 تطبيق SaaS', kind: 'efficiency' }] },
            { title: 'الصلاحية الصحيحة، للشخص الصحيح، في السياق الصحيح', audience: 'مديرو تقنية المعلومات والهوية لديك', what: 'يُتيح Conditional Access والتحكّم بالوصول المبني على الأدوار وPrivileged Identity Management منح أدنى صلاحية ممكنة استناداً إلى المستخدم والجهاز والموقع وإشارة المخاطر — وسحبها بالسرعة نفسها.', outcome: 'تُطبّق Zero Trust دون إبطاء الأعمال، وتكُفّ عن الإفراط في منح صلاحيات الإدارة الدائمة.', kpis: [{ label: 'سياسات Conditional Access مُطبَّقة في كل تسجيل دخول', kind: 'outcome' }, { label: 'رفع صلاحيات في الوقت المناسب ومحدود زمنياً للأدوار المميَّزة', kind: 'efficiency' }] },
            { title: 'اكتشف التهديدات مبكراً، وحاصرها بسرعة', audience: 'فريق العمليات الأمنية لديك', what: 'يربط Microsoft Defender XDR وSentinel الإشارات من الهويات ونقاط النهاية والبريد وتطبيقات السحابة وأرضية Power Platform / Dynamics 365 لديك في تجربة تحقيق واحدة مدعومة بالذكاء الاصطناعي.', outcome: 'يُمسك محلّلوك بالحركة الجانبية وتسرّب البيانات في وقت أبكر — ويحلّون الحوادث في جزء يسير من الزمن.', kpis: [{ label: 'احتمال أقلّ بنسبة 88٪ للتعرّض لاختراق جوهري (Forrester TEI)', kind: 'outcome' }, { label: 'متوسط زمن أسرع للاكتشاف والاستجابة عبر سلسلة الهجوم', kind: 'efficiency' }] },
            { title: 'البيانات تبقى حيث ينبغي — ولا في غيره', audience: 'مدير أمن المعلومات ومسؤولو الامتثال لديك', what: 'سياسات منع تسرّب البيانات (DLP) عبر البيئات، والمفاتيح التي يديرها العميل، وCustomer Lockbox، وعزل المستأجر، وإقامة البيانات الجغرافية، وسجلّات التدقيق، وعلامات Microsoft Purview تُطبَّق بشكل موحّد على كل Power App وflow وبيئة Dynamics 365.', outcome: 'تمنح الأعمال حرّية البناء، مع إبقاء البيانات الحسّاسة والخاضعة للوائح داخل الحدود التي يتوقّعها مدقّقوك.', kpis: [{ label: 'DLP وتصنيف مركزيان لكامل أرضية Power Platform / D365', kind: 'outcome' }, { label: 'تخفيف عبء التدقيق والامتثال عبر مستوى تحكّم واحد', kind: 'efficiency' }] },
            { title: 'وضع أمني قابل للدفاع عنه أمام مجلس الإدارة', audience: 'الرئيس التنفيذي ومجلس الإدارة لديك', what: 'تتلاقى الهوية ونقاط النهاية والبيانات وأمن التطبيقات على منصّة Microsoft واحدة — في استبدال لذيل طويل من المنتجات النقطية وعبء التكامل المُصاحب.', outcome: 'تُخفّض تعرّضك للمخاطر السيبرانية وتكلفتك الإجمالية للأمان في الوقت ذاته — بأرقام تستطيع الدفاع عنها أمام المجلس.', kpis: [{ label: '240٪ عائد على الاستثمار خلال 3 سنوات على Microsoft Entra ID', kind: 'outcome' }, { label: 'استرداد رأس المال في أقل من 6 أشهر', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'مصدر العائد على الاستثمار البالغ 240٪، واسترداد رأس المال في أقل من 6 أشهر، وانخفاض نحو 75٪ في تذاكر الدعم الفنّي المرتبطة بالهوية، وتقليل مخاطر الاختراق المرتبطة بالهوية.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'مصدر النتيجة بأن العملاء كانوا أقل احتمالاً بنسبة 88٪ للتعرّض لاختراق جوهري، مع متوسط زمن أسرع للاكتشاف والاستجابة.' },
            { title: 'Microsoft Security, Compliance & Identity — وثائق المنتج (Microsoft Learn)', note: 'مصدر Conditional Access وPrivileged Identity Management وسياسات DLP عبر البيئات وCustomer Lockbox والمفاتيح التي يديرها العميل والتكامل مع Microsoft Purview.' },
        ],
    },
    nl: {
        headline: 'Eén identiteits-, dreigings- en databeschermingsvlak voor elke Power Platform- en Dynamics 365-workload.',
        summary: 'Microsoft Entra ID, Microsoft Defender, Microsoft Sentinel en Microsoft Purview brengen identiteit, threat protection en datagovernance onder één dak — zodat de apps die uw makers opleveren en de Dynamics 365-omgevingen waarop uw business draait worden beveiligd door dezelfde controls, hetzelfde beleid en dezelfde auditbare evidence als de rest van uw Microsoft-landschap.',
        kpis: [
            { value: '240%', label: 'ROI over 3 jaar (Entra ID)', kind: 'outcome' },
            { value: '< 6 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '−50%', label: 'Identiteitsgerelateerd breachrisico', kind: 'outcome' },
            { value: '−75%', label: 'Identiteitsgerelateerde help-desktickets', kind: 'efficiency' },
            { value: '1', label: 'Verenigd controlevlak', kind: 'outcome' },
        ],
        bqPre: 'Citizen development, AI-agents en SaaS-sprawl vermenigvuldigen de plekken waar uw bedrijfsdata leeft — en elke nieuwe identiteit, app en integratie vergroot het oppervlak dat een aanvaller kan bereiken.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Als elke nieuwe app, agent en connector stilletjes uw aanvalsoppervlak vergroot, ',
        bqHighlight: 'hoe laat u de business dan snel vooruit op Power Platform en Dynamics 365 — zonder de controle over identiteit, data en audit-evidence op te geven?',
        figcaption: 'Strategische vraag die de businesscase voor de Enterprise Security-laag kadert.',
        bridge: 'Zo beantwoordt de Microsoft-securitystack die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van een wrijvingsloze sign-in voor eindgebruikers tot een tegenover de board verdedigbare cyberrisicopositie.',
        rungs: [
            { title: 'Eén sign-in, overal waar uw mensen werken', audience: 'Uw medewerkers en partners', what: 'Microsoft Entra ID levert single sign-on en self-service password reset over Power Platform, Dynamics 365, Microsoft 365 en duizenden SaaS-apps — met phishing-resistente MFA erbovenop.', outcome: 'Uw gebruikers stoppen met jongleren met wachtwoorden en herstellen lockouts zelf, terwijl uw helpdesk de kosten daarvan niet langer absorbeert.', kpis: [{ label: '~75% minder identiteitsgerelateerde help-desktickets', kind: 'efficiency' }, { label: 'Single sign-on over Microsoft en meer dan 1.000 SaaS-apps', kind: 'efficiency' }] },
            { title: 'De juiste toegang, voor de juiste persoon, in de juiste context', audience: 'Uw IT- en identity-admins', what: 'Conditional Access, RBAC en Privileged Identity Management laten u least-privilege-toegang verlenen op basis van gebruiker, apparaat, locatie en risicosignaal — en net zo snel weer intrekken.', outcome: 'U handhaaft Zero Trust zonder de business af te remmen en stopt met het overprovisioneren van permanente admin-rechten.', kpis: [{ label: 'Conditional Access-policies bij elke sign-in afgedwongen', kind: 'outcome' }, { label: 'Just-in-time en in tijd begrensde elevation voor privileged rollen', kind: 'efficiency' }] },
            { title: 'Zie dreigingen vroeg, beteugel ze snel', audience: 'Uw SecOps-team', what: 'Microsoft Defender XDR en Sentinel correleren signalen uit identities, endpoints, e-mail, cloud-apps en uw Power Platform / Dynamics 365-landschap in één AI-ondersteunde onderzoekservaring.', outcome: 'Uw analisten signaleren lateral movement en data-exfiltratie eerder — en lossen incidenten in een fractie van de tijd op.', kpis: [{ label: '88% minder kans op een materiële breach (Forrester TEI)', kind: 'outcome' }, { label: 'Snellere mean time to detect en respond over de hele kill chain', kind: 'efficiency' }] },
            { title: 'Data blijft waar het hoort — en alleen daar', audience: 'Uw CISO en compliance officers', what: 'DLP-policies over omgevingen, customer-managed keys, Customer Lockbox, tenantisolatie, geo-residency, audit logging en Microsoft Purview-labels gelden uniform voor elke Power App, flow en Dynamics 365-omgeving.', outcome: 'U geeft de business de vrijheid om te bouwen en houdt gereguleerde en gevoelige data binnen de grenzen die uw auditors verwachten.', kpis: [{ label: 'Centrale DLP en labelling voor het hele Power Platform / D365-landschap', kind: 'outcome' }, { label: 'Lagere audit- en compliancelast via één controlevlak', kind: 'efficiency' }] },
            { title: 'Een tegenover de board verdedigbare securitypositie', audience: 'Uw CEO en Raad van Bestuur', what: 'Identity, endpoint, data en app security komen samen op één Microsoft-platform — ter vervanging van een lange staart aan point products en de bijbehorende integratielast.', outcome: 'U verlaagt uw cyberrisico-exposure en uw security-TCO tegelijk, met cijfers die u tegenover de board kunt verdedigen.', kpis: [{ label: '240% ROI over 3 jaar op Microsoft Entra ID', kind: 'outcome' }, { label: 'Terugverdientijd van minder dan 6 maanden', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Entra ID', note: 'Bron voor de 240% ROI, terugverdientijd onder 6 maanden, ~75% reductie in identiteitsgerelateerde help-desktickets en verlaagd identiteitsgerelateerd breachrisico.' },
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Defender XDR', note: 'Bron voor de bevinding dat klanten 88% minder kans hadden op een materiële breach, met snellere mean time to detect en respond.' },
            { title: 'Microsoft Security, Compliance & Identity — productdocumentatie (Microsoft Learn)', note: 'Bron voor Conditional Access, Privileged Identity Management, DLP-policies over omgevingen, Customer Lockbox, customer-managed keys en Microsoft Purview-integratie.' },
        ],
    },
};

const RUNG_META = [
    { n: 1, AudienceIcon: UserRound, Icon: KeyRound },
    { n: 2, AudienceIcon: UsersIcon, Icon: ShieldCheck },
    { n: 3, AudienceIcon: Server, Icon: EyeOff },
    { n: 4, AudienceIcon: Lock, Icon: ShieldCheck },
    { n: 5, AudienceIcon: Building2, Icon: Trophy },
];

export default function BusinessValueEnterpriseSecurity({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} rungMeta={RUNG_META} />;
}
