import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Launch secure portals in weeks, not months.',
        summary: 'Power Pages democratizes external web development. Copilot generates layouts and forms from natural language, native Dataverse integration replaces custom APIs, and enterprise-grade identity and WAFs keep external surfaces safe — so your customers and partners self-serve while your call center stops drowning in routine tickets.',
        kpis: [
            { value: '200%+', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '< 6 mo', label: 'Payback period', kind: 'outcome' },
            { value: '−50–70%', label: 'Web development & design effort', kind: 'efficiency' },
            { value: '−15–20%', label: 'Routine support call volume', kind: 'outcome' },
            { value: 'Weeks vs months', label: 'Time-to-market for external portals', kind: 'efficiency' },
        ],
        bqPre: 'Providing seamless, secure self-service for your customers and partners is your core mandate, but currently, traditional web development requires months of coding and complex integrations just to surface backend data securely.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'If your IT team remains bottlenecked by custom portal development, ',
        bqHighlight: 'how will you scale digital engagement without aggressively inflating your web budgets and call center support costs?',
        figcaption: 'Strategic question framing the business case for Microsoft Power Pages.',
        bridge: 'Here is how Power Pages answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from the maker shipping a page all the way up to enterprise-wide external digital strategy.',
        rungs: [
            { title: 'Build pages by describing them', audience: 'Your web makers & developers', what: 'Copilot lets makers describe what they need in natural language to instantly generate web layouts, styling, forms, and text.', outcome: 'You bypass the friction of writing HTML/CSS from scratch and drastically reduce your web development costs.', kpis: [{ label: '50–70% reduction in web development and design effort', kind: 'efficiency' }, { label: 'Weeks instead of months for initial prototyping', kind: 'efficiency' }] },
            { title: 'Native data, no custom APIs', audience: 'Your IT directors & PMO', what: 'Power Pages is natively tied to Dataverse, eliminating the need to build custom APIs to securely connect the website to backend CRM/ERP data.', outcome: 'You rapidly deploy external portals that are instantly synchronized with your internal operations.', kpis: [{ label: 'Months-to-weeks reduction in time-to-market for external portals', kind: 'efficiency' }, { label: 'Elimination of custom API integration time', kind: 'efficiency' }] },
            { title: 'Enterprise-grade security, externally exposed', audience: 'Your CISO & enterprise architecture', what: 'Native Azure AD B2C identity management, Web Application Firewalls, and strict role-based data access controls keep external surfaces safe.', outcome: 'You confidently expose necessary operational data to external users without risking compliance breaches or data leakage.', kpis: [{ label: '100% centralized IT governance over external sites', kind: 'efficiency' }, { label: 'Zero data synchronization errors', kind: 'outcome' }] },
            { title: 'Self-service that actually deflects calls', audience: 'Your VP of CX & support operations', what: 'Customers, vendors, and partners log into a secure portal to check order statuses, submit support tickets, manage accounts, and view FAQs autonomously.', outcome: 'You reduce inbound inquiry volume so your human agents focus on high-value, complex cases.', kpis: [{ label: '15–20% reduction in routine call-center / support ticket volume', kind: 'outcome' }, { label: 'Higher Customer Satisfaction (CSAT)', kind: 'outcome' }] },
            { title: 'Modern external digital footprint', audience: 'Your CIO, CDO & Board', what: 'The enterprise shifts from rigid, expensive legacy portals to an agile, low-code architecture that scales external engagement efficiently.', outcome: 'You retire the massive TCO of legacy custom portals and build an agile digital presence that scales with the business.', kpis: [{ label: '200%+ ROI over 3 years', kind: 'outcome' }, { label: 'Significant reduction in TCO for external web properties', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Source for the 200%+ ROI, the reduction in time-to-market, and the financial impact of avoiding custom web development and third-party hosting costs.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Source for the 15–20% support ticket deflection rate achieved when organizations launch integrated, data-connected self-service portals for external stakeholders.' },
        ],
    },
    fr: {
        headline: 'Lancez des portails sécurisés en quelques semaines, pas en mois.',
        summary: 'Power Pages démocratise le développement web externe. Copilot génère mises en page et formulaires en langage naturel, l\'intégration native à Dataverse remplace les API personnalisées, et l\'identité d\'entreprise et les WAF protègent les surfaces externes — pour que vos clients et partenaires se servent eux-mêmes pendant que votre centre d\'appels cesse de crouler sous les tickets de routine.',
        kpis: [
            { value: '200 %+', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '< 6 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '−50 à 70 %', label: 'Effort de développement et de design web', kind: 'efficiency' },
            { value: '−15 à 20 %', label: 'Volume des appels support de routine', kind: 'outcome' },
            { value: 'Semaines vs mois', label: 'Time-to-market des portails externes', kind: 'efficiency' },
        ],
        bqPre: 'Offrir un self-service fluide et sécurisé à vos clients et partenaires est au cœur de votre mandat, mais aujourd\'hui le développement web traditionnel exige des mois de code et d\'intégrations complexes rien que pour exposer des données backend en toute sécurité.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si votre IT reste bloquée par le développement de portails sur mesure, ',
        bqHighlight: 'comment ferez-vous monter en puissance l\'engagement digital sans gonfler agressivement vos budgets web et vos coûts de support ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Microsoft Power Pages.',
        bridge: 'Voici comment Power Pages y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — du maker qui livre une page jusqu\'à la stratégie digitale externe à l\'échelle de l\'entreprise.',
        rungs: [
            { title: 'Construisez des pages en les décrivant', audience: 'Vos makers et développeurs web', what: 'Copilot permet aux makers de décrire ce dont ils ont besoin en langage naturel pour générer instantanément mises en page, styles, formulaires et textes.', outcome: 'Vous court-circuitez la friction du HTML/CSS écrit de zéro et réduisez drastiquement vos coûts de développement web.', kpis: [{ label: '50 à 70 % de réduction de l\'effort de développement et de design web', kind: 'efficiency' }, { label: 'Des semaines au lieu de mois pour le prototypage initial', kind: 'efficiency' }] },
            { title: 'Données natives, aucune API sur mesure', audience: 'Vos directions IT et PMO', what: 'Power Pages est nativement lié à Dataverse, ce qui élimine le besoin de bâtir des API personnalisées pour connecter sécuritairement le site aux données backend CRM/ERP.', outcome: 'Vous déployez rapidement des portails externes instantanément synchronisés avec vos opérations internes.', kpis: [{ label: 'Time-to-market des portails externes ramené de mois à semaines', kind: 'efficiency' }, { label: 'Élimination du temps d\'intégration d\'API sur mesure', kind: 'efficiency' }] },
            { title: 'Sécurité de niveau entreprise, exposée à l\'externe', audience: 'Votre CISO et architecture d\'entreprise', what: 'La gestion d\'identité native Azure AD B2C, les Web Application Firewalls et des contrôles d\'accès stricts par rôle protègent les surfaces externes.', outcome: 'Vous exposez en toute confiance les données opérationnelles nécessaires à des utilisateurs externes sans risquer de fuite de données ni de manquement à la conformité.', kpis: [{ label: '100 % de gouvernance IT centralisée sur les sites externes', kind: 'efficiency' }, { label: 'Zéro erreur de synchronisation de données', kind: 'outcome' }] },
            { title: 'Du self-service qui dévie réellement les appels', audience: 'Votre VP CX et opérations support', what: 'Clients, fournisseurs et partenaires se connectent à un portail sécurisé pour vérifier le statut de leurs commandes, soumettre des tickets, gérer leur compte et consulter les FAQ en toute autonomie.', outcome: 'Vous réduisez le volume des demandes entrantes pour que vos agents se concentrent sur les cas complexes à forte valeur.', kpis: [{ label: '15 à 20 % de réduction du volume des appels et tickets de routine', kind: 'outcome' }, { label: 'Satisfaction client (CSAT) en hausse', kind: 'outcome' }] },
            { title: 'Une empreinte digitale externe moderne', audience: 'Votre CIO, CDO et conseil d\'administration', what: 'L\'entreprise quitte des portails legacy rigides et coûteux pour une architecture low-code agile, qui fait monter en puissance l\'engagement externe avec efficience.', outcome: 'Vous mettez à la retraite l\'énorme TCO des portails sur mesure legacy et bâtissez une présence digitale agile qui grandit avec l\'entreprise.', kpis: [{ label: 'Plus de 200 % de ROI sur 3 ans', kind: 'outcome' }, { label: 'Réduction sensible du TCO sur les propriétés web externes', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Source du ROI supérieur à 200 %, de la réduction du time-to-market et de l\'impact financier de l\'évitement du développement web sur mesure et de l\'hébergement tiers.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Source du taux de déviation de 15 à 20 % des tickets support obtenu quand les organisations déploient des portails self-service intégrés et connectés aux données pour leurs parties prenantes externes.' },
        ],
    },
    de: {
        headline: 'Sichere Portale in Wochen statt Monaten ausrollen.',
        summary: 'Power Pages demokratisiert die externe Web-Entwicklung. Copilot generiert Layouts und Formulare aus natürlicher Sprache, die native Dataverse-Integration ersetzt eigene APIs, und Identitätsmanagement auf Enterprise-Niveau plus WAFs sichern externe Oberflächen ab — damit sich Ihre Kund:innen und Partner selbst bedienen, während Ihr Callcenter nicht länger in Routine-Tickets ertrinkt.',
        kpis: [
            { value: '200 %+', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '< 6 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '−50–70 %', label: 'Aufwand für Web-Entwicklung & Design', kind: 'efficiency' },
            { value: '−15–20 %', label: 'Routine-Supportanrufe', kind: 'outcome' },
            { value: 'Wochen statt Monate', label: 'Time-to-Market für externe Portale', kind: 'efficiency' },
        ],
        bqPre: 'Nahtlosen, sicheren Self-Service für Ihre Kund:innen und Partner anzubieten ist Ihr Kernauftrag — doch klassische Web-Entwicklung verlangt heute Monate an Code und komplexe Integrationen, nur um Backend-Daten sicher freizugeben.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Wenn Ihre IT weiterhin im Engpass kundenspezifischer Portalentwicklung steckt — ',
        bqHighlight: 'wie wollen Sie dann die digitale Kundenbindung skalieren, ohne Web-Budgets und Support-Kosten massiv aufzublähen?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Microsoft Power Pages.',
        bridge: 'So beantwortet Power Pages diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — vom Maker, der eine Seite ausliefert, bis zur unternehmensweiten externen Digitalstrategie.',
        rungs: [
            { title: 'Seiten bauen, indem man sie beschreibt', audience: 'Ihre Web-Maker:innen und Entwickler:innen', what: 'Mit Copilot beschreiben Maker:innen ihren Bedarf in natürlicher Sprache und erhalten sofort Layouts, Stile, Formulare und Texte.', outcome: 'Sie umgehen die Reibung, HTML/CSS von Grund auf zu schreiben, und senken Ihre Web-Entwicklungskosten drastisch.', kpis: [{ label: '50–70 % weniger Aufwand für Web-Entwicklung und Design', kind: 'efficiency' }, { label: 'Wochen statt Monate für das initiale Prototyping', kind: 'efficiency' }] },
            { title: 'Native Daten, keine eigenen APIs', audience: 'Ihre IT-Leitung und das PMO', what: 'Power Pages ist nativ an Dataverse angebunden — das eliminiert die Notwendigkeit eigener APIs, um die Website sicher mit Backend-CRM/ERP-Daten zu verbinden.', outcome: 'Sie rollen externe Portale schnell aus, die augenblicklich mit Ihren internen Operations synchron sind.', kpis: [{ label: 'Time-to-Market für externe Portale von Monaten auf Wochen reduziert', kind: 'efficiency' }, { label: 'Eliminierung der Integrationszeit für eigene APIs', kind: 'efficiency' }] },
            { title: 'Enterprise-Sicherheit, nach außen exponiert', audience: 'Ihre CISO und Enterprise Architecture', what: 'Natives Azure-AD-B2C-Identitätsmanagement, Web Application Firewalls und strikte rollenbasierte Datenzugriffskontrollen sichern die externen Oberflächen ab.', outcome: 'Sie geben notwendige operative Daten an externe Nutzer:innen frei, ohne Compliance-Verstöße oder Datenabflüsse zu riskieren.', kpis: [{ label: '100 % zentralisierte IT-Governance über externe Sites', kind: 'efficiency' }, { label: 'Null Datensynchronisationsfehler', kind: 'outcome' }] },
            { title: 'Self-Service, der Anrufe wirklich abfängt', audience: 'Ihre VP CX und Support Operations', what: 'Kund:innen, Lieferanten und Partner melden sich an einem sicheren Portal an, um Bestellstatus zu prüfen, Tickets zu eröffnen, Konten zu verwalten und FAQs eigenständig zu nutzen.', outcome: 'Sie senken das Volumen eingehender Anfragen, sodass sich Ihre Agent:innen auf hochwertige, komplexe Fälle konzentrieren.', kpis: [{ label: '15–20 % weniger Routine-Anrufe und Support-Tickets', kind: 'outcome' }, { label: 'Höhere Kundenzufriedenheit (CSAT)', kind: 'outcome' }] },
            { title: 'Ein moderner externer digitaler Fußabdruck', audience: 'Ihre CIO, CDO und Vorstand', what: 'Das Unternehmen löst sich von starren, teuren Legacy-Portalen und wechselt zu einer agilen Low-Code-Architektur, die externe Customer Engagement effizient skaliert.', outcome: 'Sie verabschieden sich vom hohen TCO maßgeschneiderter Legacy-Portale und bauen eine agile digitale Präsenz, die mit dem Geschäft mitwächst.', kpis: [{ label: 'Über 200 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Deutlich gesenkter TCO für externe Web-Properties', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Quelle für den ROI von über 200 %, die Reduktion der Time-to-Market und den finanziellen Effekt vermiedener kundenspezifischer Web-Entwicklung und Drittanbieter-Hosting-Kosten.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Quelle für die Ticket-Deflection-Rate von 15–20 %, die Organisationen erreichen, wenn sie integrierte, datenangebundene Self-Service-Portale für externe Stakeholder bereitstellen.' },
        ],
    },
    es: {
        headline: 'Lance portales seguros en semanas, no en meses.',
        summary: 'Power Pages democratiza el desarrollo web externo. Copilot genera diseños y formularios a partir de lenguaje natural, la integración nativa con Dataverse sustituye las API personalizadas y la identidad de nivel empresarial junto con los WAF mantienen seguras las superficies externas — para que sus clientes y partners se autoatiendan mientras su call center deja de ahogarse en tickets rutinarios.',
        kpis: [
            { value: '200 %+', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '< 6 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '−50–70 %', label: 'Esfuerzo de desarrollo y diseño web', kind: 'efficiency' },
            { value: '−15–20 %', label: 'Volumen de llamadas de soporte rutinarias', kind: 'outcome' },
            { value: 'Semanas vs meses', label: 'Time-to-market de portales externos', kind: 'efficiency' },
        ],
        bqPre: 'Ofrecer un autoservicio fluido y seguro a sus clientes y partners es su mandato central, pero hoy el desarrollo web tradicional exige meses de código e integraciones complejas solo para exponer datos de backend de forma segura.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si su equipo de TI sigue siendo el cuello de botella del desarrollo de portales a medida, ',
        bqHighlight: '¿cómo va a escalar el engagement digital sin inflar agresivamente sus presupuestos web y los costes del centro de soporte?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Microsoft Power Pages.',
        bridge: 'Así responde Power Pages',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde el maker que entrega una página hasta la estrategia digital externa a nivel de toda la empresa.',
        rungs: [
            { title: 'Construya páginas describiéndolas', audience: 'Sus makers y desarrolladores web', what: 'Copilot permite a los makers describir lo que necesitan en lenguaje natural para generar al instante diseños, estilos, formularios y textos.', outcome: 'Esquiva la fricción de escribir HTML/CSS desde cero y reduce drásticamente sus costes de desarrollo web.', kpis: [{ label: 'Reducción del 50–70 % en el esfuerzo de desarrollo y diseño web', kind: 'efficiency' }, { label: 'Semanas en vez de meses para el prototipado inicial', kind: 'efficiency' }] },
            { title: 'Datos nativos, sin API a medida', audience: 'Sus directores de TI y PMO', what: 'Power Pages está nativamente conectado a Dataverse, lo que elimina la necesidad de construir API personalizadas para conectar el sitio web de forma segura con los datos de CRM/ERP.', outcome: 'Despliega rápidamente portales externos sincronizados al instante con sus operaciones internas.', kpis: [{ label: 'Time-to-market de portales externos reducido de meses a semanas', kind: 'efficiency' }, { label: 'Eliminación del tiempo de integración de API personalizadas', kind: 'efficiency' }] },
            { title: 'Seguridad de nivel empresarial, expuesta al exterior', audience: 'Su CISO y arquitectura empresarial', what: 'La gestión de identidad nativa con Azure AD B2C, los Web Application Firewalls y los controles estrictos de acceso por rol mantienen seguras las superficies externas.', outcome: 'Expone con confianza los datos operativos necesarios a usuarios externos sin arriesgar fugas de datos ni incumplimientos de cumplimiento.', kpis: [{ label: '100 % de gobernanza de TI centralizada sobre los sitios externos', kind: 'efficiency' }, { label: 'Cero errores de sincronización de datos', kind: 'outcome' }] },
            { title: 'Autoservicio que de verdad desvía llamadas', audience: 'Su VP de CX y operaciones de soporte', what: 'Clientes, proveedores y partners entran en un portal seguro para consultar el estado de sus pedidos, abrir tickets, gestionar cuentas y consultar las FAQ de forma autónoma.', outcome: 'Reduce el volumen de consultas entrantes para que sus agentes humanos se centren en los casos complejos de mayor valor.', kpis: [{ label: 'Reducción del 15–20 % en llamadas y tickets de soporte rutinarios', kind: 'outcome' }, { label: 'Mayor satisfacción del cliente (CSAT)', kind: 'outcome' }] },
            { title: 'Una huella digital externa moderna', audience: 'Su CIO, CDO y Consejo', what: 'La empresa abandona portales heredados rígidos y caros y se mueve a una arquitectura low-code ágil, que escala el engagement externo con eficiencia.', outcome: 'Jubila el enorme TCO de los portales heredados a medida y construye una presencia digital ágil que crece con el negocio.', kpis: [{ label: 'Más del 200 % de ROI en 3 años', kind: 'outcome' }, { label: 'Reducción significativa del TCO en propiedades web externas', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Fuente del ROI superior al 200 %, la reducción del time-to-market y el impacto financiero de evitar el desarrollo web a medida y el hosting de terceros.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Fuente de la tasa de desviación de tickets del 15–20 % alcanzada cuando las organizaciones lanzan portales de autoservicio integrados y conectados a datos para sus stakeholders externos.' },
        ],
    },
    it: {
        headline: 'Lanciate portali sicuri in settimane, non in mesi.',
        summary: 'Power Pages democratizza lo sviluppo web esterno. Copilot genera layout e form a partire dal linguaggio naturale, l\'integrazione nativa con Dataverse sostituisce le API custom e l\'identity di livello enterprise insieme ai WAF tengono al sicuro le superfici esterne — così clienti e partner si servono da soli mentre il vostro call center smette di affogare nei ticket di routine.',
        kpis: [
            { value: '200 %+', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '< 6 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '−50–70 %', label: 'Effort di sviluppo e design web', kind: 'efficiency' },
            { value: '−15–20 %', label: 'Volume di chiamate di supporto di routine', kind: 'outcome' },
            { value: 'Settimane vs mesi', label: 'Time-to-market dei portali esterni', kind: 'efficiency' },
        ],
        bqPre: 'Offrire ai vostri clienti e partner un self-service fluido e sicuro è il vostro mandato centrale, ma oggi lo sviluppo web tradizionale richiede mesi di codice e integrazioni complesse solo per esporre in sicurezza i dati di backend.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Se la vostra IT resta imbottigliata nello sviluppo di portali custom, ',
        bqHighlight: 'come farete a scalare l\'engagement digitale senza gonfiare in modo aggressivo i budget web e i costi del call center?',
        figcaption: 'Domanda strategica che inquadra il business case di Microsoft Power Pages.',
        bridge: 'Ecco come risponde Power Pages',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dal maker che mette in produzione una pagina fino alla strategia digitale esterna a livello di intera azienda.',
        rungs: [
            { title: 'Costruisci pagine descrivendole', audience: 'I tuoi maker e sviluppatori web', what: 'Copilot consente ai maker di descrivere ciò che serve in linguaggio naturale per generare all\'istante layout, stili, form e testi.', outcome: 'Aggiri l\'attrito di scrivere HTML/CSS da zero e abbatti drasticamente i costi di sviluppo web.', kpis: [{ label: 'Riduzione del 50–70 % dell\'effort di sviluppo e design web', kind: 'efficiency' }, { label: 'Settimane invece di mesi per il prototyping iniziale', kind: 'efficiency' }] },
            { title: 'Dati nativi, niente API custom', audience: 'I tuoi direttori IT e il PMO', what: 'Power Pages è nativamente collegato a Dataverse, eliminando la necessità di costruire API custom per connettere in sicurezza il sito ai dati di CRM/ERP backend.', outcome: 'Distribuisci rapidamente portali esterni istantaneamente sincronizzati con le operations interne.', kpis: [{ label: 'Time-to-market dei portali esterni ridotto da mesi a settimane', kind: 'efficiency' }, { label: 'Eliminazione del tempo di integrazione di API custom', kind: 'efficiency' }] },
            { title: 'Sicurezza enterprise, esposta all\'esterno', audience: 'Il tuo CISO e l\'enterprise architecture', what: 'La gestione di identity nativa Azure AD B2C, i Web Application Firewall e i controlli rigorosi di accesso ai dati basati su ruolo proteggono le superfici esterne.', outcome: 'Esponi in totale tranquillità i dati operativi necessari agli utenti esterni senza rischiare fughe di dati o violazioni di compliance.', kpis: [{ label: '100 % di governance IT centralizzata sui siti esterni', kind: 'efficiency' }, { label: 'Zero errori di sincronizzazione dei dati', kind: 'outcome' }] },
            { title: 'Self-service che devia davvero le chiamate', audience: 'Il tuo VP CX e operations di supporto', what: 'Clienti, fornitori e partner accedono a un portale sicuro per controllare lo stato degli ordini, aprire ticket, gestire l\'account e consultare le FAQ in autonomia.', outcome: 'Riduci il volume delle richieste in ingresso così i tuoi agenti umani si concentrano sui casi complessi a maggior valore.', kpis: [{ label: 'Riduzione del 15–20 % dei volumi di chiamate e ticket di supporto di routine', kind: 'outcome' }, { label: 'Maggiore Customer Satisfaction (CSAT)', kind: 'outcome' }] },
            { title: 'Un\'impronta digitale esterna moderna', audience: 'Il tuo CIO, CDO e Consiglio di Amministrazione', what: 'L\'azienda passa da portali legacy rigidi e costosi a un\'architettura low-code agile, che scala in modo efficiente l\'engagement esterno.', outcome: 'Mandi in pensione il TCO enorme dei portali custom legacy e costruisci una presenza digitale agile che cresce con il business.', kpis: [{ label: 'Oltre 200 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Riduzione significativa del TCO sulle property web esterne', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Fonte del ROI superiore al 200 %, della riduzione del time-to-market e dell\'impatto finanziario dell\'evitare lo sviluppo web custom e gli hosting di terze parti.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Fonte del tasso di deflection dei ticket del 15–20 % raggiunto quando le organizzazioni lanciano portali self-service integrati e connessi ai dati per gli stakeholder esterni.' },
        ],
    },
    ar: {
        headline: 'أطلِق بوّابات آمنة في أسابيع لا في أشهر.',
        summary: 'يُتيح Power Pages لكل شخص الإسهام في تطوير الويب الموجَّه للخارج. يُولّد Copilot تخطيطات الصفحات والنماذج من اللغة الطبيعية، وتحلّ التكامل الأصيل مع Dataverse محلّ واجهات API المُخصَّصة، وتحفظ إدارة الهوية بمستوى المؤسسات وجدران حماية تطبيقات الويب (WAF) سلامة الواجهات الخارجية — فيخدم عملاؤك وشركاؤك أنفسهم بأنفسهم بينما يكُفّ مركز اتصالاتك عن الغرق في تذاكر روتينية.',
        kpis: [
            { value: '200٪+', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: 'أقل من 6 أشهر', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '−50–70٪', label: 'جهد تطوير وتصميم الويب', kind: 'efficiency' },
            { value: '−15–20٪', label: 'حجم مكالمات الدعم الروتينية', kind: 'outcome' },
            { value: 'أسابيع مقابل أشهر', label: 'سرعة الوصول إلى السوق للبوّابات الخارجية', kind: 'efficiency' },
        ],
        bqPre: 'تقديم خدمة ذاتية سلسة وآمنة لعملائك وشركائك مهمّتك الجوهرية، لكن تطوير الويب التقليدي اليوم يستلزم أشهراً من البرمجة وعمليات تكامل معقّدة لمجرّد إظهار بيانات الأنظمة الخلفية بأمان.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'إذا ظلّ فريق تقنية المعلومات لديك مُكبَّلاً بتطوير بوّابات مُخصَّصة، ',
        bqHighlight: 'فكيف ستوسّع التفاعل الرقمي دون تضخيم ميزانيات الويب وتكاليف مركز الدعم بشكل حادّ؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Microsoft Power Pages.',
        bridge: 'إليك كيف يجيب Power Pages عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من الـ maker الذي يطلق صفحة، وصولاً إلى الاستراتيجية الرقمية الخارجية على مستوى المؤسسة بأكملها.',
        rungs: [
            { title: 'ابنِ الصفحات بمجرّد وصفها', audience: 'صنّاع الويب والمطوّرون لديك', what: 'يُتيح Copilot للصنّاع وصف ما يحتاجونه باللغة الطبيعية لتوليد التخطيطات والتنسيقات والنماذج والنصوص فوراً.', outcome: 'تتجاوز عناء كتابة HTML/CSS من الصفر وتُخفّض تكاليف تطوير الويب لديك تخفيضاً جذرياً.', kpis: [{ label: 'انخفاض 50–70٪ في جهد تطوير وتصميم الويب', kind: 'efficiency' }, { label: 'أسابيع بدلاً من أشهر للنماذج الأوّلية', kind: 'efficiency' }] },
            { title: 'بيانات أصلية بلا واجهات API مُخصَّصة', audience: 'مدراء تقنية المعلومات ومكتب إدارة المشاريع لديك', what: 'يرتبط Power Pages أصيلاً بـ Dataverse، مما يُلغي الحاجة إلى بناء واجهات API مُخصَّصة لربط الموقع بأمان ببيانات أنظمة CRM/ERP الخلفية.', outcome: 'تنشر بسرعة بوّابات خارجية متزامنة فوراً مع عملياتك الداخلية.', kpis: [{ label: 'تقليص سرعة الوصول إلى السوق للبوّابات الخارجية من أشهر إلى أسابيع', kind: 'efficiency' }, { label: 'إلغاء وقت تكامل واجهات API المُخصَّصة', kind: 'efficiency' }] },
            { title: 'أمن بمستوى المؤسسات معروض للخارج', audience: 'مدير أمن المعلومات والهندسة المعمارية المؤسسية لديك', what: 'تحفظ إدارة الهوية الأصيلة عبر Azure AD B2C وجدران حماية تطبيقات الويب وضوابط الوصول الصارمة المبنية على الأدوار سلامة الواجهات الخارجية.', outcome: 'تعرض البيانات التشغيلية الضرورية للمستخدمين الخارجيين بثقة، دون المخاطرة بانتهاكات الامتثال أو تسرّب البيانات.', kpis: [{ label: 'حوكمة تقنية معلومات مركزية بنسبة 100٪ على المواقع الخارجية', kind: 'efficiency' }, { label: 'صفر أخطاء في مزامنة البيانات', kind: 'outcome' }] },
            { title: 'خدمة ذاتية تُحوِّل المكالمات فعلاً', audience: 'نائب رئيس تجربة العملاء وعمليات الدعم لديك', what: 'يُسجّل العملاء والموردون والشركاء الدخول إلى بوّابة آمنة لمتابعة حالات الطلبات وتقديم تذاكر الدعم وإدارة حساباتهم والاطّلاع على الأسئلة الشائعة باستقلالية تامّة.', outcome: 'تُقلّل حجم الاستفسارات الواردة كي يُركّز وكلاؤك البشريون على الحالات المعقّدة العالية القيمة.', kpis: [{ label: 'انخفاض 15–20٪ في حجم مكالمات وتذاكر الدعم الروتينية', kind: 'outcome' }, { label: 'ارتفاع رضا العملاء (CSAT)', kind: 'outcome' }] },
            { title: 'بصمة رقمية خارجية حديثة', audience: 'مدير تقنية المعلومات ومدير الشؤون الرقمية ومجلس الإدارة لديك', what: 'تنتقل المؤسسة من بوّابات قديمة جامدة ومُكلِفة إلى بنية low-code رشيقة، تُوسّع التفاعل الخارجي بكفاءة.', outcome: 'تتخلّص من التكلفة الإجمالية الضخمة للبوّابات المُخصَّصة القديمة وتبني حضوراً رقمياً رشيقاً ينمو مع الأعمال.', kpis: [{ label: 'عائد على الاستثمار يفوق 200٪ خلال 3 سنوات', kind: 'outcome' }, { label: 'انخفاض ملحوظ في التكلفة الإجمالية للممتلكات الإلكترونية الخارجية', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'مصدر العائد على الاستثمار الذي يفوق 200٪، وتقليص سرعة الوصول إلى السوق، والأثر المالي لتفادي تطوير الويب المُخصَّص وتكاليف الاستضافة من أطراف ثالثة.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'مصدر معدّل تحويل تذاكر الدعم البالغ 15–20٪ الذي تُحقّقه المؤسسات حين تُطلق بوّابات خدمة ذاتية متكاملة ومتّصلة بالبيانات لأصحاب المصلحة الخارجيين.' },
        ],
    },
    nl: {
        headline: 'Lanceer veilige portals in weken, niet in maanden.',
        summary: 'Power Pages democratiseert externe webontwikkeling. Copilot genereert layouts en formulieren uit natuurlijke taal, native Dataverse-integratie vervangt custom API\'s en enterprise-grade identity en WAFs houden externe oppervlakken veilig — zodat uw klanten en partners zelfservicen terwijl uw callcenter niet langer verzuipt in routinetickets.',
        kpis: [
            { value: '200%+', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '< 6 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '−50–70%', label: 'Webontwikkel- en designinspanning', kind: 'efficiency' },
            { value: '−15–20%', label: 'Volume routine-supportgesprekken', kind: 'outcome' },
            { value: 'Weken vs maanden', label: 'Time-to-market voor externe portals', kind: 'efficiency' },
        ],
        bqPre: 'Naadloze, veilige selfservice bieden aan uw klanten en partners is uw kernopdracht, maar traditionele webontwikkeling vraagt vandaag maanden code en complexe integraties louter om backend-data veilig te ontsluiten.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Als uw IT-team in de bottleneck blijft van custom portal-ontwikkeling, ',
        bqHighlight: 'hoe gaat u dan digitale engagement opschalen zonder uw webbudget en supportkosten agressief op te blazen?',
        figcaption: 'Strategische vraag die de businesscase voor Microsoft Power Pages kadert.',
        bridge: 'Zo beantwoordt Power Pages die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de maker die een pagina oplevert tot een externe digitale strategie op ondernemingsniveau.',
        rungs: [
            { title: 'Bouw pagina\'s door ze te beschrijven', audience: 'Uw web makers en developers', what: 'Copilot laat makers in natuurlijke taal beschrijven wat ze nodig hebben en genereert direct layouts, styling, formulieren en tekst.', outcome: 'U omzeilt de frictie van HTML/CSS vanaf nul schrijven en verlaagt uw webontwikkelingskosten drastisch.', kpis: [{ label: '50–70% minder webontwikkel- en designinspanning', kind: 'efficiency' }, { label: 'Weken in plaats van maanden voor initiële prototyping', kind: 'efficiency' }] },
            { title: 'Native data, geen custom API\'s', audience: 'Uw IT-directie en PMO', what: 'Power Pages is native gekoppeld aan Dataverse, waardoor het bouwen van custom API\'s om de site veilig met backend-CRM/ERP-data te verbinden overbodig wordt.', outcome: 'U rolt snel externe portals uit die direct synchroon lopen met uw interne operations.', kpis: [{ label: 'Time-to-market voor externe portals teruggebracht van maanden naar weken', kind: 'efficiency' }, { label: 'Eliminatie van integratietijd voor custom API\'s', kind: 'efficiency' }] },
            { title: 'Enterprise-grade beveiliging, extern blootgesteld', audience: 'Uw CISO en enterprise architecture', what: 'Native Azure AD B2C identity management, Web Application Firewalls en strikte rolgebaseerde toegangscontrole houden externe oppervlakken veilig.', outcome: 'U stelt noodzakelijke operationele data met vertrouwen open voor externe gebruikers, zonder compliance-inbreuken of data lekken te riskeren.', kpis: [{ label: '100% gecentraliseerde IT-governance over externe sites', kind: 'efficiency' }, { label: 'Nul datasynchronisatiefouten', kind: 'outcome' }] },
            { title: 'Selfservice die echt calls afvangt', audience: 'Uw VP CX en support operations', what: 'Klanten, leveranciers en partners loggen in op een veilig portal om orderstatussen te checken, supporttickets in te dienen, accounts te beheren en FAQ\'s zelfstandig te raadplegen.', outcome: 'U verlaagt het volume van inkomende vragen, zodat uw agents zich op hoogwaardige, complexe cases richten.', kpis: [{ label: '15–20% reductie in routine-callcenter- en supportticketvolume', kind: 'outcome' }, { label: 'Hogere klanttevredenheid (CSAT)', kind: 'outcome' }] },
            { title: 'Een moderne externe digitale footprint', audience: 'Uw CIO, CDO en Raad van Bestuur', what: 'De onderneming verschuift van starre, dure legacy-portals naar een wendbare low-code-architectuur die externe engagement efficiënt opschaalt.', outcome: 'U neemt afscheid van de enorme TCO van custom legacy-portals en bouwt een wendbare digitale aanwezigheid die met het bedrijf meegroeit.', kpis: [{ label: 'Meer dan 200% ROI over 3 jaar', kind: 'outcome' }, { label: 'Significante TCO-reductie op externe webproperties', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Pages', note: 'Bron voor de ROI van meer dan 200%, de reductie in time-to-market en de financiële impact van het vermijden van custom webontwikkeling en third-party hostingkosten.' },
            { title: 'Customer Experience Benchmarks — Self-Service Portals', note: 'Bron voor de 15–20% ticket-deflectionratio die organisaties bereiken wanneer ze geïntegreerde, op data aangesloten selfservice-portals voor externe stakeholders lanceren.' },
        ],
    },
};

export default function BusinessValuePowerPages({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
