import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Free your HR team from the helpdesk — and into the talent strategy.',
        summary: 'Dynamics 365 Human Resources combines Copilot in Microsoft Teams, end-to-end employee self-service, and a unified workforce data model. The result is fewer routine tickets, faster onboarding, and measurably stronger retention — backed by independently validated industry benchmarks.',
        kpis: [
            { value: '130%+', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '<12 mo', label: 'Payback period', kind: 'outcome' },
            { value: '−40–50%', label: 'Routine HR helpdesk tickets', kind: 'efficiency' },
            { value: '−30%', label: 'New-hire onboarding time', kind: 'efficiency' },
            { value: '−10–15%', label: 'Voluntary turnover', kind: 'outcome' },
        ],
        bqPre: 'Attracting, developing, and retaining top talent is your core mandate, but currently, your HR team spends up to ',
        bqPct: '60%',
        bqPost: ' of their time acting as an administrative helpdesk managing routine inquiries and disjointed systems.',
        bqLeadIn: 'If your HR professionals continue to act as manual data processors, ',
        bqHighlight: 'how will you execute the strategic retention and development programs the board expects without aggressively expanding your HR headcount?',
        figcaption: 'Strategic question framing the business case for Dynamics 365 Human Resources.',
        bridge: 'Here is how Dynamics 365 Human Resources answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from individual employee experience all the way up to board-level talent strategy.',
        rungs: [
            { title: 'Self-service that actually works', audience: 'Your HR staff & employees', what: 'Copilot inside Microsoft Teams lets your employees self-serve leave balances, benefits enrollment, and routine inquiries naturally in their flow of work.', outcome: 'You remove the administrative bottleneck — employees get instant answers and your HR staff get their week back.', kpis: [{ label: '40–50% reduction in routine HR helpdesk tickets', kind: 'efficiency' }, { label: 'Significant reduction in manual data-entry hours', kind: 'efficiency' }] },
            { title: 'Onboarding that makes day-one count', audience: 'Your talent acquisition & ops', what: 'Automated workflows orchestrate the full employee lifecycle — from streamlined onboarding tasks to cross-departmental offboarding checklists.', outcome: 'You accelerate the onboarding lifecycle and get new talent contributing far faster.', kpis: [{ label: '30% reduction in new-hire onboarding time', kind: 'efficiency' }, { label: 'Faster overall time-to-productivity for new roles', kind: 'efficiency' }] },
            { title: 'One trustworthy view of your workforce', audience: 'Your VP of HR / HRIS', what: 'The platform centralizes all workforce data — skills, compensation, leave, performance — in a single secure environment that natively connects to Finance and Operations.', outcome: 'You map skills gaps in real time and align headcount directly with corporate budgets.', kpis: [{ label: '100% unified workforce visibility', kind: 'efficiency' }, { label: 'Eradication of manual payroll / HR data reconciliation errors', kind: 'efficiency' }] },
            { title: 'A workplace people stay at', audience: 'Your CHRO', what: 'Employees experience a modern, frictionless workplace where administrative needs are handled instantly, while HR dedicates its time to coaching, wellness, and proactive retention.', outcome: 'You turn HR into a strategic retention engine — boosting morale and keeping your top performers engaged.', kpis: [{ label: '10–15% reduction in voluntary employee turnover', kind: 'outcome' }, { label: 'Higher Employee Net Promoter Score (eNPS)', kind: 'outcome' }] },
            { title: 'HR as a strategic business partner', audience: 'Your CHRO, CEO & Board', what: 'HR shifts from a reactive, administrative cost center into a strategic partner that optimizes human capital to drive organizational agility.', outcome: 'You lower HR operational costs and give the board the agile, high-performing workforce strategy demands.', kpis: [{ label: '130%+ ROI over 3 years', kind: 'outcome' }, { label: 'Lower overall HR administration cost per employee', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Source for the 130%+ ROI, <12-month payback, reductions in HR helpdesk tickets, and improvements in retention and onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot in Dynamics 365 HR & Microsoft Teams', note: 'Source for the productivity gains in employee self-service, onboarding orchestration, and reduction of manual HR administration.' },
        ],
    },
    fr: {
        headline: 'Libérez vos équipes RH du helpdesk — et orientez-les vers la stratégie talent.',
        summary: 'Dynamics 365 Human Resources combine Copilot dans Microsoft Teams, un self-service collaborateur de bout en bout et un modèle de données RH unifié. Résultat : moins de tickets de routine, un onboarding plus rapide et une rétention mesurablement plus forte — appuyés par des indicateurs sectoriels validés de manière indépendante.',
        kpis: [
            { value: '130 %+', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '< 12 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '−40–50 %', label: 'Tickets RH de routine', kind: 'efficiency' },
            { value: '−30 %', label: 'Durée d\'onboarding des nouveaux collaborateurs', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Turnover volontaire', kind: 'outcome' },
        ],
        bqPre: 'Attirer, développer et fidéliser les meilleurs talents est votre mission centrale, mais aujourd\'hui votre équipe RH consacre jusqu\'à ',
        bqPct: '60 %',
        bqPost: ' de son temps à jouer le rôle d\'un helpdesk administratif en gérant des requêtes de routine et des systèmes cloisonnés.',
        bqLeadIn: 'Si vos professionnels RH continuent à n\'être que des processeurs manuels de données, ',
        bqHighlight: 'comment exécuterez-vous les programmes stratégiques de rétention et de développement attendus par le conseil d\'administration sans gonfler agressivement vos effectifs RH ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Dynamics 365 Human Resources.',
        bridge: 'Voici comment Dynamics 365 Human Resources y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — de l\'expérience individuelle du collaborateur jusqu\'à la stratégie talent au niveau du conseil d\'administration.',
        rungs: [
            { title: 'Un self-service qui fonctionne vraiment', audience: 'Vos équipes RH et vos collaborateurs', what: 'Copilot dans Microsoft Teams permet à vos collaborateurs de consulter eux-mêmes leurs soldes de congés, de souscrire à leurs avantages sociaux et de poser leurs questions de routine, naturellement dans leur flux de travail.', outcome: 'Vous éliminez le goulet administratif — les collaborateurs obtiennent des réponses immédiates et vos équipes RH récupèrent leur semaine.', kpis: [{ label: '40–50 % de tickets RH de routine en moins', kind: 'efficiency' }, { label: 'Réduction significative des heures de saisie manuelle', kind: 'efficiency' }] },
            { title: 'Un onboarding qui rend le jour 1 utile', audience: 'Vos équipes recrutement et opérations RH', what: 'Des workflows automatisés orchestrent l\'ensemble du cycle de vie collaborateur — des tâches d\'onboarding rationalisées aux checklists d\'offboarding inter-services.', outcome: 'Vous accélérez le cycle d\'onboarding et permettez aux nouveaux talents d\'être productifs bien plus vite.', kpis: [{ label: '30 % de réduction du temps d\'onboarding des nouveaux collaborateurs', kind: 'efficiency' }, { label: 'Réduction du time-to-productivity global pour les nouveaux postes', kind: 'efficiency' }] },
            { title: 'Une vision unique et fiable de vos effectifs', audience: 'Votre VP RH / SIRH', what: 'La plateforme centralise toutes les données RH — compétences, rémunération, absences, performance — dans un environnement unique et sécurisé, nativement connecté à la finance et aux opérations.', outcome: 'Vous cartographiez les écarts de compétences en temps réel et alignez les effectifs directement sur les budgets de l\'entreprise.', kpis: [{ label: '100 % de visibilité unifiée sur les effectifs', kind: 'efficiency' }, { label: 'Élimination des erreurs de réconciliation manuelle paie / SIRH', kind: 'efficiency' }] },
            { title: 'Un environnement de travail dans lequel les gens restent', audience: 'Votre DRH (CHRO)', what: 'Les collaborateurs vivent une expérience moderne et fluide où les besoins administratifs sont traités instantanément, pendant que les RH consacrent leur temps au coaching, au bien-être et à la rétention proactive.', outcome: 'Vous transformez les RH en moteur stratégique de rétention — en améliorant le moral et en gardant vos meilleurs profils engagés.', kpis: [{ label: '10–15 % de réduction du turnover volontaire', kind: 'outcome' }, { label: 'Employee Net Promoter Score (eNPS) plus élevé', kind: 'outcome' }] },
            { title: 'Les RH comme partenaire business stratégique', audience: 'Votre DRH, PDG et conseil d\'administration', what: 'Les RH cessent d\'être un centre de coût administratif réactif pour devenir un partenaire stratégique qui optimise le capital humain et favorise l\'agilité organisationnelle.', outcome: 'Vous baissez les coûts opérationnels RH et offrez au conseil la stratégie d\'effectifs agile et performante exigée par le marché.', kpis: [{ label: 'Plus de 130 % de ROI sur 3 ans', kind: 'outcome' }, { label: 'Coût d\'administration RH par collaborateur globalement plus bas', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Source pour le ROI de plus de 130 %, le retour sur investissement en moins de 12 mois, la réduction des tickets RH et l\'amélioration de la rétention et de l\'onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot dans Dynamics 365 HR et Microsoft Teams', note: 'Source pour les gains de productivité sur le self-service collaborateur, l\'orchestration de l\'onboarding et la réduction de l\'administration RH manuelle.' },
        ],
    },
    de: {
        headline: 'Befreien Sie Ihr HR-Team vom Helpdesk — und in die Talentstrategie.',
        summary: 'Dynamics 365 Human Resources kombiniert Copilot in Microsoft Teams, durchgängigen Mitarbeiter-Self-Service und ein vereinheitlichtes Workforce-Datenmodell. Das Ergebnis: weniger Routine-Tickets, schnelleres Onboarding und messbar stärkere Bindung — gestützt auf unabhängig validierte Branchen-Benchmarks.',
        kpis: [
            { value: '130 %+', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '< 12 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '−40–50 %', label: 'Routine-HR-Helpdesk-Tickets', kind: 'efficiency' },
            { value: '−30 %', label: 'Onboarding-Zeit für neue Mitarbeitende', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Freiwillige Fluktuation', kind: 'outcome' },
        ],
        bqPre: 'Top-Talente zu gewinnen, zu entwickeln und zu binden ist Ihr Kernauftrag — doch Ihr HR-Team verbringt heute bis zu ',
        bqPct: '60 %',
        bqPost: ' seiner Zeit als administrativer Helpdesk, der Routineanfragen und entkoppelte Systeme verwaltet.',
        bqLeadIn: 'Wenn Ihre HR-Profis weiterhin als manuelle Datenverarbeiter:innen agieren — ',
        bqHighlight: 'wie wollen Sie dann die strategischen Bindungs- und Entwicklungsprogramme umsetzen, die der Vorstand erwartet, ohne Ihr HR-Headcount aggressiv zu erweitern?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Dynamics 365 Human Resources.',
        bridge: 'So beantwortet Dynamics 365 Human Resources diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — von der individuellen Mitarbeitendenerfahrung bis hin zur Talentstrategie auf Vorstandsebene.',
        rungs: [
            { title: 'Self-Service, der wirklich funktioniert', audience: 'Ihr HR-Team und Ihre Mitarbeitenden', what: 'Copilot in Microsoft Teams ermöglicht Ihren Mitarbeitenden den Self-Service zu Urlaubssalden, Benefits-Anmeldungen und Routineanfragen — natürlich im Arbeitsfluss.', outcome: 'Sie beseitigen den administrativen Engpass — Mitarbeitende erhalten sofort Antworten und Ihr HR-Team gewinnt die Woche zurück.', kpis: [{ label: '40–50 % weniger Routine-HR-Helpdesk-Tickets', kind: 'efficiency' }, { label: 'Deutlich weniger Stunden manueller Dateneingabe', kind: 'efficiency' }] },
            { title: 'Onboarding, das Tag 1 zählen lässt', audience: 'Ihr Recruiting & HR-Operations', what: 'Automatisierte Workflows orchestrieren den gesamten Mitarbeitenden-Lifecycle — von verschlankten Onboarding-Aufgaben bis zu abteilungsübergreifenden Offboarding-Checklisten.', outcome: 'Sie beschleunigen den Onboarding-Lebenszyklus und bringen neue Talente deutlich schneller in den produktiven Beitrag.', kpis: [{ label: '30 % kürzere Onboarding-Zeit für neue Mitarbeitende', kind: 'efficiency' }, { label: 'Schnellere Time-to-Productivity in neuen Rollen insgesamt', kind: 'efficiency' }] },
            { title: 'Eine vertrauenswürdige Sicht auf Ihre Belegschaft', audience: 'Ihr VP HR / HRIS', what: 'Die Plattform zentralisiert alle Workforce-Daten — Skills, Vergütung, Abwesenheiten, Performance — in einer einzigen sicheren Umgebung, die nativ mit Finance & Operations verbunden ist.', outcome: 'Sie mappen Skill-Lücken in Echtzeit und richten den Headcount direkt an den Unternehmensbudgets aus.', kpis: [{ label: '100 % vereinheitlichte Workforce-Sichtbarkeit', kind: 'efficiency' }, { label: 'Beseitigung manueller Payroll-/HR-Datenabstimmungsfehler', kind: 'efficiency' }] },
            { title: 'Ein Arbeitsplatz, an dem Menschen bleiben', audience: 'Ihre CHRO', what: 'Mitarbeitende erleben einen modernen, reibungslosen Arbeitsplatz, an dem administrative Bedürfnisse sofort erledigt werden, während HR seine Zeit Coaching, Wellness und proaktiver Bindung widmet.', outcome: 'Sie verwandeln HR in einen strategischen Bindungsmotor — heben die Moral und halten Ihre Top-Performer engagiert.', kpis: [{ label: '10–15 % weniger freiwillige Fluktuation', kind: 'outcome' }, { label: 'Höherer Employee Net Promoter Score (eNPS)', kind: 'outcome' }] },
            { title: 'HR als strategischer Geschäftspartner', audience: 'Ihre CHRO, CEO und Vorstand', what: 'HR wandelt sich vom reaktiven, administrativen Cost Center zum strategischen Partner, der Humankapital optimiert und organisatorische Agilität fördert.', outcome: 'Sie senken die operativen HR-Kosten und liefern dem Vorstand die agile, leistungsstarke Workforce-Strategie, die er fordert.', kpis: [{ label: 'Über 130 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Insgesamt niedrigere HR-Administrationskosten pro Mitarbeitendem', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Quelle für die mehr als 130 % ROI, Amortisation in unter 12 Monaten, Reduktion von HR-Helpdesk-Tickets und Verbesserungen bei Bindung und Onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot in Dynamics 365 HR & Microsoft Teams', note: 'Quelle für die Produktivitätsgewinne bei Mitarbeiter-Self-Service, Onboarding-Orchestrierung und Reduktion manueller HR-Administration.' },
        ],
    },
    es: {
        headline: 'Libere a su equipo de RR. HH. del helpdesk — y llévelos a la estrategia de talento.',
        summary: 'Dynamics 365 Human Resources combina Copilot en Microsoft Teams, autoservicio del empleado de extremo a extremo y un modelo unificado de datos de plantilla. El resultado: menos tickets rutinarios, onboarding más rápido y una retención medible más sólida — respaldado por indicadores sectoriales validados de forma independiente.',
        kpis: [
            { value: '130 %+', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '< 12 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '−40–50 %', label: 'Tickets de helpdesk de RR. HH.', kind: 'efficiency' },
            { value: '−30 %', label: 'Tiempo de onboarding de nuevas incorporaciones', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Rotación voluntaria', kind: 'outcome' },
        ],
        bqPre: 'Atraer, desarrollar y retener al mejor talento es su mandato central, pero hoy su equipo de RR. HH. dedica hasta el ',
        bqPct: '60 %',
        bqPost: ' de su tiempo a actuar como un helpdesk administrativo gestionando consultas rutinarias y sistemas desconectados.',
        bqLeadIn: 'Si sus profesionales de RR. HH. siguen actuando como simples procesadores manuales de datos, ',
        bqHighlight: '¿cómo va a ejecutar los programas estratégicos de retención y desarrollo que el consejo espera sin ampliar agresivamente su plantilla de RR. HH.?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Dynamics 365 Human Resources.',
        bridge: 'Así responde Dynamics 365 Human Resources',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde la experiencia individual del empleado hasta la estrategia de talento a nivel de consejo.',
        rungs: [
            { title: 'Un autoservicio que de verdad funciona', audience: 'Su equipo de RR. HH. y sus empleados', what: 'Copilot dentro de Microsoft Teams permite a sus empleados consultar saldos de vacaciones, gestionar la inscripción a beneficios y resolver consultas rutinarias de forma natural, en su flujo de trabajo.', outcome: 'Elimina el cuello de botella administrativo — los empleados obtienen respuestas inmediatas y su equipo de RR. HH. recupera su semana.', kpis: [{ label: '40–50 % menos tickets de helpdesk de RR. HH.', kind: 'efficiency' }, { label: 'Reducción significativa de horas de entrada manual de datos', kind: 'efficiency' }] },
            { title: 'Un onboarding que hace que el día uno cuente', audience: 'Su equipo de talento y operaciones de RR. HH.', what: 'Workflows automatizados orquestan el ciclo de vida completo del empleado — desde tareas de onboarding optimizadas hasta checklists de offboarding interdepartamentales.', outcome: 'Acelera el ciclo de onboarding y consigue que el nuevo talento aporte mucho antes.', kpis: [{ label: '30 % de reducción del tiempo de onboarding de nuevas incorporaciones', kind: 'efficiency' }, { label: 'Menor time-to-productivity global en los nuevos puestos', kind: 'efficiency' }] },
            { title: 'Una visión única y fiable de su plantilla', audience: 'Su VP de RR. HH. / HRIS', what: 'La plataforma centraliza todos los datos de plantilla — skills, retribución, ausencias, desempeño — en un único entorno seguro, conectado de forma nativa con Finanzas y Operaciones.', outcome: 'Mapea las brechas de skills en tiempo real y alinea el headcount directamente con los presupuestos corporativos.', kpis: [{ label: '100 % de visibilidad unificada de la plantilla', kind: 'efficiency' }, { label: 'Erradicación de errores de reconciliación manual de nómina/RR. HH.', kind: 'efficiency' }] },
            { title: 'Un lugar de trabajo en el que la gente se queda', audience: 'Su CHRO', what: 'Los empleados experimentan un lugar de trabajo moderno y sin fricciones donde las necesidades administrativas se resuelven al instante, mientras RR. HH. dedica su tiempo a coaching, bienestar y retención proactiva.', outcome: 'Convierte RR. HH. en un motor estratégico de retención — mejora la moral y mantiene comprometidos a sus mejores profesionales.', kpis: [{ label: '10–15 % de reducción de la rotación voluntaria de empleados', kind: 'outcome' }, { label: 'Mayor Employee Net Promoter Score (eNPS)', kind: 'outcome' }] },
            { title: 'RR. HH. como socio estratégico del negocio', audience: 'Su CHRO, CEO y Consejo de Administración', what: 'RR. HH. pasa de ser un centro de coste administrativo y reactivo a un socio estratégico que optimiza el capital humano para impulsar la agilidad organizativa.', outcome: 'Reduce los costes operativos de RR. HH. y ofrece al consejo la estrategia de plantilla ágil y de alto rendimiento que la realidad exige.', kpis: [{ label: 'Más del 130 % de ROI en 3 años', kind: 'outcome' }, { label: 'Menor coste global de administración de RR. HH. por empleado', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Fuente del ROI superior al 130 %, la amortización en menos de 12 meses, la reducción de tickets de helpdesk y las mejoras en retención y onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot en Dynamics 365 HR y Microsoft Teams', note: 'Fuente de las mejoras de productividad en autoservicio del empleado, orquestación del onboarding y reducción de la administración manual de RR. HH.' },
        ],
    },
    it: {
        headline: 'Libera il team HR dall\'helpdesk — e portalo nella strategia talenti.',
        summary: 'Dynamics 365 Human Resources combina Copilot in Microsoft Teams, self-service end-to-end del dipendente e un modello dati unificato della forza lavoro. Il risultato: meno ticket di routine, onboarding più rapido e una retention misurabilmente più solida — il tutto supportato da benchmark di settore convalidati in modo indipendente.',
        kpis: [
            { value: '130 %+', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '< 12 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '−40–50 %', label: 'Ticket helpdesk HR di routine', kind: 'efficiency' },
            { value: '−30 %', label: 'Tempo di onboarding dei neoassunti', kind: 'efficiency' },
            { value: '−10–15 %', label: 'Turnover volontario', kind: 'outcome' },
        ],
        bqPre: 'Attrarre, sviluppare e trattenere i migliori talenti è il tuo mandato centrale, ma oggi il tuo team HR passa fino al ',
        bqPct: '60 %',
        bqPost: ' del tempo come helpdesk amministrativo, gestendo richieste di routine e sistemi disconnessi.',
        bqLeadIn: 'Se i tuoi professionisti HR continuano a comportarsi come semplici elaboratori manuali di dati, ',
        bqHighlight: 'come eseguirai i programmi strategici di retention e sviluppo che il consiglio si aspetta, senza espandere aggressivamente l\'organico HR?',
        figcaption: 'Domanda strategica che inquadra il business case di Dynamics 365 Human Resources.',
        bridge: 'Ecco come risponde Dynamics 365 Human Resources',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dall\'esperienza del singolo dipendente fino alla strategia talenti a livello di consiglio di amministrazione.',
        rungs: [
            { title: 'Un self-service che funziona davvero', audience: 'Il tuo team HR e i dipendenti', what: 'Copilot dentro Microsoft Teams permette ai dipendenti di consultare saldi ferie, gestire l\'iscrizione ai benefit e risolvere richieste di routine in modo naturale, nel loro flusso di lavoro.', outcome: 'Elimini il collo di bottiglia amministrativo — i dipendenti ottengono risposte immediate e il team HR si riprende la settimana.', kpis: [{ label: '40–50 % di ticket helpdesk HR di routine in meno', kind: 'efficiency' }, { label: 'Significativa riduzione delle ore di data entry manuale', kind: 'efficiency' }] },
            { title: 'Un onboarding che fa contare il primo giorno', audience: 'Talent acquisition e HR operations', what: 'Workflow automatizzati orchestrano l\'intero ciclo di vita del dipendente — dalle attività di onboarding semplificate alle checklist di offboarding tra dipartimenti.', outcome: 'Acceleri il ciclo di onboarding e fai contribuire il nuovo talento molto più rapidamente.', kpis: [{ label: '30 % di riduzione del tempo di onboarding dei neoassunti', kind: 'efficiency' }, { label: 'Time-to-productivity complessivo più rapido per i nuovi ruoli', kind: 'efficiency' }] },
            { title: 'Una vista unica e affidabile della forza lavoro', audience: 'Il tuo VP HR / HRIS', what: 'La piattaforma centralizza tutti i dati della forza lavoro — competenze, retribuzione, assenze, performance — in un unico ambiente sicuro, nativamente connesso a Finance e Operations.', outcome: 'Mappi gli skill gap in tempo reale e allinei l\'organico direttamente ai budget aziendali.', kpis: [{ label: '100 % di visibilità unificata sulla forza lavoro', kind: 'efficiency' }, { label: 'Eradicazione degli errori di riconciliazione manuale tra payroll e HR', kind: 'efficiency' }] },
            { title: 'Un posto di lavoro in cui le persone restano', audience: 'Il tuo CHRO', what: 'I dipendenti vivono un workplace moderno e senza attriti, dove le esigenze amministrative sono gestite all\'istante, mentre l\'HR dedica tempo a coaching, benessere e retention proattiva.', outcome: 'Trasformi l\'HR in un motore strategico di retention — alzando il morale e mantenendo ingaggiati i top performer.', kpis: [{ label: '10–15 % di riduzione del turnover volontario', kind: 'outcome' }, { label: 'Employee Net Promoter Score (eNPS) più alto', kind: 'outcome' }] },
            { title: 'L\'HR come partner strategico del business', audience: 'Il tuo CHRO, CEO e Consiglio di Amministrazione', what: 'L\'HR passa da centro di costo amministrativo e reattivo a partner strategico che ottimizza il capitale umano per favorire l\'agilità organizzativa.', outcome: 'Abbassi i costi operativi HR e offri al consiglio la strategia di forza lavoro agile e ad alte prestazioni che il mercato richiede.', kpis: [{ label: 'Oltre 130 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Costo complessivo di amministrazione HR per dipendente più basso', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Fonte del ROI superiore al 130 %, del rientro in meno di 12 mesi, della riduzione dei ticket helpdesk HR e dei miglioramenti in retention e onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot in Dynamics 365 HR e Microsoft Teams', note: 'Fonte dei guadagni di produttività su self-service del dipendente, orchestrazione dell\'onboarding e riduzione dell\'amministrazione manuale HR.' },
        ],
    },
    ar: {
        headline: 'حرّر فريق الموارد البشرية لديك من مكتب المساعدة — وأطلِقه نحو استراتيجية المواهب.',
        summary: 'يجمع Dynamics 365 Human Resources بين Copilot في Microsoft Teams، والخدمة الذاتية الكاملة للموظف، ونموذج بيانات موحَّد للقوى العاملة. والنتيجة: تذاكر روتينية أقل، وتسريع للتأهيل، واحتفاظ أقوى وقابل للقياس — مدعوم بمؤشرات قطاعية موثَّقة من جهات مستقلة.',
        kpis: [
            { value: '130٪+', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: 'أقل من 12 شهراً', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '−40–50٪', label: 'تذاكر مكتب مساعدة الموارد البشرية الروتينية', kind: 'efficiency' },
            { value: '−30٪', label: 'زمن تأهيل الموظفين الجدد', kind: 'efficiency' },
            { value: '−10–15٪', label: 'الاستقالات الطوعية', kind: 'outcome' },
        ],
        bqPre: 'استقطاب أفضل المواهب وتطويرها والاحتفاظ بها هو مهمتك الجوهرية، لكن فريق الموارد البشرية لديك يُمضي اليوم حتى ',
        bqPct: '60٪',
        bqPost: ' من وقته بوصفه مكتب مساعدة إداري يُدير استفسارات روتينية وأنظمة منفصلة.',
        bqLeadIn: 'إذا واصل اختصاصيو الموارد البشرية لديك العمل كمعالِجي بيانات يدويين، ',
        bqHighlight: 'فكيف ستُنفّذ برامج الاحتفاظ والتطوير الاستراتيجية التي يتوقّعها مجلس الإدارة دون توسيع عدد موظفي الموارد البشرية بشكل عدواني؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Dynamics 365 Human Resources.',
        bridge: 'إليك كيف يجيب Dynamics 365 Human Resources عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من تجربة الموظف الفردية وصولاً إلى استراتيجية المواهب على مستوى مجلس الإدارة.',
        rungs: [
            { title: 'خدمة ذاتية تعمل فعلاً', audience: 'فريق الموارد البشرية والموظفون لديك', what: 'يُتيح Copilot داخل Microsoft Teams لموظفيك الاطلاع ذاتياً على أرصدة الإجازات، والتسجيل في المزايا، والإجابة عن الاستفسارات الروتينية بشكل طبيعي ضمن سير عملهم.', outcome: 'تُزيل عنق الزجاجة الإداري — يحصل الموظفون على إجابات فورية، ويستعيد فريق الموارد البشرية أسبوعه.', kpis: [{ label: 'انخفاض 40–50٪ في تذاكر مكتب مساعدة الموارد البشرية الروتينية', kind: 'efficiency' }, { label: 'انخفاض ملموس في ساعات إدخال البيانات اليدوي', kind: 'efficiency' }] },
            { title: 'تأهيل يجعل اليوم الأول مهمّاً', audience: 'فريق الاستقطاب وعمليات الموارد البشرية لديك', what: 'تُنظّم سير عمل مُؤتمَت دورة حياة الموظف بالكامل — من مهام تأهيل مُبسّطة إلى قوائم إنهاء الخدمة عبر الإدارات.', outcome: 'تُسرّع دورة التأهيل وتجعل المواهب الجديدة تُساهم بشكل أسرع بكثير.', kpis: [{ label: 'انخفاض 30٪ في زمن تأهيل الموظفين الجدد', kind: 'efficiency' }, { label: 'تسريع الزمن اللازم لتحقيق الإنتاجية في الأدوار الجديدة', kind: 'efficiency' }] },
            { title: 'رؤية واحدة موثوقة لقواك العاملة', audience: 'نائب رئيس الموارد البشرية / HRIS لديك', what: 'تُمركز المنصة جميع بيانات القوى العاملة — المهارات والتعويضات والإجازات والأداء — في بيئة واحدة آمنة مرتبطة أصلاً بـ Finance and Operations.', outcome: 'تُحدّد فجوات المهارات آنياً وتُواءم العدد الإجمالي للموظفين مباشرةً مع الموازنات المؤسسية.', kpis: [{ label: 'رؤية موحَّدة بنسبة 100٪ على القوى العاملة', kind: 'efficiency' }, { label: 'القضاء على أخطاء التوفيق اليدوي بين الرواتب وبيانات الموارد البشرية', kind: 'efficiency' }] },
            { title: 'مكان عمل يبقى فيه الناس', audience: 'الرئيس التنفيذي للموارد البشرية (CHRO) لديك', what: 'يعيش الموظفون مكان عمل عصرياً وخالياً من الاحتكاك تُعالَج فيه الاحتياجات الإدارية فوراً، فيما تُكرّس الموارد البشرية وقتها للتدريب والعافية والاحتفاظ الاستباقي.', outcome: 'تُحوّل الموارد البشرية إلى محرّك احتفاظ استراتيجي — يرفع المعنويات ويُبقي أفضل الكفاءات منخرطة.', kpis: [{ label: 'انخفاض 10–15٪ في الاستقالات الطوعية', kind: 'outcome' }, { label: 'مؤشر صافي توصية الموظف (eNPS) أعلى', kind: 'outcome' }] },
            { title: 'الموارد البشرية شريك أعمال استراتيجي', audience: 'CHRO والرئيس التنفيذي ومجلس الإدارة لديك', what: 'تتحوّل الموارد البشرية من مركز تكلفة إداري وتفاعلي إلى شريك استراتيجي يُحسِّن رأس المال البشري لتعزيز مرونة المنظمة.', outcome: 'تُخفّض التكاليف التشغيلية للموارد البشرية وتُقدّم لمجلس الإدارة استراتيجية القوى العاملة المرنة وعالية الأداء التي يحتاجها.', kpis: [{ label: 'عائد على الاستثمار يفوق 130٪ خلال 3 سنوات', kind: 'outcome' }, { label: 'انخفاض إجمالي تكلفة إدارة الموارد البشرية لكل موظف', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'مصدر العائد على الاستثمار البالغ أكثر من 130٪، واسترداد رأس المال في أقل من 12 شهراً، وانخفاض تذاكر مكتب مساعدة الموارد البشرية، وتحسّن الاحتفاظ والتأهيل.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot in Dynamics 365 HR & Microsoft Teams', note: 'مصدر مكاسب الإنتاجية في الخدمة الذاتية للموظف، وتنسيق التأهيل، وتقليل العمل الإداري اليدوي للموارد البشرية.' },
        ],
    },
    nl: {
        headline: 'Bevrijd uw HR-team van de helpdesk — en richt het op de talentstrategie.',
        summary: 'Dynamics 365 Human Resources combineert Copilot in Microsoft Teams, end-to-end medewerker-self-service en een geünificeerd workforce-datamodel. Het resultaat: minder routinetickets, sneller onboarden en een meetbaar sterkere retentie — onderbouwd met onafhankelijk gevalideerde sectorbenchmarks.',
        kpis: [
            { value: '130%+', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '< 12 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '−40–50%', label: 'Routinematige HR-helpdesktickets', kind: 'efficiency' },
            { value: '−30%', label: 'Onboarding-tijd nieuwe medewerkers', kind: 'efficiency' },
            { value: '−10–15%', label: 'Vrijwillig verloop', kind: 'outcome' },
        ],
        bqPre: 'Het aantrekken, ontwikkelen en behouden van toptalent is uw kernopdracht, maar vandaag besteedt uw HR-team tot ',
        bqPct: '60%',
        bqPost: ' van zijn tijd als administratieve helpdesk die routinevragen en losse systemen beheert.',
        bqLeadIn: 'Als uw HR-professionals zich blijven gedragen als handmatige dataverwerkers, ',
        bqHighlight: 'hoe gaat u dan de strategische retentie- en ontwikkelprogramma\'s uitvoeren die de Raad van Bestuur verwacht zonder uw HR-headcount agressief uit te breiden?',
        figcaption: 'Strategische vraag die de businesscase voor Dynamics 365 Human Resources kadert.',
        bridge: 'Zo beantwoordt Dynamics 365 Human Resources die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de individuele medewerker-experience tot aan de talentstrategie op bestuursniveau.',
        rungs: [
            { title: 'Self-service die echt werkt', audience: 'Uw HR-team en medewerkers', what: 'Copilot in Microsoft Teams laat uw medewerkers verlofsaldi, benefits-inschrijvingen en routinevragen zelf afhandelen, natuurlijk in hun workflow.', outcome: 'U verwijdert het administratieve knelpunt — medewerkers krijgen direct antwoord en uw HR-team krijgt de week terug.', kpis: [{ label: '40–50% minder routinematige HR-helpdesktickets', kind: 'efficiency' }, { label: 'Significante reductie van handmatige data-entry-uren', kind: 'efficiency' }] },
            { title: 'Onboarding die dag één laat tellen', audience: 'Uw recruitment- en HR-operationsteams', what: 'Geautomatiseerde workflows orkestreren de volledige medewerker-lifecycle — van gestroomlijnde onboarding-taken tot afdelingsoverstijgende offboarding-checklists.', outcome: 'U versnelt de onboarding-cyclus en laat nieuw talent veel sneller bijdragen.', kpis: [{ label: '30% minder onboarding-tijd voor nieuwe medewerkers', kind: 'efficiency' }, { label: 'Snellere algehele time-to-productivity in nieuwe rollen', kind: 'efficiency' }] },
            { title: 'Eén betrouwbaar beeld van uw workforce', audience: 'Uw VP HR / HRIS', what: 'Het platform centraliseert alle workforce-data — skills, beloning, verzuim, performance — in één veilige omgeving die native koppelt met Finance en Operations.', outcome: 'U brengt skill gaps realtime in kaart en stemt headcount direct af op corporate budgetten.', kpis: [{ label: '100% geünificeerd workforce-inzicht', kind: 'efficiency' }, { label: 'Uitbanning van handmatige reconciliatiefouten tussen payroll en HR', kind: 'efficiency' }] },
            { title: 'Een werkplek waar mensen blijven', audience: 'Uw CHRO', what: 'Medewerkers ervaren een moderne, frictieloze werkplek waar administratieve behoeften direct worden afgehandeld, terwijl HR zijn tijd besteedt aan coaching, welzijn en proactieve retentie.', outcome: 'U maakt van HR een strategische retentiemotor — verhoogt het moreel en houdt uw top performers betrokken.', kpis: [{ label: '10–15% minder vrijwillig medewerkerverloop', kind: 'outcome' }, { label: 'Hogere Employee Net Promoter Score (eNPS)', kind: 'outcome' }] },
            { title: 'HR als strategische businesspartner', audience: 'Uw CHRO, CEO en Raad van Bestuur', what: 'HR verandert van een reactief, administratief kostencentrum in een strategische partner die menselijk kapitaal optimaliseert voor organisatorische wendbaarheid.', outcome: 'U verlaagt operationele HR-kosten en biedt de Raad van Bestuur de wendbare, hoog presterende workforce-strategie die de markt eist.', kpis: [{ label: 'Meer dan 130% ROI over 3 jaar', kind: 'outcome' }, { label: 'Lagere totale HR-administratiekosten per medewerker', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Dynamics 365 Human Resources', note: 'Bron voor de meer dan 130% ROI, terugverdientijd van minder dan 12 maanden, reductie van HR-helpdesktickets en verbetering in retentie en onboarding.' },
            { title: 'Microsoft Workforce Benchmarks — Copilot in Dynamics 365 HR en Microsoft Teams', note: 'Bron voor de productiviteitsverbeteringen in medewerker-self-service, onboarding-orkestratie en reductie van handmatige HR-administratie.' },
        ],
    },
};

export default function BusinessValueHumanResources({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
