import React from 'react';
import BusinessValueView from './BusinessValueView.jsx';

const STRINGS = {
    en: {
        headline: 'Clear the backlog. Retire the spreadsheets.',
        summary: 'Power Apps democratizes application development. Citizen developers ship custom apps rapidly with AI Copilot, pro devs accelerate complex deployments, and IT keeps centralized governance over everything that gets built — so you can finally retire paper, Excel, and expensive shadow-IT SaaS.',
        kpis: [
            { value: '140%+', label: 'ROI over 3 years', kind: 'outcome' },
            { value: '< 6 mo', label: 'Payback period', kind: 'outcome' },
            { value: '−74%', label: 'App development costs', kind: 'efficiency' },
            { value: 'Weeks vs months', label: 'Time-to-market for internal tools', kind: 'efficiency' },
            { value: '↓ shadow IT', label: '100% IT visibility & governance', kind: 'outcome' },
        ],
        bqPre: 'Digitizing operations to drive efficiency is your core mandate, but currently, an 18-month IT backlog is forcing business units to rely on fragmented spreadsheets and expensive shadow IT.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'If your IT team lacks the developer capacity to address this backlog, ',
        bqHighlight: 'how will you digitize the enterprise and retire legacy tech debt without compromising security or inflating your budget?',
        figcaption: 'Strategic question framing the business case for Microsoft Power Apps.',
        bridge: 'Here is how Power Apps answers it',
        outcomesIntro: 'Each step compounds the value of the previous one — from the citizen developer shipping their first app all the way up to enterprise-wide digital strategy.',
        rungs: [
            { title: 'Anyone can build the app they need', audience: 'Your citizen developers & pro devs', what: 'Business users build with intuitive drag-and-drop and AI Copilot, while pro devs use the same platform to rapidly scaffold complex solutions and integrate legacy APIs.', outcome: 'You bypass the pro-code bottleneck and empower the business to digitize its own manual data entry and paper processes.', kpis: [{ label: '74% reduction in app development costs', kind: 'outcome' }, { label: 'Thousands of hours saved by frontline workers digitizing paper tasks', kind: 'efficiency' }] },
            { title: 'Clear the IT backlog', audience: 'Your IT directors & PMO', what: 'Solutions that previously required 6–9 months of traditional SDLC are now designed, built, and deployed in weeks — or days.', outcome: 'You move at the speed of the market, delivering critical operational tools to the business in weeks rather than months.', kpis: [{ label: 'Weeks instead of months for app delivery', kind: 'efficiency' }, { label: '50%+ reduction in time-to-market for internal tooling', kind: 'efficiency' }] },
            { title: 'Decentralized building, centralized control', audience: 'Your CISO & enterprise architecture', what: 'Apps are built on Dataverse with strict, IT-administered role-based access, Data Loss Prevention policies, and unified Application Lifecycle Management.', outcome: 'You safely decentralize development while maintaining absolute centralized control — eradicating shadow IT and data leakage.', kpis: [{ label: '100% IT visibility over all custom applications', kind: 'efficiency' }, { label: 'Zero unmanaged rogue applications', kind: 'outcome' }] },
            { title: 'Retire legacy SaaS, fix the frontline', audience: 'Your COO & line-of-business leaders', what: 'Frontline workers capture clean data instantly via mobile apps, while IT replaces expensive niche SaaS tools with low-code internal apps that do the same job — without the recurring license fees.', outcome: 'You reduce operational errors, accelerate frontline workflows, and systematically retire expensive legacy software.', kpis: [{ label: 'Significant reduction in 3rd-party SaaS licensing costs', kind: 'outcome' }, { label: 'Measurable reduction in operational data-entry errors', kind: 'outcome' }] },
            { title: 'A digital-first operating model', audience: 'Your CIO, CEO & Board', what: 'The enterprise shifts from a slow, legacy-bound architecture into a highly agile, digital-first culture capable of rapid innovation at scale.', outcome: 'You lower TCO for internal tooling and build a truly agile, digital-first enterprise — with the ROI to back it up.', kpis: [{ label: '140%+ ROI over 3 years', kind: 'outcome' }, { label: 'Payback in less than 6 months', kind: 'outcome' }, { label: 'Increased overall enterprise digital agility', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Source for the 140%+ ROI, the 74% reduction in application development costs, and the financial savings from retiring legacy third-party applications and avoiding pro-developer hires.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Source for the dramatic reduction in time-to-market — from months to weeks — and the frontline productivity gains achieved by replacing paper and Excel with mobile Power Apps.' },
        ],
    },
    fr: {
        headline: 'Videz le backlog. Mettez les tableurs à la retraite.',
        summary: 'Power Apps démocratise le développement d\'applications. Les citizen developers livrent rapidement des applications sur mesure avec l\'IA Copilot, les pro devs accélèrent les déploiements complexes, et l\'IT conserve une gouvernance centralisée sur tout ce qui est construit — pour vous permettre enfin de mettre au rebut le papier, Excel et les outils SaaS coûteux du shadow IT.',
        kpis: [
            { value: '140 %+', label: 'ROI sur 3 ans', kind: 'outcome' },
            { value: '< 6 mois', label: 'Délai de rentabilité', kind: 'outcome' },
            { value: '−74 %', label: 'Coûts de développement applicatif', kind: 'efficiency' },
            { value: 'Semaines vs mois', label: 'Time-to-market des outils internes', kind: 'efficiency' },
            { value: '↓ shadow IT', label: '100 % de visibilité et de gouvernance IT', kind: 'outcome' },
        ],
        bqPre: 'Digitaliser les opérations pour gagner en efficacité est votre mission centrale, mais aujourd\'hui un backlog IT de 18 mois oblige les directions métier à s\'appuyer sur des tableurs fragmentés et un shadow IT coûteux.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si votre équipe IT n\'a pas la capacité de développement nécessaire pour traiter ce backlog, ',
        bqHighlight: 'comment ferez-vous pour digitaliser l\'entreprise et résorber la dette technique sans compromettre la sécurité ni gonfler votre budget ?',
        figcaption: 'Question stratégique cadrant l\'analyse de valeur de Microsoft Power Apps.',
        bridge: 'Voici comment Power Apps y répond',
        outcomesIntro: 'Chaque étape démultiplie la valeur de la précédente — du citizen developer qui livre sa première app jusqu\'à la stratégie digitale à l\'échelle de l\'entreprise.',
        rungs: [
            { title: 'Tout le monde peut construire l\'app dont il a besoin', audience: 'Vos citizen developers et pro devs', what: 'Les utilisateurs métier construisent avec un drag-and-drop intuitif et l\'IA Copilot, pendant que les pro devs s\'appuient sur la même plateforme pour échafauder rapidement des solutions complexes et intégrer des API legacy.', outcome: 'Vous contournez le goulet d\'étranglement du pro-code et donnez au métier les moyens de digitaliser sa propre saisie manuelle et ses processus papier.', kpis: [{ label: '74 % de réduction des coûts de développement applicatif', kind: 'outcome' }, { label: 'Des milliers d\'heures gagnées par les opérationnels en digitalisant les tâches papier', kind: 'efficiency' }] },
            { title: 'Videz le backlog IT', audience: 'Vos directeurs IT et PMO', what: 'Des solutions qui exigeaient auparavant 6 à 9 mois de SDLC traditionnel sont désormais conçues, construites et déployées en quelques semaines — voire en jours.', outcome: 'Vous avancez à la vitesse du marché, en livrant au métier des outils opérationnels critiques en semaines plutôt qu\'en mois.', kpis: [{ label: 'Semaines au lieu de mois pour livrer une application', kind: 'efficiency' }, { label: 'Plus de 50 % de réduction du time-to-market pour l\'outillage interne', kind: 'efficiency' }] },
            { title: 'Construction décentralisée, contrôle centralisé', audience: 'Votre RSSI et l\'architecture d\'entreprise', what: 'Les applications sont construites sur Dataverse avec des accès basés sur les rôles administrés strictement par l\'IT, des politiques DLP (Data Loss Prevention) et un Application Lifecycle Management unifié.', outcome: 'Vous décentralisez le développement en toute sécurité tout en conservant un contrôle central absolu — en éradiquant le shadow IT et les fuites de données.', kpis: [{ label: '100 % de visibilité IT sur l\'ensemble des applications custom', kind: 'efficiency' }, { label: 'Zéro application sauvage non gérée', kind: 'outcome' }] },
            { title: 'Mettez au rebut le SaaS legacy, corrigez le terrain', audience: 'Votre COO et les directions métier', what: 'Les opérationnels capturent instantanément des données propres via des apps mobiles, pendant que l\'IT remplace les outils SaaS de niche coûteux par des apps low-code internes qui font le même travail — sans les redevances récurrentes.', outcome: 'Vous réduisez les erreurs opérationnelles, accélérez les workflows terrain et mettez systématiquement au rebut des logiciels legacy onéreux.', kpis: [{ label: 'Réduction significative des coûts de licences SaaS tierces', kind: 'outcome' }, { label: 'Réduction mesurable des erreurs de saisie opérationnelles', kind: 'outcome' }] },
            { title: 'Un modèle opérationnel digital-first', audience: 'Votre CIO, PDG et conseil d\'administration', what: 'L\'entreprise passe d\'une architecture lente, prisonnière du legacy, à une culture digital-first hautement agile, capable d\'innover rapidement à l\'échelle.', outcome: 'Vous baissez le TCO de l\'outillage interne et bâtissez une entreprise réellement agile et digital-first — avec le ROI qui va avec.', kpis: [{ label: 'Plus de 140 % de ROI sur 3 ans', kind: 'outcome' }, { label: 'Rentabilisation en moins de 6 mois', kind: 'outcome' }, { label: 'Agilité digitale globale de l\'entreprise renforcée', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Source du ROI de plus de 140 %, des 74 % de réduction des coûts de développement et des économies financières issues de la mise au rebut d\'applications tierces legacy et de l\'évitement de recrutements pro-dev.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Source de la réduction spectaculaire du time-to-market — de mois à semaines — et des gains de productivité terrain obtenus en remplaçant le papier et Excel par des Power Apps mobiles.' },
        ],
    },
    de: {
        headline: 'Räumen Sie das Backlog ab. Schicken Sie die Tabellen in den Ruhestand.',
        summary: 'Power Apps demokratisiert die Anwendungsentwicklung. Citizen Developer liefern mit AI Copilot schnell individuelle Apps aus, Pro Devs beschleunigen komplexe Deployments, und die IT behält die zentrale Governance über alles, was gebaut wird — damit Sie endlich Papier, Excel und teures Shadow-IT-SaaS in den Ruhestand schicken können.',
        kpis: [
            { value: '140 %+', label: 'ROI über 3 Jahre', kind: 'outcome' },
            { value: '< 6 Mon.', label: 'Amortisationszeit', kind: 'outcome' },
            { value: '−74 %', label: 'App-Entwicklungskosten', kind: 'efficiency' },
            { value: 'Wochen statt Monate', label: 'Time-to-Market interner Tools', kind: 'efficiency' },
            { value: '↓ Shadow IT', label: '100 % IT-Sichtbarkeit & Governance', kind: 'outcome' },
        ],
        bqPre: 'Operations zu digitalisieren und Effizienz zu treiben ist Ihr Kernauftrag — doch ein 18-monatiges IT-Backlog zwingt die Fachbereiche heute auf fragmentierte Tabellen und teure Shadow IT zurückzugreifen.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Wenn Ihrem IT-Team die Entwickler-Kapazität fehlt, dieses Backlog abzubauen — ',
        bqHighlight: 'wie wollen Sie dann das Unternehmen digitalisieren und Legacy-Tech-Debt abbauen, ohne die Sicherheit zu gefährden oder Ihr Budget aufzublähen?',
        figcaption: 'Strategische Frage als Rahmen für den Business Case von Microsoft Power Apps.',
        bridge: 'So beantwortet Power Apps diese Frage',
        outcomesIntro: 'Jede Stufe baut auf der vorhergehenden auf — vom Citizen Developer, der seine erste App ausliefert, bis hin zur unternehmensweiten Digitalstrategie.',
        rungs: [
            { title: 'Jede:r kann die App bauen, die sie braucht', audience: 'Ihre Citizen Developer und Pro Devs', what: 'Business-Anwender:innen bauen mit intuitivem Drag-and-Drop und AI Copilot, während Pro Devs auf derselben Plattform schnell komplexe Lösungen scaffolden und Legacy-APIs integrieren.', outcome: 'Sie umgehen den Pro-Code-Engpass und befähigen den Fachbereich, seine eigene manuelle Dateneingabe und Papierprozesse zu digitalisieren.', kpis: [{ label: '74 % geringere App-Entwicklungskosten', kind: 'outcome' }, { label: 'Tausende Stunden, die Frontline-Mitarbeitende durch die Digitalisierung von Papierarbeit einsparen', kind: 'efficiency' }] },
            { title: 'Räumen Sie das IT-Backlog ab', audience: 'Ihre IT-Direktion und PMO', what: 'Lösungen, die früher 6–9 Monate klassischen SDLC erforderten, werden jetzt in Wochen — oder Tagen — entworfen, gebaut und ausgeliefert.', outcome: 'Sie bewegen sich im Tempo des Marktes und liefern dem Fachbereich kritische operative Tools in Wochen statt Monaten.', kpis: [{ label: 'Wochen statt Monate für die App-Auslieferung', kind: 'efficiency' }, { label: 'Über 50 % kürzere Time-to-Market für interne Tools', kind: 'efficiency' }] },
            { title: 'Dezentral bauen, zentral kontrollieren', audience: 'Ihre CISO und Enterprise Architecture', what: 'Apps werden auf Dataverse gebaut — mit strikten, IT-administrierten rollenbasierten Berechtigungen, Data-Loss-Prevention-Policies und einheitlichem Application Lifecycle Management.', outcome: 'Sie dezentralisieren die Entwicklung sicher und behalten gleichzeitig die absolute zentrale Kontrolle — Shadow IT und Datenabflüsse werden eliminiert.', kpis: [{ label: '100 % IT-Sichtbarkeit über alle individuellen Anwendungen', kind: 'efficiency' }, { label: 'Null ungemanagete Rogue-Anwendungen', kind: 'outcome' }] },
            { title: 'Legacy-SaaS aussortieren, die Frontline reparieren', audience: 'Ihre COO und Bereichsverantwortlichen', what: 'Frontline-Mitarbeitende erfassen über mobile Apps sofort saubere Daten, während die IT teure Nischen-SaaS-Tools durch interne Low-Code-Apps ersetzt, die denselben Job ohne wiederkehrende Lizenzgebühren erledigen.', outcome: 'Sie reduzieren operative Fehler, beschleunigen Frontline-Workflows und sortieren systematisch teure Legacy-Software aus.', kpis: [{ label: 'Deutliche Senkung der SaaS-Lizenzkosten von Drittanbietern', kind: 'outcome' }, { label: 'Messbare Reduktion operativer Dateneingabefehler', kind: 'outcome' }] },
            { title: 'Ein Digital-First-Betriebsmodell', audience: 'Ihre CIO, CEO und Vorstand', what: 'Das Unternehmen entwickelt sich von einer langsamen, an Legacy gebundenen Architektur zu einer hochagilen, Digital-First-Kultur, die schnelle Innovation in der Breite ermöglicht.', outcome: 'Sie senken die TCO für interne Tools und bauen ein wirklich agiles, Digital-First-Unternehmen — mit dem ROI, der das untermauert.', kpis: [{ label: 'Über 140 % ROI über 3 Jahre', kind: 'outcome' }, { label: 'Amortisation in unter 6 Monaten', kind: 'outcome' }, { label: 'Insgesamt höhere digitale Agilität des Unternehmens', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Quelle für den ROI von über 140 %, die 74 % geringeren App-Entwicklungskosten und die finanziellen Einsparungen aus dem Aussortieren von Legacy-Drittanbieter-Anwendungen sowie vermiedenen Pro-Developer-Einstellungen.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Quelle für die drastische Verkürzung der Time-to-Market — von Monaten auf Wochen — und für die Frontline-Produktivitätsgewinne durch den Ersatz von Papier und Excel durch mobile Power Apps.' },
        ],
    },
    es: {
        headline: 'Vacíe el backlog. Jubile las hojas de cálculo.',
        summary: 'Power Apps democratiza el desarrollo de aplicaciones. Los citizen developers entregan rápidamente apps a medida con la IA Copilot, los pro devs aceleran despliegues complejos y TI mantiene una gobernanza centralizada sobre todo lo que se construye — para que por fin pueda jubilar el papel, Excel y costosos SaaS de shadow IT.',
        kpis: [
            { value: '140 %+', label: 'ROI en 3 años', kind: 'outcome' },
            { value: '< 6 meses', label: 'Plazo de amortización', kind: 'outcome' },
            { value: '−74 %', label: 'Costes de desarrollo de apps', kind: 'efficiency' },
            { value: 'Semanas vs meses', label: 'Time-to-market de herramientas internas', kind: 'efficiency' },
            { value: '↓ shadow IT', label: '100 % de visibilidad y gobernanza de TI', kind: 'outcome' },
        ],
        bqPre: 'Digitalizar las operaciones para impulsar la eficiencia es su mandato central, pero hoy un backlog de TI de 18 meses obliga a las unidades de negocio a depender de hojas de cálculo fragmentadas y de un costoso shadow IT.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Si su equipo de TI no tiene capacidad de desarrollo para atender ese backlog, ',
        bqHighlight: '¿cómo va a digitalizar la empresa y reducir la deuda técnica heredada sin comprometer la seguridad ni inflar su presupuesto?',
        figcaption: 'Pregunta estratégica que enmarca el caso de negocio de Microsoft Power Apps.',
        bridge: 'Así responde Power Apps',
        outcomesIntro: 'Cada paso multiplica el valor del anterior — desde el citizen developer que publica su primera app hasta la estrategia digital a nivel de toda la empresa.',
        rungs: [
            { title: 'Cualquiera puede construir la app que necesita', audience: 'Sus citizen developers y pro devs', what: 'Los usuarios de negocio construyen con un drag-and-drop intuitivo y la IA Copilot, mientras los pro devs usan la misma plataforma para esqueletar rápidamente soluciones complejas e integrar APIs heredadas.', outcome: 'Salta el cuello de botella del pro-code y permite al negocio digitalizar su propia entrada manual de datos y procesos en papel.', kpis: [{ label: '74 % de reducción de los costes de desarrollo de aplicaciones', kind: 'outcome' }, { label: 'Miles de horas ahorradas por los trabajadores de primera línea al digitalizar tareas en papel', kind: 'efficiency' }] },
            { title: 'Vacíe el backlog de TI', audience: 'Sus directores de TI y PMO', what: 'Soluciones que antes requerían 6–9 meses de SDLC tradicional ahora se diseñan, construyen y despliegan en semanas — o días.', outcome: 'Avanza al ritmo del mercado, entregando al negocio herramientas operativas críticas en semanas en vez de meses.', kpis: [{ label: 'Semanas en lugar de meses para entregar una app', kind: 'efficiency' }, { label: 'Más del 50 % de reducción del time-to-market para herramientas internas', kind: 'efficiency' }] },
            { title: 'Construcción descentralizada, control centralizado', audience: 'Su CISO y arquitectura empresarial', what: 'Las apps se construyen sobre Dataverse con accesos basados en roles administrados estrictamente por TI, políticas de Data Loss Prevention y un Application Lifecycle Management unificado.', outcome: 'Descentraliza el desarrollo de forma segura mientras mantiene un control central absoluto — erradicando el shadow IT y la fuga de datos.', kpis: [{ label: '100 % de visibilidad de TI sobre todas las aplicaciones a medida', kind: 'efficiency' }, { label: 'Cero aplicaciones rogue no gestionadas', kind: 'outcome' }] },
            { title: 'Jubile el SaaS heredado, arregle la primera línea', audience: 'Su COO y responsables de negocio', what: 'Los trabajadores de primera línea capturan datos limpios al instante mediante apps móviles, mientras TI sustituye costosas herramientas SaaS de nicho por apps internas low-code que hacen el mismo trabajo — sin las cuotas recurrentes de licencia.', outcome: 'Reduce los errores operativos, acelera los workflows de primera línea y jubila sistemáticamente software heredado caro.', kpis: [{ label: 'Reducción significativa de los costes de licencias SaaS de terceros', kind: 'outcome' }, { label: 'Reducción medible de los errores de entrada de datos operativos', kind: 'outcome' }] },
            { title: 'Un modelo operativo digital-first', audience: 'Su CIO, CEO y Consejo', what: 'La empresa pasa de una arquitectura lenta y atada al legado a una cultura digital-first altamente ágil, capaz de innovar rápidamente y a escala.', outcome: 'Reduce el TCO de la herramienta interna y construye una empresa verdaderamente ágil y digital-first — con el ROI que lo respalda.', kpis: [{ label: 'Más del 140 % de ROI en 3 años', kind: 'outcome' }, { label: 'Amortización en menos de 6 meses', kind: 'outcome' }, { label: 'Mayor agilidad digital global de la empresa', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Fuente del ROI superior al 140 %, de la reducción del 74 % de los costes de desarrollo de aplicaciones y de los ahorros financieros derivados de jubilar aplicaciones de terceros heredadas y evitar contrataciones de pro-developer.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Fuente de la drástica reducción del time-to-market — de meses a semanas — y de las mejoras de productividad en primera línea al sustituir papel y Excel por Power Apps móviles.' },
        ],
    },
    it: {
        headline: 'Svuota il backlog. Manda in pensione i fogli di calcolo.',
        summary: 'Power Apps democratizza lo sviluppo applicativo. I citizen developer rilasciano rapidamente app personalizzate con l\'AI Copilot, i pro dev accelerano i deployment complessi e l\'IT mantiene una governance centralizzata su tutto ciò che viene costruito — così puoi finalmente mandare in pensione carta, Excel e costosi SaaS di shadow IT.',
        kpis: [
            { value: '140 %+', label: 'ROI in 3 anni', kind: 'outcome' },
            { value: '< 6 mesi', label: 'Tempo di rientro', kind: 'outcome' },
            { value: '−74 %', label: 'Costi di sviluppo applicativo', kind: 'efficiency' },
            { value: 'Settimane vs mesi', label: 'Time-to-market degli strumenti interni', kind: 'efficiency' },
            { value: '↓ shadow IT', label: '100 % di visibilità e governance IT', kind: 'outcome' },
        ],
        bqPre: 'Digitalizzare le operazioni per generare efficienza è il tuo mandato centrale, ma oggi un backlog IT di 18 mesi costringe le business unit a fare affidamento su fogli di calcolo frammentati e su un costoso shadow IT.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Se il tuo team IT non ha la capacità di sviluppo per smaltire questo backlog, ',
        bqHighlight: 'come farai a digitalizzare l\'azienda e a smaltire il debito tecnico legacy senza compromettere la sicurezza o gonfiare il budget?',
        figcaption: 'Domanda strategica che inquadra il business case di Microsoft Power Apps.',
        bridge: 'Ecco come risponde Power Apps',
        outcomesIntro: 'Ogni livello amplifica il valore del precedente — dal citizen developer che rilascia la sua prima app fino alla strategia digitale a livello di intera azienda.',
        rungs: [
            { title: 'Chiunque può costruire l\'app che gli serve', audience: 'I tuoi citizen developer e pro dev', what: 'Gli utenti business costruiscono con un drag-and-drop intuitivo e l\'AI Copilot, mentre i pro dev usano la stessa piattaforma per scaffoldare rapidamente soluzioni complesse e integrare API legacy.', outcome: 'Aggiri il collo di bottiglia del pro-code e dai al business gli strumenti per digitalizzare il proprio data entry manuale e i processi cartacei.', kpis: [{ label: '74 % di riduzione dei costi di sviluppo applicativo', kind: 'outcome' }, { label: 'Migliaia di ore risparmiate dai lavoratori in prima linea digitalizzando attività cartacee', kind: 'efficiency' }] },
            { title: 'Svuota il backlog IT', audience: 'I tuoi direttori IT e PMO', what: 'Soluzioni che prima richiedevano 6–9 mesi di SDLC tradizionale vengono ora progettate, costruite e rilasciate in settimane — o giorni.', outcome: 'Ti muovi alla velocità del mercato, consegnando al business strumenti operativi critici in settimane anziché mesi.', kpis: [{ label: 'Settimane invece di mesi per consegnare un\'app', kind: 'efficiency' }, { label: 'Oltre il 50 % di riduzione del time-to-market per gli strumenti interni', kind: 'efficiency' }] },
            { title: 'Sviluppo decentralizzato, controllo centralizzato', audience: 'Il tuo CISO e l\'enterprise architecture', what: 'Le app sono costruite su Dataverse con accessi basati sui ruoli rigorosamente amministrati dall\'IT, politiche di Data Loss Prevention e Application Lifecycle Management unificato.', outcome: 'Decentralizzi lo sviluppo in sicurezza mantenendo un controllo centrale assoluto — eradicando shadow IT e fughe di dati.', kpis: [{ label: '100 % di visibilità IT su tutte le applicazioni custom', kind: 'efficiency' }, { label: 'Zero applicazioni rogue non governate', kind: 'outcome' }] },
            { title: 'Manda in pensione il SaaS legacy, sistema la prima linea', audience: 'Il tuo COO e i responsabili line-of-business', what: 'I lavoratori in prima linea catturano istantaneamente dati puliti tramite app mobile, mentre l\'IT sostituisce costosi strumenti SaaS di nicchia con app interne low-code che fanno lo stesso lavoro — senza canoni di licenza ricorrenti.', outcome: 'Riduci gli errori operativi, acceleri i workflow di prima linea e mandi in pensione in modo sistematico software legacy costoso.', kpis: [{ label: 'Significativa riduzione dei costi di licenza per SaaS di terze parti', kind: 'outcome' }, { label: 'Riduzione misurabile degli errori di data entry operativo', kind: 'outcome' }] },
            { title: 'Un modello operativo digital-first', audience: 'Il tuo CIO, CEO e Consiglio di Amministrazione', what: 'L\'azienda passa da un\'architettura lenta e ancorata al legacy a una cultura digital-first altamente agile, capace di innovare rapidamente su scala.', outcome: 'Abbassi il TCO degli strumenti interni e costruisci un\'azienda davvero agile e digital-first — con il ROI a sostegno.', kpis: [{ label: 'Oltre 140 % di ROI in 3 anni', kind: 'outcome' }, { label: 'Rientro in meno di 6 mesi', kind: 'outcome' }, { label: 'Maggiore agilità digitale complessiva dell\'azienda', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Fonte del ROI superiore al 140 %, della riduzione del 74 % dei costi di sviluppo applicativo e dei risparmi derivanti dalla dismissione di applicazioni di terze parti legacy e dall\'evitare assunzioni di pro-developer.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Fonte della drastica riduzione del time-to-market — da mesi a settimane — e dei guadagni di produttività in prima linea ottenuti sostituendo carta ed Excel con Power Apps mobile.' },
        ],
    },
    ar: {
        headline: 'أفرِغ قائمة الانتظار. أحِل جداول البيانات إلى التقاعد.',
        summary: 'يُدمقرِط Power Apps تطوير التطبيقات. يُسلّم المطوّرون المواطنون تطبيقات مخصَّصة بسرعة باستخدام مساعد الذكاء الاصطناعي Copilot، ويُسرّع المطوّرون المحترفون عمليات النشر المعقَّدة، فيما تحتفظ تقنية المعلومات بحوكمة مركزية على كل ما يُبنى — كي تتمكّن أخيراً من إحالة الأعمال الورقية وExcel وأدوات SaaS الظِّلّية المُكلِفة إلى التقاعد.',
        kpis: [
            { value: '140٪+', label: 'العائد على الاستثمار خلال 3 سنوات', kind: 'outcome' },
            { value: 'أقل من 6 أشهر', label: 'فترة استرداد رأس المال', kind: 'outcome' },
            { value: '−74٪', label: 'تكاليف تطوير التطبيقات', kind: 'efficiency' },
            { value: 'أسابيع مقابل أشهر', label: 'زمن الوصول إلى السوق للأدوات الداخلية', kind: 'efficiency' },
            { value: '↓ shadow IT', label: 'رؤية وحوكمة بنسبة 100٪ لتقنية المعلومات', kind: 'outcome' },
        ],
        bqPre: 'رقمنة العمليات لتعزيز الكفاءة هي مهمتك الجوهرية، لكن قائمة انتظار لتقنية المعلومات بطول 18 شهراً تُجبر وحدات الأعمال اليوم على الاعتماد على جداول بيانات مُجزّأة وعلى تقنية معلومات ظِلّية مُكلِفة.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'إذا افتقر فريق تقنية المعلومات لديك إلى طاقة المطوّرين اللازمة لمعالجة هذا التراكم، ',
        bqHighlight: 'فكيف ستُرقمن المؤسسة وتُسدّد الدَّيْن التقني القديم دون المساس بالأمن أو تضخيم ميزانيتك؟',
        figcaption: 'سؤال استراتيجي يُؤطّر دراسة الجدوى لـ Microsoft Power Apps.',
        bridge: 'إليك كيف يجيب Power Apps عن هذا السؤال',
        outcomesIntro: 'كل مرحلة تُضاعف قيمة سابقتها — من المطوّر المواطن الذي يُسلِّم أول تطبيق له وصولاً إلى الاستراتيجية الرقمية على مستوى المؤسسة بأكملها.',
        rungs: [
            { title: 'بإمكان أي شخص بناء التطبيق الذي يحتاجه', audience: 'المطوّرون المواطنون والمحترفون لديك', what: 'يبني مستخدمو الأعمال بأسلوب السحب والإفلات البديهي ومساعد Copilot، فيما يستخدم المطوّرون المحترفون المنصة نفسها لتجهيز هياكل حلول معقّدة بسرعة ودمج واجهات API القديمة.', outcome: 'تتجاوز عنق الزجاجة للبرمجة الاحترافية وتُمكّن جهات الأعمال من رقمنة إدخالها اليدوي للبيانات وعملياتها الورقية بنفسها.', kpis: [{ label: 'انخفاض 74٪ في تكاليف تطوير التطبيقات', kind: 'outcome' }, { label: 'توفير آلاف الساعات لعمّال الصفوف الأمامية عبر رقمنة المهام الورقية', kind: 'efficiency' }] },
            { title: 'أفرِغ قائمة انتظار تقنية المعلومات', audience: 'مديرو تقنية المعلومات ومكتب إدارة المشاريع لديك', what: 'الحلول التي كانت تتطلّب سابقاً 6–9 أشهر من دورة تطوير البرمجيات التقليدية تُصمَّم وتُبنى وتُنشَر الآن خلال أسابيع — أو أيام.', outcome: 'تتحرّك بسرعة السوق، فتُسلّم لجهات الأعمال أدوات تشغيلية حرجة خلال أسابيع بدلاً من أشهر.', kpis: [{ label: 'أسابيع بدلاً من أشهر لتسليم تطبيق', kind: 'efficiency' }, { label: 'انخفاض يفوق 50٪ في زمن الوصول إلى السوق للأدوات الداخلية', kind: 'efficiency' }] },
            { title: 'بناء لا مركزي، وتحكُّم مركزي', audience: 'كبير مسؤولي أمن المعلومات وهندسة المؤسسة لديك', what: 'تُبنى التطبيقات على Dataverse بأذونات قائمة على الأدوار تُديرها تقنية المعلومات بدقّة، وسياسات منع تسرّب البيانات (DLP)، وإدارة موحَّدة لدورة حياة التطبيقات.', outcome: 'تجعل التطوير لامركزياً بأمان مع الحفاظ على تحكُّم مركزي مطلق — فتقضي على تقنية المعلومات الظِّلّية وتسريب البيانات.', kpis: [{ label: 'رؤية تقنية معلومات بنسبة 100٪ على جميع التطبيقات المخصَّصة', kind: 'efficiency' }, { label: 'صفر تطبيقات شاردة غير مُدارة', kind: 'outcome' }] },
            { title: 'أحِل SaaS القديم إلى التقاعد، وأصلِح الصفّ الأمامي', audience: 'مدير العمليات وقيادات وحدات الأعمال لديك', what: 'يلتقط عمّال الصفوف الأمامية بيانات نظيفة فوراً عبر تطبيقات الجوّال، فيما تستبدل تقنية المعلومات أدوات SaaS المتخصّصة المُكلِفة بتطبيقات داخلية منخفضة الكود تؤدي العمل نفسه — دون رسوم ترخيص متكرّرة.', outcome: 'تُقلّل الأخطاء التشغيلية، وتُسرّع سير عمل الصف الأمامي، وتُحيل بشكل منهجي البرمجيات القديمة المُكلِفة إلى التقاعد.', kpis: [{ label: 'انخفاض ملموس في تكاليف ترخيص SaaS من أطراف ثالثة', kind: 'outcome' }, { label: 'انخفاض قابل للقياس في أخطاء الإدخال التشغيلي للبيانات', kind: 'outcome' }] },
            { title: 'نموذج تشغيلي رقمي أوّلاً', audience: 'مدير تقنية المعلومات والرئيس التنفيذي ومجلس الإدارة لديك', what: 'تنتقل المؤسسة من بنية بطيئة مكبَّلة بالنظم القديمة إلى ثقافة "رقمي أوّلاً" مرنة جداً، قادرة على الابتكار السريع على نطاق واسع.', outcome: 'تُخفّض التكلفة الإجمالية للملكية للأدوات الداخلية وتبني مؤسسة "رقمي أوّلاً" مرنة فعلاً — مع عائد استثمار يدعم ذلك.', kpis: [{ label: 'عائد على الاستثمار يفوق 140٪ خلال 3 سنوات', kind: 'outcome' }, { label: 'استرداد رأس المال في أقل من 6 أشهر', kind: 'outcome' }, { label: 'زيادة في الرشاقة الرقمية الإجمالية للمؤسسة', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'مصدر العائد على الاستثمار البالغ أكثر من 140٪، وانخفاض تكاليف تطوير التطبيقات بنسبة 74٪، والوفورات المالية الناتجة عن إحالة تطبيقات الأطراف الثالثة القديمة إلى التقاعد وتجنّب توظيف مطوّرين محترفين.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'مصدر الانخفاض الكبير في زمن الوصول إلى السوق — من أشهر إلى أسابيع — ومكاسب إنتاجية الصفوف الأمامية المتحقّقة باستبدال الورق وExcel بتطبيقات Power Apps للجوّال.' },
        ],
    },
    nl: {
        headline: 'Werk de backlog weg. Stuur de spreadsheets met pensioen.',
        summary: 'Power Apps democratiseert applicatieontwikkeling. Citizen developers leveren snel custom apps met AI Copilot, pro devs versnellen complexe deployments, en IT houdt gecentraliseerde governance over alles wat gebouwd wordt — zodat u eindelijk papier, Excel en dure shadow-IT-SaaS met pensioen kunt sturen.',
        kpis: [
            { value: '140%+', label: 'ROI over 3 jaar', kind: 'outcome' },
            { value: '< 6 mnd', label: 'Terugverdientijd', kind: 'outcome' },
            { value: '−74%', label: 'Kosten van app-ontwikkeling', kind: 'efficiency' },
            { value: 'Weken vs maanden', label: 'Time-to-market voor interne tools', kind: 'efficiency' },
            { value: '↓ shadow IT', label: '100% IT-zicht & governance', kind: 'outcome' },
        ],
        bqPre: 'Operations digitaliseren om efficiëntie te realiseren is uw kernopdracht, maar vandaag dwingt een 18 maanden lange IT-backlog business units om terug te vallen op gefragmenteerde spreadsheets en dure shadow IT.',
        bqPct: '',
        bqPost: '',
        bqLeadIn: 'Als uw IT-team de developercapaciteit mist om die backlog weg te werken, ',
        bqHighlight: 'hoe gaat u dan de onderneming digitaliseren en legacy-tech-debt afbouwen zonder de security in gevaar te brengen of uw budget op te blazen?',
        figcaption: 'Strategische vraag die de businesscase voor Microsoft Power Apps kadert.',
        bridge: 'Zo beantwoordt Power Apps die vraag',
        outcomesIntro: 'Elke stap versterkt de waarde van de vorige — van de citizen developer die zijn eerste app uitlevert tot een digitale strategie op ondernemingsniveau.',
        rungs: [
            { title: 'Iedereen kan de app bouwen die hij nodig heeft', audience: 'Uw citizen developers en pro devs', what: 'Business users bouwen met intuïtieve drag-and-drop en AI Copilot, terwijl pro devs hetzelfde platform gebruiken om snel complexe oplossingen te scaffolden en legacy-API\'s te integreren.', outcome: 'U omzeilt de pro-code-bottleneck en stelt de business in staat om zijn eigen handmatige data-entry en papierprocessen te digitaliseren.', kpis: [{ label: '74% reductie van de kosten voor app-ontwikkeling', kind: 'outcome' }, { label: 'Duizenden uren bespaard door frontline-medewerkers die papieren taken digitaliseren', kind: 'efficiency' }] },
            { title: 'Werk de IT-backlog weg', audience: 'Uw IT-directie en PMO', what: 'Oplossingen die voorheen 6–9 maanden traditionele SDLC vergden worden nu in weken — of dagen — ontworpen, gebouwd en uitgerold.', outcome: 'U beweegt op het tempo van de markt en levert de business kritieke operationele tools in weken in plaats van maanden.', kpis: [{ label: 'Weken in plaats van maanden voor app-oplevering', kind: 'efficiency' }, { label: 'Meer dan 50% reductie van time-to-market voor interne tooling', kind: 'efficiency' }] },
            { title: 'Decentraal bouwen, centraal sturen', audience: 'Uw CISO en enterprise architecture', what: 'Apps worden gebouwd op Dataverse met strikte, door IT beheerde rolgebaseerde toegang, Data Loss Prevention-policies en geünificeerd Application Lifecycle Management.', outcome: 'U decentraliseert ontwikkeling veilig terwijl u absolute centrale controle behoudt — shadow IT en datalekkage worden geëlimineerd.', kpis: [{ label: '100% IT-zicht op alle custom applicaties', kind: 'efficiency' }, { label: 'Geen onbeheerde rogue-applicaties meer', kind: 'outcome' }] },
            { title: 'Stuur legacy-SaaS met pensioen, fix de frontline', audience: 'Uw COO en line-of-business-leiders', what: 'Frontline-medewerkers leggen direct schone data vast via mobiele apps, terwijl IT dure niche-SaaS-tools vervangt door low-code interne apps die hetzelfde werk doen — zonder de terugkerende licentiekosten.', outcome: 'U verlaagt operationele fouten, versnelt frontline-workflows en stuurt systematisch dure legacy-software met pensioen.', kpis: [{ label: 'Significante verlaging van licentiekosten van derde-partij-SaaS', kind: 'outcome' }, { label: 'Meetbare verlaging van operationele data-entry-fouten', kind: 'outcome' }] },
            { title: 'Een digital-first operating model', audience: 'Uw CIO, CEO en Raad van Bestuur', what: 'De onderneming verschuift van een trage, aan legacy gebonden architectuur naar een uiterst wendbare, digital-first cultuur die op grote schaal snel kan innoveren.', outcome: 'U verlaagt de TCO van interne tooling en bouwt een werkelijk wendbare, digital-first onderneming — met de ROI om dat te onderbouwen.', kpis: [{ label: 'Meer dan 140% ROI over 3 jaar', kind: 'outcome' }, { label: 'Terugverdientijd van minder dan 6 maanden', kind: 'outcome' }, { label: 'Hogere algehele digitale wendbaarheid van de onderneming', kind: 'outcome' }] },
        ],
        references: [
            { title: 'Forrester Consulting — The Total Economic Impact™ of Microsoft Power Apps', note: 'Bron voor de meer dan 140% ROI, de 74% reductie van app-ontwikkelingskosten en de financiële besparingen door het uitfaseren van legacy third-party-applicaties en het vermijden van pro-developer-aanwervingen.' },
            { title: 'Microsoft Power Platform Benchmarks', note: 'Bron voor de drastische verkorting van de time-to-market — van maanden naar weken — en de frontline-productiviteitswinst door papier en Excel te vervangen door mobiele Power Apps.' },
        ],
    },
};

export default function BusinessValuePowerApps({ theme, lang = 'en' }) {
    const s = STRINGS[lang] || STRINGS.en;
    return <BusinessValueView s={s} theme={theme} lang={lang} />;
}
